"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.marker
import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.result


class Test(literal.Action):

    @override
    def run(self):
        result = literal.LocalPosition(
            "position<result>",
        )
        gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
        )
        gateway.create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<source>"
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).run()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<holder>"
        ).particle.get_position(
            local.my_domain_com.my_lib.result.Result
        ).move_particle_to(
            result
        )
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<holder>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).destroy_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<holder>"
        ).destroy_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        result.destroy_particle()
        gateway.destroy_particle()
