"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.outer
import local.my_domain_com.my_lib.payload


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.outer.OuterAction,
    )

    @override
    def run(self):
        source = literal.LocalPosition[Never](
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.destroyer.DestroyerAction,
                local.my_domain_com.my_lib.payload.PayloadPosition,
            ),
        )
        payload_source = literal.LocalPosition[Never](
            "position<payload_source>",
            constraints=(
                local.my_domain_com.my_lib.child.ChildPosition,
            ),
        )
        source.create_particle()
        payload_source.create_particle()
        payload_source.particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).create_particle()
        payload_source.move_particle_to(
            source.particle.get_position(
                local.my_domain_com.my_lib.payload.PayloadPosition
            )
        )
        source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.outer.OuterAction
            ).get_interface_position(
                "position<run>"
            )
        )
        self.on_particle.get_action(
            local.my_domain_com.my_lib.outer.OuterAction
        ).run(OuterDestructionContracts())


class OuterDestructionContracts(local.my_domain_com.my_lib.outer.OuterDestructionContracts):

    @override
    def destroy_position_run__position_payload(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).destroy_particle()
