"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.shared


class KnownDestructor(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.shared.Shared,
    )


@final
class KnownDestructorGuarantees:
    def __init__(self):
        self.global_position_shared = literal.Guarantee()


@final
class KnownDestructorExecution:
    def __init__(
        self,
        action: KnownDestructor,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = KnownDestructorGuarantees()
        self.local_position_holder = literal.LocalPosition(
            "position<holder>",
            scheduler=self.scheduler,
        )
        self.join_for_move_global_position_shared_to_position_holder: literal.Join
        self.join_for_empty_rule_global_position_shared: literal.Join

    def accept_for_empty_rule_global_position_shared(self):
        if not self.join_for_empty_rule_global_position_shared.arrive():
            return
        self.move_global_position_shared_to_position_holder()

    def move_global_position_shared_to_position_holder(self):
        if not self.join_for_move_global_position_shared_to_position_holder.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.shared.Shared
        ).move_particle_to(self.local_position_holder)
        self.local_position_holder.move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.shared.Shared
            )
        )
        self.guarantees.global_position_shared.publish(
            self.scheduler,
        )
