"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class Worker(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class WorkerExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_first = literal.LocalPosition(
            "position<first>",
            scheduler=self.scheduler,
        )
        self.local_position_second = literal.LocalPosition(
            "position<second>",
            scheduler=self.scheduler,
        )

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_first)
        self.create_position_second()

    def create_position_first(self):
        self.local_position_first.create_particle()
        self.local_position_first.destroy_particle()

    def create_position_second(self):
        self.local_position_second.create_particle()
        self.local_position_second.destroy_particle()
