"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.callee_known


class DestroyerDestructionContracts:
    def run_destructors_position_target(self, _particle: literal.Particle):
        pass

    def destroy_position_target(self, _particle: literal.Particle):
        pass

    def run_destructors_position_run(self, _particle: literal.Particle):
        pass

    def destroy_position_run(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = DestroyerDestructionContracts()


class DestroyerAction(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never](
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.callee_known.CalleeKnownPosition,
                    ),
                ),
                literal.LocalPosition[Never]("position<run>"),
            ],
        )

    @override
    def run(self, destruction_contracts: DestroyerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.callee_known.CalleeKnownPosition
        ).create_particle()
        destruction_contracts.run_destructors_position_target(
            self.get_interface_position(
                "position<target>"
            ).particle
        )
        destruction_contracts.destroy_position_target(
            self.get_interface_position(
                "position<target>"
            ).particle
        )
        self.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.callee_known.CalleeKnownPosition
        ).destroy_particle()
        self.get_interface_position(
            "position<target>"
        ).destroy_particle()
        destruction_contracts.run_destructors_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        destruction_contracts.destroy_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        self.get_interface_position(
            "position<run>"
        ).destroy_particle()
