"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class B(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<t>"),
            ],
        )

    @override
    def run(self):
        r = literal.LocalPosition(
            "position<r>",
        )
        r.create_particle()
        self.get_interface_position(
            "position<t>"
        ).destroy_particle()
        r.destroy_particle()
