load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@protobuf//bazel/toolchains:proto_lang_toolchain.bzl", "proto_lang_toolchain")
load("@rules_rust//extensions/pyo3:defs.bzl", "rust_pyo3_toolchain")
load("//tools/bzl:build_file_checks.bzl", "check_build_file")
load(":build_file_checks_test.bzl", "build_file_checks_test_suite")

bzl_library(
    name = "ast_grep",
    srcs = ["ast_grep.bzl"],
)

bzl_library(
    name = "build_file_checks",
    srcs = ["build_file_checks.bzl"],
    visibility = ["//visibility:public"],
)

build_file_checks_test_suite(name = "build_file_checks_test")

config_setting(
    name = "coverage_enabled",
    values = {"collect_code_coverage": "true"},
    visibility = ["//visibility:public"],
)

alias(
    name = "coverage_pytest_dependency",
    actual = select({
        ":coverage_enabled": "@pypi//coverage",
        "//conditions:default": "@pypi//pytest",
    }),
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "format",
    srcs = ["format.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "linters",
    srcs = ["linters.bzl"],
    visibility = ["//visibility:public"],
    deps = [":ast_grep"],
)

alias(
    name = "loop_coverage_pytest_dependency",
    actual = select({
        ":coverage_enabled": "//tools:loop_coverage",
        "//conditions:default": "@pypi//pytest",
    }),
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "package_checks",
    srcs = ["package_checks.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "py_test",
    srcs = ["py_test.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "pyright",
    srcs = ["pyright.bzl"],
    visibility = ["//visibility:public"],
)

exports_files([
    "pyright_test_runner.py",
    "rules_py_pyi_propagation.patch",
    "rules_rust_pyo3_lint_config.patch",
])

proto_lang_toolchain(
    name = "python_toolchain",
    command_line = "--python_out=%s",
    progress_message = "Generating Python proto_library %{label}",
    runtime = "@protobuf//:protobuf_python",
    toolchain_type = "@protobuf//bazel/private:python_toolchain_type",
)

rust_pyo3_toolchain(
    name = "rust_pyo3",
    pyo3 = "@crates//:pyo3",
    pyo3_introspection = "@crates//:pyo3-introspection",
)

toolchain(
    name = "rust_pyo3_toolchain",
    toolchain = ":rust_pyo3",
    toolchain_type = "@rules_rust//extensions/pyo3:rust_toolchain_type",
)

check_build_file()
