"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destruct
import local.my_domain_com.my_lib.marker_a
import local.my_domain_com.my_lib.marker_b
import local.my_domain_com.my_lib.maybe_empty


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.marker_a.MarkerA,
                        local.my_domain_com.my_lib.marker_b.MarkerB,
                        local.my_domain_com.my_lib.maybe_empty.MaybeEmpty,
                        local.my_domain_com.my_lib.destruct.Destruct,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleGuarantees:
    def __init__(self):
        self.guarantee_position_run: list[literal.Task] = []
        self.trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        guarantees: MiddleGuarantees,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.destruction_connections = destruction_connections
        self.execution_trigger_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.join_for_trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_a = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_b = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__when_empty_position_run__global_position_maybe_empty = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__when_occupied_position_run = self.scheduler.create_join(2)

    def accept_for_empty_rule_position_run(self):
        self.move_position_run_to_action_destroyer__position_run()

    def move_position_run_to_action_destroyer__position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.execution_trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer,
            destruction_connections=self.destruction_connections,
        )
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_a)
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_b)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_run__global_position_maybe_empty)
        self.scheduler.submit(self.trigger_action_destroyer__when_occupied_position_run)
        self.scheduler.submit_all(self.guarantees.guarantee_position_run)
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_a)
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_b)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_run__global_position_maybe_empty)
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_run)
        self.trigger_action_destroyer__when_occupied_position_run()

    def trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_a(self):
        if not self.join_for_trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_a.arrive():
            return
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_run__global_position_marker_a()

    def trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_b(self):
        if not self.join_for_trigger_action_destroyer__for_empty_rule_position_run__global_position_marker_b.arrive():
            return
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_run__global_position_marker_b()

    def trigger_action_destroyer__when_empty_position_run__global_position_maybe_empty(self):
        if not self.join_for_trigger_action_destroyer__when_empty_position_run__global_position_maybe_empty.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_empty_position_run__global_position_maybe_empty()

    def trigger_action_destroyer__for_empty_rule_position_run(self):
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_run()

    def trigger_action_destroyer__when_occupied_position_run(self):
        if not self.join_for_trigger_action_destroyer__when_occupied_position_run.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_occupied_position_run()
