load("//tools/bzl:build_file_checks.bzl", "check_build_file")

filegroup(
    name = "reserved_words",
    srcs = [
        "package_repositories.txt",
        "programming_languages.txt",
        "small_common_words.txt",
    ],
    visibility = ["//define/compiler:__subpackages__"],
)

check_build_file()
