"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.item
import local.my_domain_com.my_lib.other


class TestAction(literal.Action):

    @override
    def run(self):
        gateway = literal.LocalPosition[Never](
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.other.OtherAction,
            ),
        )
        box = literal.LocalPosition[Never](
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.item.ItemPosition,
            ),
        )
        destination = literal.LocalPosition[Never](
            "position<destination>",
        )
        gateway.create_particle()
        literal.record_operation("test.create(gateway)")
        box.create_particle()
        literal.record_operation("test.create(box)")
        box.move_particle_to(
            destination
        )
        literal.record_operation("test.move(box, destination)")
        destination.move_particle_to(
            gateway.particle.get_action(
                local.my_domain_com.my_lib.other.OtherAction
            ).get_interface_position(
                "position<box>"
            )
        )
        literal.record_operation("test.move(destination, gateway::/other::box)")
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).run()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<destination>"
        ).destroy_particle()
        literal.record_operation("test.destroy(gateway::/other::destination)")
        gateway.destroy_particle()
        literal.record_operation("test.destroy(gateway)")
