"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.end_dest
import local.my_domain_com.my_lib.end_local
import local.my_domain_com.my_lib.mid_dest
import local.my_domain_com.my_lib.mid_local


class ActDestructionContracts:
    def run_destructors_position_chain_dest(self, _particle: literal.Particle):
        pass

    def destroy_position_chain_dest(self, _particle: literal.Particle):
        pass

    def run_destructors_position_chain_dest__position_mid_dest(self, _particle: literal.Particle):
        pass

    def destroy_position_chain_dest__position_mid_dest(self, _particle: literal.Particle):
        pass

    def run_destructors_position_trigger(self, _particle: literal.Particle):
        pass

    def destroy_position_trigger(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = ActDestructionContracts()


class Act(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger>"),
                literal.LocalPosition("position<iface_dest>"),
                literal.LocalPosition(
                    "position<chain_dest>",
                    constraints=(
                        local.my_domain_com.my_lib.mid_dest.MidDest,
                    ),
                ),
            ],
        )

    @override
    def run(self, destruction_contracts: ActDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        src_a = literal.LocalPosition(
            "position<src_a>",
        )
        src_b = literal.LocalPosition(
            "position<src_b>",
        )
        src_c = literal.LocalPosition(
            "position<src_c>",
        )
        src_d = literal.LocalPosition(
            "position<src_d>",
        )
        local_dest = literal.LocalPosition(
            "position<local_dest>",
        )
        local_chain_dest = literal.LocalPosition(
            "position<local_chain_dest>",
            constraints=(
                local.my_domain_com.my_lib.mid_local.MidLocal,
            ),
        )
        src_a.create_particle()
        src_b.create_particle()
        src_c.create_particle()
        src_d.create_particle()
        local_chain_dest.create_particle()
        local_chain_dest.particle.get_position(
            local.my_domain_com.my_lib.mid_local.MidLocal
        ).create_particle()
        src_a.move_particle_to(
            local_dest
        )
        src_b.move_particle_to(
            self.get_interface_position(
                "position<iface_dest>"
            )
        )
        src_c.move_particle_to(
            self.get_interface_position(
                "position<chain_dest>"
            ).particle.get_position(
                local.my_domain_com.my_lib.mid_dest.MidDest
            ).particle.get_position(
                local.my_domain_com.my_lib.end_dest.EndDest
            )
        )
        src_d.move_particle_to(
            local_chain_dest.particle.get_position(
                local.my_domain_com.my_lib.mid_local.MidLocal
            ).particle.get_position(
                local.my_domain_com.my_lib.end_local.EndLocal
            )
        )
        self.get_interface_position(
            "position<iface_dest>"
        ).destroy_particle()
        destruction_contracts.run_destructors_position_chain_dest(
            self.get_interface_position(
                "position<chain_dest>"
            ).particle
        )
        destruction_contracts.run_destructors_position_chain_dest__position_mid_dest(
            self.get_interface_position(
                "position<chain_dest>"
            ).particle.get_position(
                local.my_domain_com.my_lib.mid_dest.MidDest
            ).particle
        )
        destruction_contracts.destroy_position_chain_dest(
            self.get_interface_position(
                "position<chain_dest>"
            ).particle
        )
        destruction_contracts.destroy_position_chain_dest__position_mid_dest(
            self.get_interface_position(
                "position<chain_dest>"
            ).particle.get_position(
                local.my_domain_com.my_lib.mid_dest.MidDest
            ).particle
        )
        self.get_interface_position(
            "position<chain_dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_dest.MidDest
        ).particle.get_position(
            local.my_domain_com.my_lib.end_dest.EndDest
        ).destroy_particle()
        self.get_interface_position(
            "position<chain_dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_dest.MidDest
        ).destroy_particle()
        self.get_interface_position(
            "position<chain_dest>"
        ).destroy_particle()
        destruction_contracts.run_destructors_position_trigger(
            self.get_interface_position(
                "position<trigger>"
            ).particle
        )
        destruction_contracts.destroy_position_trigger(
            self.get_interface_position(
                "position<trigger>"
            ).particle
        )
        self.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
        local_dest.destroy_particle()
        local_chain_dest.particle.get_position(
            local.my_domain_com.my_lib.mid_local.MidLocal
        ).particle.get_position(
            local.my_domain_com.my_lib.end_local.EndLocal
        ).destroy_particle()
        local_chain_dest.particle.get_position(
            local.my_domain_com.my_lib.mid_local.MidLocal
        ).destroy_particle()
        local_chain_dest.destroy_particle()
