load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:build_file_checks.bzl", "check_build_file")
load("//tools/bzl:format.bzl", "format_test")

py_library(
    name = "schema",
    srcs = ["__init__.py"],
    visibility = ["//defcl/schema:__subpackages__"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

check_build_file()
