"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.transitive_implied


class Implied(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.transitive_implied.TransitiveImplied,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class ImpliedGuarantees:
    def __init__(self):
        self.guarantee_global_position_transitive_implied: list[literal.Task] = []


@final
class ImpliedExecution:
    def __init__(
        self,
        action: Implied,
        scheduler: literal.Scheduler,
        guarantees: ImpliedGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees

    def accept_when_empty_global_position_transitive_implied(self):
        self.create_global_position_transitive_implied()

    def create_global_position_transitive_implied(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.transitive_implied.TransitiveImplied
        ).create_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_global_position_transitive_implied)
