"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class Act(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<src>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class ActGuarantees:
    def __init__(self):
        self.guarantee_position_src: list[literal.Task] = []
        self.guarantee_position_trigger: list[literal.Task] = []


@final
class ActExecution:
    def __init__(
        self,
        action: Act,
        scheduler: literal.Scheduler,
        guarantees: ActGuarantees,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.destruction_connections = destruction_connections

    def accept_for_empty_rule_position_src(self):
        self.destroy_position_src()

    def accept_for_empty_rule_position_trigger(self):
        self.destroy_position_trigger()

    def destroy_position_src(self):
        literal.continue_destruction(self.continue_destroy_position_src)

    def continue_destroy_position_src(self):
        self.action.get_interface_position(
            "position<src>"
        ).destroy_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_src)

    def destroy_position_trigger(self):
        literal.continue_destruction(self.continue_destroy_position_trigger)

    def continue_destroy_position_trigger(self):
        self.action.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_trigger)
