"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.fifth
import local.my_domain_com.my_lib.marker


class FifthDestructorAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.fifth.FifthPosition,
        local.my_domain_com.my_lib.marker.MarkerPosition,
    )

    @override
    def run(self):
        holder = literal.LocalPosition[Never](
            "position<holder>",
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.fifth.FifthPosition
        ).move_particle_to(
            holder
        )
        holder.move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.fifth.FifthPosition
            )
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.marker.MarkerPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.marker.MarkerPosition
        ).destroy_particle()
