"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.holder
import local.my_domain_com.my_lib.outer


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.holder.Holder,
        local.my_domain_com.my_lib.outer.Outer,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).run()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
