"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class InnerDestructorA(literal.Action):
    pass


@final
class InnerDestructorAExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_work_a = literal.LocalPosition(
            "position<work_a>",
            scheduler=self.scheduler,
        )

    def accept_action_parent(self):
        self.create_position_work_a()

    def create_position_work_a(self):
        self.local_position_work_a.create_particle()
        self.local_position_work_a.destroy_particle()
