"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class DestructorA(literal.Action):

    @override
    def run(self):
        work = literal.LocalPosition(
            "position<work>",
        )
        work.create_particle()
        literal.record_operation("destructor_a.create(work)")
        work.destroy_particle()
        literal.record_operation("destructor_a.destroy(work)")
