"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.left_child


class Left(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.left_child.LeftChild,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class LeftGuarantees:
    def __init__(self):
        self.guarantee_action_left_child__position_trigger_pos: list[literal.Task] = []
        self.trigger_action_left_child = local.my_domain_com.my_lib.left_child.LeftChildGuarantees()


@final
class LeftExecution:
    def __init__(
        self,
        action: Left,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: LeftGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.execution_trigger_action_left_child: local.my_domain_com.my_lib.left_child.LeftChildExecution
        self.join_for_trigger_action_left_child__when_empty_global_position_marker = literal.Join(2)

    def accept_when_empty_action_left_child__position_trigger_pos(self):
        self.create_action_left_child__position_trigger_pos()

    def accept_when_empty_global_position_marker(self):
        self.trigger_action_left_child__when_empty_global_position_marker()

    def create_action_left_child__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.left_child.LeftChild
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/left_child::trigger_pos",
            1,
        )
        self.execution_trigger_action_left_child = local.my_domain_com.my_lib.left_child.LeftChildExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.left_child.LeftChild
            ),
            self.scheduler,
            self.trace_execution,
            "left_child",
            self.guarantees.trigger_action_left_child,
        )
        self.scheduler.submit_all(self.guarantees.guarantee_action_left_child__position_trigger_pos)
        self.trigger_action_left_child__when_empty_global_position_marker()

    def trigger_action_left_child__when_empty_global_position_marker(self):
        if not self.join_for_trigger_action_left_child__when_empty_global_position_marker.arrive():
            return
        self.execution_trigger_action_left_child.accept_when_empty_global_position_marker()
