"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class DestroyerDestructionContracts:
    def run_destructors_position_run(self, _particle: literal.Particle):
        pass

    def destroy_position_run(self, _particle: literal.Particle):
        pass

    def run_destructors_position_left(self, _particle: literal.Particle):
        pass

    def destroy_position_left(self, _particle: literal.Particle):
        pass

    def run_destructors_position_right(self, _particle: literal.Particle):
        pass

    def destroy_position_right(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = DestroyerDestructionContracts()


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<left>"),
                literal.LocalPosition("position<right>"),
                literal.LocalPosition("position<run>"),
            ],
        )

    @override
    def run(self, destruction_contracts: DestroyerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        first = literal.LocalPosition(
            "position<first>",
        )
        destruction_contracts_2 = literal.LocalPosition(
            "position<destruction_contracts>",
        )
        self.get_interface_position(
            "position<left>"
        ).move_particle_to(
            first
        )
        self.get_interface_position(
            "position<right>"
        ).move_particle_to(
            destruction_contracts_2
        )
        destruction_contracts.run_destructors_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        destruction_contracts.destroy_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        self.get_interface_position(
            "position<run>"
        ).destroy_particle()
        destruction_contracts.run_destructors_position_left(
            first.particle
        )
        destruction_contracts.run_destructors_position_right(
            destruction_contracts_2.particle
        )
        destruction_contracts.destroy_position_left(
            first.particle
        )
        destruction_contracts.destroy_position_right(
            destruction_contracts_2.particle
        )
        first.destroy_particle()
        destruction_contracts_2.destroy_particle()
