"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal
from define.runtime import tracing

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.middle


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_connection_action_middle: tracing.DestructionConnection
        self.destruction_position_action_middle__position_run__global_position_child: literal.Position
        self.destruction_connection_action_middle = tracing.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_middle__position_run__global_position_child,
        )
        self.execution_action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
            self.trace_execution,
            "middle",
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_run: self.destruction_connection_action_middle,
            },
            ),
        )
        self.execution_action_middle.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_action_middle.join_for_move_position_run_to_action_destroyer__position_run = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_source)
        self.execution_action_middle.on_action_parent_occupied()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "source",
            1,
        )
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "source::/child",
            1,
        )
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ).get_interface_position(
                "position<run>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "source",
            "/middle::run",
            1,
        )
        self.destruction_position_action_middle__position_run__global_position_child = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_action_middle.accept_for_empty_rule_position_run()

    def destroy_action_middle__position_run__global_position_child(self):
        self.destruction_position_action_middle__position_run__global_position_child.destroy_particle()
        self.scheduler.destroy_completed(
            self.destruction_connection_action_middle.trace_execution,
            "run::/child",
            1,
        )
        self.destruction_connection_action_middle.complete()
