"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.final


class ReactA(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/react_a>"

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition("position<trigger>"),
                literal.InterfacePosition(
                    "position<result>",
                    constraints=(
                        local.my_domain_com.my_lib.final.Final,
                    ),
                ),
            ],
            trigger_position_name="position<trigger>",
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<result>"
        ).create_particle()
        self.get_interface_position(
            "position<result>"
        ).particle.get_action(
            "action<my.domain.com:my_lib:/final>"
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
