"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.worker


class First(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger_pos>"),
            ],
        )

    @override
    def run(self):
        gw = literal.LocalPosition(
            "position<gw>",
            constraints=(
                local.my_domain_com.my_lib.worker.Worker,
            ),
        )
        gw.create_particle()
        literal.record_operation("first.create(gw)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("first.create(gw::/worker::trigger_pos)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("first.destroy(gw::/worker::trigger_pos)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("first.create(gw::/worker::trigger_pos)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("first.destroy(gw::/worker::trigger_pos)")
        gw.destroy_particle()
        literal.record_operation("first.destroy(gw)")
