"""Generated by the Define compiler."""

from typing import ClassVar

from define.runtime import literal

import local.my_domain_com.my_lib.direct_child
import local.my_domain_com.my_lib.guaranteed_child


class Parent(literal.GlobalPosition):
    constraints: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.direct_child.DirectChild,
        local.my_domain_com.my_lib.guaranteed_child.GuaranteedChild,
    )
