"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.implied
import local.my_domain_com.my_lib.implier_one
import local.my_domain_com.my_lib.implier_two


class Runner(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/runner>"

    def __init__(self):
        super().__init__(
            interface_positions=[
                literal.InterfacePosition("position<run>"),
                literal.InterfacePosition(
                    "position<source>",
                    constraints=(
                        local.my_domain_com.my_lib.implier_one.ImplierOne,
                        local.my_domain_com.my_lib.implier_two.ImplierTwo,
                    ),
                ),
                literal.InterfacePosition(
                    "position<dest>",
                    constraints=(
                        local.my_domain_com.my_lib.implied.Implied,
                    ),
                ),
            ],
            trigger_position_name="position<run>",
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<source>"
        ).create_dimension_point()
        self.get_interface_position(
            "position<source>"
        ).move_dimension_point_to(
            self.get_interface_position(
                "position<dest>"
            )
        )
