"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class SecondDestructionContracts:
    def run_destructors_position_trigger_pos(self, _particle: literal.Particle):
        pass

    def destroy_position_trigger_pos(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = SecondDestructionContracts()


class Second(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger_pos>"),
            ],
        )

    @override
    def run(self, destruction_contracts: SecondDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        destruction_contracts.run_destructors_position_trigger_pos(
            self.get_interface_position(
                "position<trigger_pos>"
            ).particle
        )
        destruction_contracts.destroy_position_trigger_pos(
            self.get_interface_position(
                "position<trigger_pos>"
            ).particle
        )
        self.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
