"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class Test(literal.Action):

    @override
    def run(self):
        self_ = literal.LocalPosition(
            "position<self_>",
        )
        self__ = literal.LocalPosition(
            "position<self__>",
        )
        self___ = literal.LocalPosition(
            "position<self>",
        )
        self_.create_particle()
        literal.record_operation("test.create(self_)")
        self__.create_particle()
        literal.record_operation("test.create(self__)")
        self___.create_particle()
        literal.record_operation("test.create(self)")
        self_.destroy_particle()
        literal.record_operation("test.destroy(self_)")
        self__.destroy_particle()
        literal.record_operation("test.destroy(self__)")
        self___.destroy_particle()
        literal.record_operation("test.destroy(self)")
