load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/lint:format.bzl", "format_test")

py_library(
    name = "defcl",
    srcs = ["__init__.py"],
    visibility = ["//defcl:__subpackages__"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)
