"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class InnerDestructionContracts:
    def run_destructors_position_inner_run(self, _particle: literal.Particle):
        pass

    def destroy_position_inner_run(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = InnerDestructionContracts()


class Inner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<inner_run>"),
            ],
        )

    @override
    def run(self, destruction_contracts: InnerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        local = literal.LocalPosition(
            "position<local>",
        )
        self.get_interface_position(
            "position<inner_run>"
        ).move_particle_to(
            local
        )
        destruction_contracts.run_destructors_position_inner_run(
            local.particle
        )
        destruction_contracts.destroy_position_inner_run(
            local.particle
        )
        local.destroy_particle()
