%import common.LF -> NEWLINE

# Terminals
PATH_SEGMENT: /[^:<>\/{}\s]+/
MULTIVERSE_NAME.2: /[^:<>\/{}\s]+(?=:[^:>]*:[^:>]*:\/)/
AUTHORITY_DOMAIN.1: /[^:<>\/{}\s]+(?=[^:>]*:[^:>]*:\/)/
AUTHORITY_PATH_SEGMENT: /[^:<>\/{}\s]+/
UNIVERSE_NAME: /[^:<>\/{}\s]+(?=:(?![^:>]*:)[^:>]*\/)/

# General

# Ignore leading whitespace (indentation) on lines inside blocks.
# The lookbehind ensures we only match after a newline, and the
# lookahead ensures we don't consume trailing whitespace on blank lines.
%ignore /(?<=\n) +(?=\S)/

# Allow only visible characters in comments.
# TODO: Disallow invisible Unicode characters per spec.
COMMENT: / *#(?:[^\x00-\x1F\x7F]*[^\x00-\x1F\x7F ])?/
%ignore COMMENT

terminator: "." NEWLINE
block: " {" NEWLINE NEWLINE* "}" NEWLINE
// TODO: Enforce that leading whitespace before "}" matches the opening
// statement's leading whitespace, per spec.
?definition_end: terminator | block

# Global Names

authority_path: ("/" AUTHORITY_PATH_SEGMENT)+
authority: AUTHORITY_DOMAIN authority_path?

fqun: MULTIVERSE_NAME ":" authority ":" UNIVERSE_NAME ":"
    | authority ":" UNIVERSE_NAME ":"
    | UNIVERSE_NAME ":"

global_name_path: ("/" PATH_SEGMENT)+
global_name: fqun global_name_path

# Global Definitions

position_definition: "define the potential position" "<" global_name ">" definition_end
action_definition: "define the potential action" "<" global_name ">" (terminator | action_definition_block)

# Local Names

LOCAL_NAME: /[^:<>{}\s]+/

# Action Definition Block

local_position_definition: "define the position" "<" LOCAL_NAME ">" terminator
trigger_conditions_block: "it happens when" " {" NEWLINE NEWLINE* "}"
action_statements_block: " and it does" " {" NEWLINE NEWLINE* "}" NEWLINE
_trigger_and_action: trigger_conditions_block action_statements_block
action_definition_block: " {" NEWLINE (NEWLINE | local_position_definition)* _trigger_and_action NEWLINE* "}" NEWLINE

# Root

definition: position_definition | action_definition
start: NEWLINE* definition (NEWLINE* definition)* NEWLINE*
