"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.mover


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            TestGuarantees(),
        )
        execution.create_position_parent()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_parent__action_mover = local.my_domain_com.my_lib.mover.MoverGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_parent = literal.LocalPosition(
            "position<parent>",
            constraints=(
                local.my_domain_com.my_lib.mover.Mover,
            ),
            scheduler=self.scheduler,
        )
        guarantees.trigger_position_parent__action_mover.guarantee_position_destination.append(
            self.destroy_position_parent__action_mover__position_destination
        )
        guarantees.trigger_position_parent__action_mover.guarantee_position_source.append(
            self.destroy_position_parent
        )
        guarantees.trigger_position_parent__action_mover.guarantee_position_run.append(
            self.destroy_position_parent
        )
        self.execution_trigger_position_parent__action_mover: local.my_domain_com.my_lib.mover.MoverExecution
        self.join_for_destroy_position_parent = self.scheduler.create_join(3)
        self.join_for_trigger_position_parent__action_mover__for_empty_rule_position_source = self.scheduler.create_join(2)
        self.join_for_trigger_position_parent__action_mover__for_empty_rule_position_run = self.scheduler.create_join(2)

    def create_position_parent(self):
        self.local_position_parent.create_particle()
        self.scheduler.submit(self.create_position_parent__action_mover__position_source)
        self.create_position_parent__action_mover__position_run()

    def create_position_parent__action_mover__position_source(self):
        self.local_position_parent.particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<source>"
        ).create_particle()
        self.trigger_position_parent__action_mover__for_empty_rule_position_source()

    def create_position_parent__action_mover__position_run(self):
        self.local_position_parent.particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.execution_trigger_position_parent__action_mover = local.my_domain_com.my_lib.mover.MoverExecution(
            self.local_position_parent.particle.get_action(
                local.my_domain_com.my_lib.mover.Mover
            ),
            self.scheduler,
            self.guarantees.trigger_position_parent__action_mover,
        )
        self.scheduler.submit(self.trigger_position_parent__action_mover__for_empty_rule_position_run)
        self.scheduler.submit(self.trigger_position_parent__action_mover__for_empty_rule_position_source)
        self.scheduler.submit(self.trigger_position_parent__action_mover__when_empty_position_destination)
        self.trigger_position_parent__action_mover__for_empty_rule_position_run()

    def destroy_position_parent__action_mover__position_destination(self):
        self.local_position_parent.particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<destination>"
        ).destroy_particle()
        self.destroy_position_parent()

    def destroy_position_parent(self):
        if not self.join_for_destroy_position_parent.arrive():
            return
        self.local_position_parent.destroy_particle()

    def trigger_position_parent__action_mover__for_empty_rule_position_source(self):
        if not self.join_for_trigger_position_parent__action_mover__for_empty_rule_position_source.arrive():
            return
        self.execution_trigger_position_parent__action_mover.accept_for_empty_rule_position_source()

    def trigger_position_parent__action_mover__when_empty_position_destination(self):
        self.execution_trigger_position_parent__action_mover.accept_when_empty_position_destination()

    def trigger_position_parent__action_mover__for_empty_rule_position_run(self):
        if not self.join_for_trigger_position_parent__action_mover__for_empty_rule_position_run.arrive():
            return
        self.execution_trigger_position_parent__action_mover.accept_for_empty_rule_position_run()
