"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<gateway>",
                    constraints=(
                        local.my_domain_com.my_lib.other.Other,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.create_position_gateway()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        guarantees.trigger_position_gateway__action_other.guarantee_position_trigger_pos__move__position_output.append(
            self.destroy_position_gateway__action_other__position_output
        )
        self.execution_trigger_position_gateway__action_other: local.my_domain_com.my_lib.other.OtherExecution
        self.join_for_trigger_position_gateway__action_other__for_empty_rule_position_trigger_pos = self.scheduler.create_join(2)

    def create_position_gateway(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).create_particle()
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.execution_trigger_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherExecution(
            self.action.get_interface_position(
                "position<gateway>"
            ).particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ),
            self.scheduler,
            self.guarantees.trigger_position_gateway__action_other,
        )
        self.scheduler.submit(self.trigger_position_gateway__action_other__for_empty_rule_position_trigger_pos)
        self.trigger_position_gateway__action_other__for_empty_rule_position_trigger_pos()

    def destroy_position_gateway__action_other__position_output(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<output>"
        ).destroy_particle()

    def trigger_position_gateway__action_other__for_empty_rule_position_trigger_pos(self):
        if not self.join_for_trigger_position_gateway__action_other__for_empty_rule_position_trigger_pos.arrive():
            return
        self.execution_trigger_position_gateway__action_other.accept_for_empty_rule_position_trigger_pos()
