"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child


class ClassVarDestructionContracts:
    def run_destructors_position_trigger_pos(self, _particle: literal.Particle):
        pass

    def destroy_position_trigger_pos(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = ClassVarDestructionContracts()


class ClassVar_(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.child.Child,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger_pos>"),
            ],
        )

    @override
    def run(self, destruction_contracts: ClassVarDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).destroy_particle()
        self_2 = literal.LocalPosition(
            "position<self>",
        )
        self_ = literal.LocalPosition(
            "position<self_>",
        )
        literal_2 = literal.LocalPosition(
            "position<literal>",
        )
        super = literal.LocalPosition(
            "position<super>",
        )
        type = literal.LocalPosition(
            "position<type>",
        )
        typing = literal.LocalPosition(
            "position<typing>",
        )
        class_2 = literal.LocalPosition(
            "position<class>",
        )
        class_2_2 = literal.LocalPosition(
            "position<class_2>",
        )
        local_2 = literal.LocalPosition(
            "position<local>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
        )
        self_2.create_particle()
        self_.create_particle()
        literal_2.create_particle()
        super.create_particle()
        type.create_particle()
        typing.create_particle()
        class_2.create_particle()
        class_2_2.create_particle()
        local_2.create_particle()
        local_2.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        destruction_contracts.run_destructors_position_trigger_pos(
            self.get_interface_position(
                "position<trigger_pos>"
            ).particle
        )
        destruction_contracts.destroy_position_trigger_pos(
            self.get_interface_position(
                "position<trigger_pos>"
            ).particle
        )
        self.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self_2.destroy_particle()
        self_.destroy_particle()
        literal_2.destroy_particle()
        super.destroy_particle()
        type.destroy_particle()
        typing.destroy_particle()
        class_2.destroy_particle()
        class_2_2.destroy_particle()
        local_2.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).destroy_particle()
        local_2.destroy_particle()
