# Root package

load("@bazel_skylib//rules:native_binary.bzl", "native_binary", "native_test")

exports_files([
    ".rules",
    "pyproject.toml",
    ".claude/settings.json",
    ".cursor/cli.json",
])

# --- Lock file management ---

native_binary(
    name = "update_lock",
    src = "//tools:update_lock",
    out = "update_lock_bin",
    args = ["$(location @multitool//tools/uv)"],
    data = [
        "pyproject.toml",
        "uv.lock",
        "//tools:pyproject.toml",
        "@multitool//tools/uv",
    ],
    tags = [
        "local",
        "requires-network",
    ],
)

# --- Lock file freshness ---

native_test(
    name = "uv_lock_test",
    size = "small",
    src = "//tools:uv_lock_test",
    out = "uv_lock_test_bin",
    args = ["$(location @multitool//tools/uv)"],
    data = [
        "pyproject.toml",
        "uv.lock",
        "//tools:pyproject.toml",
        "@multitool//tools/uv",
    ],
    tags = [
        "local",
        "requires-network",
    ],
)
