# Root package

load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@npm//:basedpyright/package_json.bzl", basedpyright_bin = "bin")
load("@npm//:defs.bzl", "npm_link_all_packages")

exports_files([
    ".codex/rules/default.rules",
    "pyproject.toml",
    ".claude/settings.json",
    ".cursor/cli.json",
])

exports_files(
    ["uv.lock"],
    visibility = ["//tools:__pkg__"],
)

# basedpyright has to go here instead of in tools/, because otherwise
# it tries to type check its own code, which is slow.
npm_link_all_packages(name = "node_modules")

basedpyright_bin.basedpyright_binary(
    name = "basedpyright",
    chdir = package_name(),
    visibility = ["//:__subpackages__"],
)

basedpyright_bin.basedpyright_langserver_binary(
    name = "basedpyright-langserver",
    chdir = package_name(),
    visibility = ["//:__subpackages__"],
)

# --- Lock file management ---

native_binary(
    name = "update_lock",
    src = "//tools:update_lock",
    out = "update_lock_bin",
    args = ["$(location @multitool//tools/uv)"],
    data = [
        "pyproject.toml",
        "uv.lock",
        "@multitool//tools/uv",
        "@re2//python:uv_metadata",
    ],
    tags = [
        "local",
        "requires-network",
    ],
)
