"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.parent


class MiddleDestructionContracts:
    def run_destructors_position_iface(self, _particle: literal.Particle):
        pass

    def destroy_position_iface(self, _particle: literal.Particle):
        pass

    def run_destructors_position_iface__position_parent(self, _particle: literal.Particle):
        pass

    def destroy_position_iface__position_parent(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = MiddleDestructionContracts()


class Middle(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<run>"),
                literal.LocalPosition(
                    "position<iface>",
                    constraints=(
                        local.my_domain_com.my_lib.parent.Parent,
                    ),
                ),
            ],
        )

    @override
    def run(self, destruction_contracts: MiddleDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        gw = literal.LocalPosition(
            "position<gw>",
            constraints=(
                local.my_domain_com.my_lib.inner.Inner,
            ),
        )
        gw.create_particle()
        self.get_interface_position(
            "position<iface>"
        ).move_particle_to(
            gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            )
        )
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).run()
        destruction_contracts.run_destructors_position_iface(
            gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            ).particle
        )
        destruction_contracts.run_destructors_position_iface__position_parent(
            gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            ).particle.get_position(
                local.my_domain_com.my_lib.parent.Parent
            ).particle
        )
        destruction_contracts.destroy_position_iface(
            gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            ).particle
        )
        destruction_contracts.destroy_position_iface__position_parent(
            gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            ).particle.get_position(
                local.my_domain_com.my_lib.parent.Parent
            ).particle
        )
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).destroy_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).destroy_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).destroy_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).destroy_particle()
        gw.destroy_particle()
