"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.grandchild1
import local.my_domain_com.my_lib.grandchild2
import local.my_domain_com.my_lib.parent


class InnerAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.ParentPosition,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<trigger_pos>"),
            ],
        )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild1.Grandchild1Position
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild2.Grandchild2Position
        ).create_particle()
