load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")

py_library(
    name = "config",
    srcs = ["__init__.py"],
    visibility = ["//define/config:__subpackages__"],
    deps = ["//define"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)
