"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.run


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def run(self):
        source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.run.Run,
            ),
        )
        child_particle = literal.LocalPosition(
            "position<child_particle>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
        )
        source.create_particle()
        child_particle.create_particle()
        child_particle.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        child_particle.move_particle_to(
            source.particle.get_position(
                local.my_domain_com.my_lib.run.Run
            )
        )
        source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).run()
