"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.run


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.run.Run,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.guarantee_position_run: list[literal.Task] = []


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        guarantees: DestroyerGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.join_for_destroy_position_run = literal.Join(2)

    def accept_for_empty_rule_position_run__global_position_run(self):
        self.destroy_position_run__global_position_run()

    def accept_for_empty_rule_position_run(self):
        self.destroy_position_run()

    def destroy_position_run__global_position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.run.Run
        ).destroy_particle()
        self.destroy_position_run()

    def destroy_position_run(self):
        if not self.join_for_destroy_position_run.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_run)
