"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.implied
import local.my_domain_com.my_lib.implier_one
import local.my_domain_com.my_lib.implier_two


class Runner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<source>",
                    constraints=(
                        local.my_domain_com.my_lib.implier_one.ImplierOne,
                        local.my_domain_com.my_lib.implier_two.ImplierTwo,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<dest>",
                    constraints=(
                        local.my_domain_com.my_lib.implied.Implied,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class RunnerGuarantees:
    def __init__(self):
        self.guarantee_position_source: list[literal.Task] = []
        self.guarantee_position_dest: list[literal.Task] = []
        self.guarantee_position_run: list[literal.Task] = []
        self.trigger_position_source__action_implier_one = local.my_domain_com.my_lib.implier_one.ImplierOneGuarantees()
        self.trigger_position_source__action_implier_two = local.my_domain_com.my_lib.implier_two.ImplierTwoGuarantees()


@final
class RunnerExecution:
    def __init__(
        self,
        action: Runner,
        scheduler: literal.Scheduler,
        guarantees: RunnerGuarantees,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.destruction_connections = destruction_connections
        guarantees.trigger_position_source__action_implier_one.guarantee_global_position_implied.append(
            self.trigger_position_source__action_implier_two__when_empty_global_position_implied
        )
        self.execution_trigger_position_source__action_implier_one: local.my_domain_com.my_lib.implier_one.ImplierOneExecution
        self.execution_trigger_position_source__action_implier_two: local.my_domain_com.my_lib.implier_two.ImplierTwoExecution
        self.join_for_move_position_source_to_position_dest = self.scheduler.create_join(2)
        self.join_for_trigger_position_source__action_implier_one__when_empty_global_position_implied = self.scheduler.create_join(2)
        self.join_for_trigger_position_source__action_implier_two__when_empty_global_position_implied = self.scheduler.create_join(2)

    def accept_when_empty_position_source(self):
        self.create_position_source()

    def accept_when_empty_position_dest(self):
        self.move_position_source_to_position_dest()

    def accept_for_empty_rule_position_run(self):
        self.destroy_position_run()

    def create_position_source(self):
        self.action.get_interface_position(
            "position<source>"
        ).create_particle()
        self.execution_trigger_position_source__action_implier_one = local.my_domain_com.my_lib.implier_one.ImplierOneExecution(
            self.action.get_interface_position(
                "position<source>"
            ).particle.get_action(
                local.my_domain_com.my_lib.implier_one.ImplierOne
            ),
            self.scheduler,
            self.guarantees.trigger_position_source__action_implier_one,
        )
        self.execution_trigger_position_source__action_implier_two = local.my_domain_com.my_lib.implier_two.ImplierTwoExecution(
            self.action.get_interface_position(
                "position<source>"
            ).particle.get_action(
                local.my_domain_com.my_lib.implier_two.ImplierTwo
            ),
            self.scheduler,
            self.guarantees.trigger_position_source__action_implier_two,
        )
        self.scheduler.submit(self.move_position_source_to_position_dest)
        self.scheduler.submit(self.trigger_position_source__action_implier_one__when_empty_global_position_implied)
        self.scheduler.submit(self.trigger_position_source__action_implier_one__when_empty_global_position_implied)
        self.trigger_position_source__action_implier_two__when_empty_global_position_implied()

    def move_position_source_to_position_dest(self):
        if not self.join_for_move_position_source_to_position_dest.arrive():
            return
        self.action.get_interface_position(
            "position<source>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<dest>"
            )
        )
        self.scheduler.submit(self.create_position_dest__global_position_implied)
        self.scheduler.continue_with(self.guarantees.guarantee_position_source)

    def create_position_dest__global_position_implied(self):
        self.action.get_interface_position(
            "position<dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.implied.Implied
        ).create_particle()
        self.action.get_interface_position(
            "position<dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.implied.Implied
        ).destroy_particle()
        self.action.get_interface_position(
            "position<dest>"
        ).destroy_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_dest)

    def destroy_position_run(self):
        literal.continue_destruction(self.continue_destroy_position_run)

    def continue_destroy_position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_run)

    def trigger_position_source__action_implier_one__when_empty_global_position_implied(self):
        if not self.join_for_trigger_position_source__action_implier_one__when_empty_global_position_implied.arrive():
            return
        self.execution_trigger_position_source__action_implier_one.accept_when_empty_global_position_implied()

    def trigger_position_source__action_implier_two__when_empty_global_position_implied(self):
        if not self.join_for_trigger_position_source__action_implier_two__when_empty_global_position_implied.arrive():
            return
        self.execution_trigger_position_source__action_implier_two.accept_when_empty_global_position_implied()
