"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.make_thing


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
            TestGuarantees(),
        )
        execution.create_position_box()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_box__global_action_make_thing = local.my_domain_com.my_lib.make_thing.MakeThingGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: TestGuarantees,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.make_thing.MakeThing,
            ),
            scheduler=self.scheduler,
        )
        guarantees.trigger_position_box__global_action_make_thing.guarantee_position_result.append(
            self.destroy_position_box__global_action_make_thing__position_result
        )
        guarantees.trigger_position_box__global_action_make_thing.guarantee_position_result.append(
            self.trigger_position_box__global_action_make_thing__position_result__global_action_destructor__action_parent
        )
        guarantees.trigger_position_box__global_action_make_thing.guarantee_position_result.append(
            self.trigger_position_box__global_action_make_thing__position_result__global_action_destructor
        )
        self.trigger_position_box__global_action_make_thing__execution: local.my_domain_com.my_lib.make_thing.MakeThingExecution
        self.trigger_position_box__global_action_make_thing__position_result__global_action_destructor__execution: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.join_for_destroy_position_box = literal.Join(2)
        self.join_for_trigger_position_box__global_action_make_thing__action_parent = literal.Join(2)
        self.join_for_trigger_position_box__global_action_make_thing__when_empty_position_result = literal.Join(2)
        self.join_for_trigger_position_box__global_action_make_thing__position_result__global_action_destructor__action_parent = literal.Join(2)

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.scheduler.submit(self.create_position_box__global_action_make_thing__position_run)
        self.scheduler.submit(self.trigger_position_box__global_action_make_thing__action_parent)
        self.trigger_position_box__global_action_make_thing__when_empty_position_result()

    def create_position_box__global_action_make_thing__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/make_thing::run",
            1,
        )
        self.init_trigger_position_box__global_action_make_thing__execution()
        self.scheduler.submit(self.destroy_position_box__global_action_make_thing__position_run)
        self.scheduler.submit(self.trigger_position_box__global_action_make_thing__action_parent)
        self.trigger_position_box__global_action_make_thing__when_empty_position_result()

    def destroy_position_box__global_action_make_thing__position_result(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        ).get_interface_position(
            "position<result>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/make_thing::result",
            1,
        )
        self.destroy_position_box()

    def destroy_position_box__global_action_make_thing__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/make_thing::run",
            1,
        )
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box",
            1,
        )

    def init_trigger_position_box__global_action_make_thing__execution(self):
        action = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        )
        self.trigger_position_box__global_action_make_thing__execution = local.my_domain_com.my_lib.make_thing.MakeThingExecution(
            action,
            self.scheduler,
            self.trace_execution,
            "make_thing",
            self.guarantees.trigger_position_box__global_action_make_thing,
        )

    def init_trigger_position_box__global_action_make_thing__position_result__global_action_destructor__execution(self):
        self.trigger_position_box__global_action_make_thing__position_result__global_action_destructor__execution = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
            self.trace_execution,
            "destructor",
        )

    def trigger_position_box__global_action_make_thing__position_result__global_action_destructor(self):
        self.init_trigger_position_box__global_action_make_thing__position_result__global_action_destructor__execution()
        self.trigger_position_box__global_action_make_thing__position_result__global_action_destructor__action_parent()

    def trigger_position_box__global_action_make_thing__action_parent(self):
        if not self.join_for_trigger_position_box__global_action_make_thing__action_parent.arrive():
            return
        self.trigger_position_box__global_action_make_thing__execution.accept_action_parent()

    def trigger_position_box__global_action_make_thing__when_empty_position_result(self):
        if not self.join_for_trigger_position_box__global_action_make_thing__when_empty_position_result.arrive():
            return
        self.trigger_position_box__global_action_make_thing__execution.accept_when_empty_position_result()

    def trigger_position_box__global_action_make_thing__position_result__global_action_destructor__action_parent(self):
        if not self.join_for_trigger_position_box__global_action_make_thing__position_result__global_action_destructor__action_parent.arrive():
            return
        self.trigger_position_box__global_action_make_thing__position_result__global_action_destructor__execution.accept_action_parent()
