"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<run>"),
            ],
        )

    @override
    def run(self):
        local = literal.LocalPosition(
            "position<local>",
        )
        self.get_interface_position(
            "position<run>"
        ).move_particle_to(
            local
        )
        literal.record_operation("destroyer.move(run, local)")
        local.destroy_particle()
        literal.record_operation("destroyer.destroy(local)")
