"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.a_b.cd.a


class Test(literal.GlobalPosition):
    typed_name: ClassVar[str] = "position<a.b:cd:/test>"
    constraints: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.a_b.cd.a.A,
    )

    @override
    def after_assigned(self):
        self.create_particle()
        self.particle.get_position(
            "position<a.b:cd:/a>"
        ).create_particle()
        self.particle.get_position(
            "position<a.b:cd:/a>"
        ).particle.get_action(
            "action<a.b:cd:/b>"
        ).get_interface_position(
            "position<t>"
        ).create_particle()
