load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/lint:format.bzl", "format_test")

py_library(
    name = "valid",
    srcs = ["__init__.py"],
    visibility = ["//defcl/testdata/valid:__subpackages__"],
    deps = ["//defcl/testdata"],
)

filegroup(
    name = "valid_files",
    srcs = glob(["*.defcl"]),
    visibility = ["//defcl/testdata:__pkg__"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)
