"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.filled
import local.my_domain_com.my_lib.other


class TestAction(literal.Action):

    @override
    def run(self):
        box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.other.OtherAction,
            ),
        )
        box.create_particle()
        box.particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).run()
        box.particle.get_position(
            local.my_domain_com.my_lib.filled.FilledPosition
        ).destroy_particle()
        box.destroy_particle()
