"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class DestructorA(literal.Action):
    pass


@final
class DestructorAExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_work = literal.LocalPosition(
            "position<work>",
            scheduler=self.scheduler,
        )

    def accept_action_parent(self):
        self.create_position_work()

    def create_position_work(self):
        self.local_position_work.create_particle()
        self.local_position_work.destroy_particle()
