"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.caller_a
import local.my_domain_com.my_lib.caller_b


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.caller_a.CallerA,
        local.my_domain_com.my_lib.caller_b.CallerB,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_action_caller_a__position_trigger_pos)
        execution.create_action_caller_b__position_trigger_pos()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_action_caller_a = local.my_domain_com.my_lib.caller_a.CallerAGuarantees()
        self.trigger_action_caller_b = local.my_domain_com.my_lib.caller_b.CallerBGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.execution_trigger_action_caller_a: local.my_domain_com.my_lib.caller_a.CallerAExecution
        self.execution_trigger_action_caller_b: local.my_domain_com.my_lib.caller_b.CallerBExecution
        self.join_for_trigger_action_caller_a__for_empty_rule_position_trigger_pos = self.scheduler.create_join(2)
        self.join_for_trigger_action_caller_b__for_empty_rule_position_trigger_pos = self.scheduler.create_join(2)

    def create_action_caller_a__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.caller_a.CallerA
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.execution_trigger_action_caller_a = local.my_domain_com.my_lib.caller_a.CallerAExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.caller_a.CallerA
            ),
            self.scheduler,
            self.guarantees.trigger_action_caller_a,
        )
        self.scheduler.submit(self.trigger_action_caller_a__for_empty_rule_position_trigger_pos)
        self.scheduler.submit(self.trigger_action_caller_a__action_parent)
        self.trigger_action_caller_a__for_empty_rule_position_trigger_pos()

    def create_action_caller_b__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.caller_b.CallerB
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.execution_trigger_action_caller_b = local.my_domain_com.my_lib.caller_b.CallerBExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.caller_b.CallerB
            ),
            self.scheduler,
            self.guarantees.trigger_action_caller_b,
        )
        self.scheduler.submit(self.trigger_action_caller_b__for_empty_rule_position_trigger_pos)
        self.scheduler.submit(self.trigger_action_caller_b__action_parent)
        self.trigger_action_caller_b__for_empty_rule_position_trigger_pos()

    def trigger_action_caller_a__action_parent(self):
        self.execution_trigger_action_caller_a.accept_action_parent()

    def trigger_action_caller_a__for_empty_rule_position_trigger_pos(self):
        if not self.join_for_trigger_action_caller_a__for_empty_rule_position_trigger_pos.arrive():
            return
        self.execution_trigger_action_caller_a.accept_for_empty_rule_position_trigger_pos()

    def trigger_action_caller_b__action_parent(self):
        self.execution_trigger_action_caller_b.accept_action_parent()

    def trigger_action_caller_b__for_empty_rule_position_trigger_pos(self):
        if not self.join_for_trigger_action_caller_b__for_empty_rule_position_trigger_pos.arrive():
            return
        self.execution_trigger_action_caller_b.accept_for_empty_rule_position_trigger_pos()
