"""Generated by the Define compiler."""
from __future__ import annotations

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.callee
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.later


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_position_box)
        execution.scheduler.submit(execution.create_position_later_box)
        execution.create_position_carrier()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_box__action_callee = local.my_domain_com.my_lib.callee.CalleeGuarantees()
        self.trigger_position_later_box__action_later = local.my_domain_com.my_lib.later.LaterGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.callee.Callee,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.destructor.Destructor,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_later_box = literal.LocalPosition(
            "position<later_box>",
            constraints=(
                local.my_domain_com.my_lib.later.Later,
            ),
            scheduler=self.scheduler,
        )
        guarantees.trigger_position_later_box__action_later.guarantee_position_target.append(
            self.destroy_position_later_box
        )
        guarantees.trigger_position_box__action_callee.guarantee_position_target.append(
            self.destroy_position_box
        )
        self.execution_trigger_position_box__action_callee: local.my_domain_com.my_lib.callee.CalleeExecution
        self.destruction_connection_trigger_position_box__action_callee: literal.DestructionConnection
        self.execution_trigger_position_later_box__action_later: local.my_domain_com.my_lib.later.LaterExecution
        self.destruction_connection_trigger_position_later_box__action_later: literal.DestructionConnection
        self.join_for_move_position_carrier_to_position_box__action_callee__position_target = literal.Join(2)
        self.join_for_move_position_carrier_to_position_later_box__action_later__position_target = literal.Join(2)
        self.join_for_destroy_position_later_box = literal.Join(2)
        self.join_for_destroy_position_box = literal.Join(2)
        self.join_for_trigger_position_box__action_callee__for_empty_rule_position_target = literal.Join(2)
        self.join_for_trigger_position_later_box__action_later__for_empty_rule_position_target = literal.Join(2)

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.submit(self.move_position_carrier_to_position_box__action_callee__position_target)
        self.create_position_box__action_callee__position_run()

    def create_position_later_box(self):
        self.local_position_later_box.create_particle()
        self.scheduler.submit(self.move_position_carrier_to_position_later_box__action_later__position_target)
        self.create_position_later_box__action_later__position_run()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.move_position_carrier_to_position_box__action_callee__position_target()

    def move_position_carrier_to_position_box__action_callee__position_target(self):
        if not self.join_for_move_position_carrier_to_position_box__action_callee__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.callee.Callee
            ).get_interface_position(
                "position<target>"
            )
        )
        self.scheduler.submit(self.create_position_carrier_2)
        self.trigger_position_box__action_callee__for_empty_rule_position_target()

    def create_position_carrier_2(self):
        self.local_position_carrier.create_particle()
        self.move_position_carrier_to_position_later_box__action_later__position_target()

    def move_position_carrier_to_position_later_box__action_later__position_target(self):
        if not self.join_for_move_position_carrier_to_position_later_box__action_later__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.local_position_later_box.particle.get_action(
                local.my_domain_com.my_lib.later.Later
            ).get_interface_position(
                "position<target>"
            )
        )
        self.trigger_position_later_box__action_later__for_empty_rule_position_target()

    def create_position_box__action_callee__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_connection_trigger_position_box__action_callee = literal.DestructionConnection(
            self.scheduler,
            0,
            self.trigger_position_box__action_callee__position_target__action_destructor,
        )
        self.execution_trigger_position_box__action_callee = local.my_domain_com.my_lib.callee.CalleeExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.callee.Callee
            ),
            self.scheduler,
            self.guarantees.trigger_position_box__action_callee,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.callee.CalleeExecution.continue_destroy_position_target: self.destruction_connection_trigger_position_box__action_callee,
            },
            ),
        )
        self.scheduler.submit(self.destroy_position_box__action_callee__position_run)
        self.trigger_position_box__action_callee__for_empty_rule_position_target()

    def create_position_later_box__action_later__position_run(self):
        self.local_position_later_box.particle.get_action(
            local.my_domain_com.my_lib.later.Later
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_connection_trigger_position_later_box__action_later = literal.DestructionConnection(
            self.scheduler,
            0,
            self.trigger_position_later_box__action_later__position_target__action_destructor,
        )
        self.execution_trigger_position_later_box__action_later = local.my_domain_com.my_lib.later.LaterExecution(
            self.local_position_later_box.particle.get_action(
                local.my_domain_com.my_lib.later.Later
            ),
            self.scheduler,
            self.guarantees.trigger_position_later_box__action_later,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.later.LaterExecution.continue_destroy_position_target: self.destruction_connection_trigger_position_later_box__action_later,
            },
            ),
        )
        self.scheduler.submit(self.destroy_position_later_box__action_later__position_run)
        self.trigger_position_later_box__action_later__for_empty_rule_position_target()

    def destroy_position_later_box__action_later__position_run(self):
        self.local_position_later_box.particle.get_action(
            local.my_domain_com.my_lib.later.Later
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.destroy_position_later_box()

    def destroy_position_later_box(self):
        if not self.join_for_destroy_position_later_box.arrive():
            return
        self.local_position_later_box.destroy_particle()

    def destroy_position_box__action_callee__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()

    def trigger_position_box__action_callee__for_empty_rule_position_target(self):
        if not self.join_for_trigger_position_box__action_callee__for_empty_rule_position_target.arrive():
            return
        self.execution_trigger_position_box__action_callee.accept_for_empty_rule_position_target()

    def trigger_position_later_box__action_later__for_empty_rule_position_target(self):
        if not self.join_for_trigger_position_later_box__action_later__for_empty_rule_position_target.arrive():
            return
        self.execution_trigger_position_later_box__action_later.accept_for_empty_rule_position_target()

    def trigger_position_box__action_callee__position_target__action_destructor(self):
        execution = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
        )
        execution.accept_action_parent()

    def trigger_position_later_box__action_later__position_target__action_destructor(self):
        execution = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
        )
        execution.accept_action_parent()
