"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.parent


class Destroyer(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.global_position_parent = literal.Guarantee()
        self.position_trigger_pos = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.join_for_destroy_global_position_parent: literal.Join
        self.join_for_destroy_position_trigger_pos: literal.Join
        self.join_for_empty_rule_global_position_parent: literal.Join
        self.join_for_empty_rule_position_trigger_pos: literal.Join

    def accept_for_empty_rule_global_position_parent(self):
        if not self.join_for_empty_rule_global_position_parent.arrive():
            return
        self.destroy_global_position_parent()

    def accept_for_empty_rule_position_trigger_pos(self):
        if not self.join_for_empty_rule_position_trigger_pos.arrive():
            return
        self.destroy_position_trigger_pos()

    def destroy_global_position_parent(self):
        if not self.join_for_destroy_global_position_parent.arrive():
            return
        literal.continue_destruction(self.continue_destroy_global_position_parent)

    def continue_destroy_global_position_parent(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).destroy_particle()
        self.guarantees.global_position_parent.publish(
            self.scheduler,
        )

    def destroy_position_trigger_pos(self):
        if not self.join_for_destroy_position_trigger_pos.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger_pos)

    def continue_destroy_position_trigger_pos(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.guarantees.position_trigger_pos.publish(
            self.scheduler,
        )
