"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.helper
import local.my_domain_com.my_lib.worker


class Test(literal.EntryPoint):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<source>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<temp>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<gw_a>",
                    constraints=(
                        local.my_domain_com.my_lib.worker.Worker,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<gw_b>",
                    constraints=(
                        local.my_domain_com.my_lib.helper.Helper,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_position_source)
        execution.scheduler.submit(execution.create_position_gw_a)
        execution.create_position_gw_b()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_gw_b__global_action_helper = local.my_domain_com.my_lib.helper.HelperGuarantees()
        self.trigger_position_gw_a__global_action_worker = local.my_domain_com.my_lib.worker.WorkerGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        guarantees.trigger_position_gw_b__global_action_helper.guarantee_position_slot__move__position_out.append(
            self.move_position_gw_b__global_action_helper__position_out_to_position_gw_a__global_action_worker__position_slot
        )
        self.trigger_position_gw_b__global_action_helper__execution: local.my_domain_com.my_lib.helper.HelperExecution
        self.trigger_position_gw_a__global_action_worker__execution: local.my_domain_com.my_lib.worker.WorkerExecution
        self.join_for_move_position_source_to_position_gw_a__global_action_worker__position_slot = literal.Join(2)
        self.join_for_move_position_temp_to_position_gw_b__global_action_helper__position_slot = literal.Join(2)
        self.join_for_move_position_gw_b__global_action_helper__position_out_to_position_gw_a__global_action_worker__position_slot = literal.Join(2)
        self.join_for_trigger_position_gw_b__global_action_helper__for_empty_rule_position_slot = literal.Join(2)
        self.join_for_trigger_position_gw_a__global_action_worker__for_empty_rule_position_slot = literal.Join(2)

    def create_position_source(self):
        self.action.get_interface_position(
            "position<source>"
        ).create_particle()
        self.move_position_source_to_position_gw_a__global_action_worker__position_slot()

    def create_position_gw_a(self):
        self.action.get_interface_position(
            "position<gw_a>"
        ).create_particle()
        self.scheduler.submit(self.move_position_source_to_position_gw_a__global_action_worker__position_slot)
        self.create_position_gw_a__global_action_worker__position_trigger_pos()

    def create_position_gw_b(self):
        self.action.get_interface_position(
            "position<gw_b>"
        ).create_particle()
        self.scheduler.submit(self.move_position_temp_to_position_gw_b__global_action_helper__position_slot)
        self.create_position_gw_b__global_action_helper__position_trigger_pos()

    def move_position_source_to_position_gw_a__global_action_worker__position_slot(self):
        if not self.join_for_move_position_source_to_position_gw_a__global_action_worker__position_slot.arrive():
            return
        self.action.get_interface_position(
            "position<source>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<gw_a>"
            ).particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ).get_interface_position(
                "position<slot>"
            )
        )
        self.action.get_interface_position(
            "position<gw_a>"
        ).particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<slot>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<temp>"
            )
        )
        self.scheduler.submit(self.move_position_temp_to_position_gw_b__global_action_helper__position_slot)
        self.move_position_gw_b__global_action_helper__position_out_to_position_gw_a__global_action_worker__position_slot()

    def move_position_temp_to_position_gw_b__global_action_helper__position_slot(self):
        if not self.join_for_move_position_temp_to_position_gw_b__global_action_helper__position_slot.arrive():
            return
        self.action.get_interface_position(
            "position<temp>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<gw_b>"
            ).particle.get_action(
                local.my_domain_com.my_lib.helper.Helper
            ).get_interface_position(
                "position<slot>"
            )
        )
        self.trigger_position_gw_b__global_action_helper__for_empty_rule_position_slot()

    def create_position_gw_b__global_action_helper__position_trigger_pos(self):
        self.action.get_interface_position(
            "position<gw_b>"
        ).particle.get_action(
            local.my_domain_com.my_lib.helper.Helper
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.init_trigger_position_gw_b__global_action_helper__execution()
        self.trigger_position_gw_b__global_action_helper__for_empty_rule_position_slot()

    def move_position_gw_b__global_action_helper__position_out_to_position_gw_a__global_action_worker__position_slot(self):
        if not self.join_for_move_position_gw_b__global_action_helper__position_out_to_position_gw_a__global_action_worker__position_slot.arrive():
            return
        self.action.get_interface_position(
            "position<gw_b>"
        ).particle.get_action(
            local.my_domain_com.my_lib.helper.Helper
        ).get_interface_position(
            "position<out>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<gw_a>"
            ).particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ).get_interface_position(
                "position<slot>"
            )
        )
        self.trigger_position_gw_a__global_action_worker__for_empty_rule_position_slot()

    def create_position_gw_a__global_action_worker__position_trigger_pos(self):
        self.action.get_interface_position(
            "position<gw_a>"
        ).particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.init_trigger_position_gw_a__global_action_worker__execution()
        self.trigger_position_gw_a__global_action_worker__for_empty_rule_position_slot()

    def init_trigger_position_gw_b__global_action_helper__execution(self):
        action = self.action.get_interface_position(
            "position<gw_b>"
        ).particle.get_action(
            local.my_domain_com.my_lib.helper.Helper
        )
        self.trigger_position_gw_b__global_action_helper__execution = local.my_domain_com.my_lib.helper.HelperExecution(
            action,
            self.scheduler,
            self.guarantees.trigger_position_gw_b__global_action_helper,
        )

    def init_trigger_position_gw_a__global_action_worker__execution(self):
        action = self.action.get_interface_position(
            "position<gw_a>"
        ).particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        )
        self.trigger_position_gw_a__global_action_worker__execution = local.my_domain_com.my_lib.worker.WorkerExecution(
            action,
            self.scheduler,
            self.guarantees.trigger_position_gw_a__global_action_worker,
        )

    def trigger_position_gw_b__global_action_helper__for_empty_rule_position_slot(self):
        if not self.join_for_trigger_position_gw_b__global_action_helper__for_empty_rule_position_slot.arrive():
            return
        self.trigger_position_gw_b__global_action_helper__execution.accept_for_empty_rule_position_slot()

    def trigger_position_gw_a__global_action_worker__for_empty_rule_position_slot(self):
        if not self.join_for_trigger_position_gw_a__global_action_worker__for_empty_rule_position_slot.arrive():
            return
        self.trigger_position_gw_a__global_action_worker__execution.accept_for_empty_rule_position_slot()
