"""Generated by the Define compiler."""

from typing import ClassVar

from define.runtime import literal


class MarkerB(literal.GlobalPosition):
    typed_name: ClassVar[str] = "position<my.domain.com:my_lib:/marker_b>"
