"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.result


class Child(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.result.Result,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class ChildGuarantees:
    def __init__(self, scheduler: literal.Scheduler):
        self.global_position_result = literal.Fanout(scheduler)


@final
class ChildExecution:
    def __init__(
        self,
        action: Child,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = ChildGuarantees(self.scheduler)
        self.local_position_scratch = literal.LocalPosition(
            "position<scratch>",
            scheduler=self.scheduler,
        )

    def on_action_parent_occupied(self):
        self.create_position_scratch()

    def accept_when_empty_global_position_result(self):
        self.create_global_position_result()

    def create_position_scratch(self):
        self.local_position_scratch.create_particle()
        self.scheduler.operation_completed(
            self.trace_execution,
            "create(scratch)",
        )
        self.local_position_scratch.destroy_particle()
        self.scheduler.operation_completed(
            self.trace_execution,
            "destroy(scratch)",
        )

    def create_global_position_result(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.result.Result
        ).create_particle()
        self.scheduler.operation_completed(
            self.trace_execution,
            "create(/result)",
        )
        self.guarantees.global_position_result.run()
