"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer


class MiddleDestructionContracts:
    def run_destructors_position_run(self, _particle: literal.Particle):
        pass

    def destroy_position_run(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = MiddleDestructionContracts()


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<run>"),
            ],
        )

    @override
    def run(self, destruction_contracts: MiddleDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.get_interface_position(
            "position<run>"
        ).move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        literal.record_operation("middle.move(run, /destroyer::run)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).run(
            DestroyerDestructionContracts(
                destruction_contracts.run_destructors_position_run,
                destruction_contracts.destroy_position_run,
            ),
        )
        local_2 = literal.LocalPosition(
            "position<local>",
        )
        local_2.create_particle()
        literal.record_operation("middle.create(local)")
        local_2.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        literal.record_operation("middle.move(local, /destroyer::run)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).run()


class DestroyerDestructionContracts(local.my_domain_com.my_lib.destroyer.DestroyerDestructionContracts):
    def __init__(
        self,
        run_destructors_position_run: literal.DestructionContribution,
        destroy_position_run: literal.DestructionContribution,
    ):
        self._run_destructors_position_run: literal.DestructionContribution = run_destructors_position_run
        self._destroy_position_run: literal.DestructionContribution = destroy_position_run

    @override
    def run_destructors_position_run(self, particle: literal.Particle):
        self._run_destructors_position_run(
            particle
        )

    @override
    def destroy_position_run(self, particle: literal.Particle):
        self._destroy_position_run(
            particle
        )
