filegroup(
    name = "generator",
    testonly = True,
    srcs = glob(["**"]),
    visibility = [
        "//define/compiler/codegen:__pkg__",
        "//define/testdata:__pkg__",
    ],
)

filegroup(
    name = "profile_source",
    testonly = True,
    srcs = ["constructor_entry_point_adds_no_diagnostics/source.dfn"],
    visibility = ["//tools:__pkg__"],
)
