"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.leaf
import local.my_domain_com.my_lib.mid


class TestAction(literal.Action):

    @override
    def run(self):
        box = literal.LocalPosition[Never](
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.mid.MidPosition,
            ),
        )
        source = literal.LocalPosition[Never](
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.mid.MidPosition,
            ),
        )
        box.create_particle()
        literal.record_operation("test.create(box)")
        box.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).create_particle()
        literal.record_operation("test.create(box::/mid)")
        box.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.LeafPosition
        ).create_particle()
        literal.record_operation("test.create(box::/mid::/leaf)")
        box.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.LeafPosition
        ).destroy_particle()
        literal.record_operation("test.destroy(box::/mid::/leaf)")
        box.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).destroy_particle()
        literal.record_operation("test.destroy(box::/mid)")
        box.destroy_particle()
        literal.record_operation("test.destroy(box)")
        source.create_particle()
        literal.record_operation("test.create(source)")
        source.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).create_particle()
        literal.record_operation("test.create(source::/mid)")
        source.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.LeafPosition
        ).create_particle()
        literal.record_operation("test.create(source::/mid::/leaf)")
        source.move_particle_to(
            box
        )
        literal.record_operation("test.move(source, box)")
        box.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.LeafPosition
        ).destroy_particle()
        literal.record_operation("test.destroy(box::/mid::/leaf)")
        box.particle.get_position(
            local.my_domain_com.my_lib.mid.MidPosition
        ).destroy_particle()
        literal.record_operation("test.destroy(box::/mid)")
        box.destroy_particle()
        literal.record_operation("test.destroy(box)")
