"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal


class TestAction(literal.Action):

    @override
    def run(self):
        a = literal.LocalPosition[Never](
            "position<a>",
        )
        b = literal.LocalPosition[Never](
            "position<b>",
        )
        c = literal.LocalPosition[Never](
            "position<c>",
        )
        d = literal.LocalPosition[Never](
            "position<d>",
        )
        a.create_particle()
        a.move_particle_to(
            b
        )
        b.move_particle_to(
            c
        )
        c.move_particle_to(
            d
        )
        d.move_particle_to(
            a
        )
        a.destroy_particle()
