"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.inner


class Outer(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.inner.Inner,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class OuterGuarantees:
    def __init__(self):
        self.guarantee_action_inner__position_run: list[literal.Task] = []


@final
class OuterExecution:
    def __init__(
        self,
        action: Outer,
        scheduler: literal.Scheduler,
        guarantees: OuterGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.execution_trigger_action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.join_for_trigger_action_inner__action_parent = literal.Join(2)

    def accept_when_empty_action_inner__position_run(self):
        self.create_action_inner__position_run()

    def accept_action_parent(self):
        self.trigger_action_inner__action_parent()

    def create_action_inner__position_run(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.execution_trigger_action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.scheduler,
        )
        self.scheduler.submit_all(self.guarantees.guarantee_action_inner__position_run)
        self.trigger_action_inner__action_parent()

    def trigger_action_inner__action_parent(self):
        if not self.join_for_trigger_action_inner__action_parent.arrive():
            return
        self.execution_trigger_action_inner.accept_action_parent()
