"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.destruct


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.destruct.Destruct,
                    ),
                ),
            ],
        )

    @override
    def run(self):
        self.get_interface_position(
            "position<run>"
        ).particle.get_action(
            local.my_domain_com.my_lib.destruct.Destruct
        ).run()
        self.get_interface_position(
            "position<run>"
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(run)")
