"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.marker


class RightChild(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.marker.Marker,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class RightChildGuarantees:
    def __init__(self):
        self.guarantee_global_position_marker: list[literal.Task] = []


@final
class RightChildExecution:
    def __init__(
        self,
        action: RightChild,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: RightChildGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees

    def accept_for_empty_rule_global_position_marker(self):
        self.destroy_global_position_marker()

    def destroy_global_position_marker(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/marker",
            1,
        )
        self.scheduler.continue_with(self.guarantees.guarantee_global_position_marker)
