"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.empty
import local.my_domain_com.my_lib.occupied


class DestroyerDestructionContracts:
    def run_destructors_position_target(self, _particle: literal.Particle):
        pass

    def destroy_position_target(self, _particle: literal.Particle):
        pass

    def run_destructors_position_trigger(self, _particle: literal.Particle):
        pass

    def destroy_position_trigger(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = DestroyerDestructionContracts()


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.occupied.Occupied,
                        local.my_domain_com.my_lib.empty.Empty,
                    ),
                ),
                literal.LocalPosition("position<trigger>"),
            ],
        )

    @override
    def run(self, destruction_contracts: DestroyerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.occupied.Occupied
        ).create_particle()
        literal.record_operation("destroyer.create(target::/occupied)")
        self.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.empty.Empty
        ).create_particle()
        literal.record_operation("destroyer.create(target::/empty)")
        self.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.empty.Empty
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(target::/empty)")
        destruction_contracts.run_destructors_position_target(
            self.get_interface_position(
                "position<target>"
            ).particle
        )
        destruction_contracts.destroy_position_target(
            self.get_interface_position(
                "position<target>"
            ).particle
        )
        self.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.occupied.Occupied
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(target::/occupied)")
        self.get_interface_position(
            "position<target>"
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(target)")
        destruction_contracts.run_destructors_position_trigger(
            self.get_interface_position(
                "position<trigger>"
            ).particle
        )
        destruction_contracts.destroy_position_trigger(
            self.get_interface_position(
                "position<trigger>"
            ).particle
        )
        self.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(trigger)")
