"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.box
import local.my_domain_com.my_lib.outer


class WrapperDestructionContracts:
    def run_destructors_position_run(self, _particle: literal.Particle):
        pass

    def destroy_position_run(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = WrapperDestructionContracts()


class WrapperAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.box.BoxPosition,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<run>"),
            ],
        )

    @override
    def run(self, destruction_contracts: WrapperDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        destruction_contracts.run_destructors_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        destruction_contracts.destroy_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        self.get_interface_position(
            "position<run>"
        ).destroy_particle()
        literal.record_operation("wrapper.destroy(run)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.box.BoxPosition
        ).create_particle()
        literal.record_operation("wrapper.create(/box)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.box.BoxPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.outer.OuterAction
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        literal.record_operation("wrapper.create(/box::/outer::run)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.box.BoxPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.outer.OuterAction
        ).run()

    def run_destructors_of_global_position_box__action_outer(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.box.BoxPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.outer.OuterAction
        ).run_destructors_of_action_make_a()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.box.BoxPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.outer.OuterAction
        ).run_destructors_of_action_make_b()
