load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "invalid",
    srcs = ["__init__.py"],
    visibility = ["//defcl/testdata/invalid:__subpackages__"],
    deps = ["//defcl/testdata"],
)

filegroup(
    name = "invalid_files",
    srcs = glob(["**/*.defcl"]) + [
        "//defcl/testdata/invalid/semantics:semantics_files",
    ],
    visibility = ["//defcl/testdata:__pkg__"],
)
