"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent


class Test(literal.Action):
    is_constructor: ClassVar[bool] = True

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition(
                    "position<local>",
                    constraints=(
                        local.my_domain_com.my_lib.parent.Parent,
                    ),
                ),
            ],
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<local>"
        ).create_particle()
        self.get_interface_position(
            "position<local>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        self.get_interface_position(
            "position<local>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
