filegroup(
    name = "compiler_memory",
    testonly = True,
    srcs = [
        ":guarantee_expansion",
        ":project_config",
    ],
    visibility = [
        "//define/compiler:__pkg__",
        "//define/testdata:__pkg__",
    ],
)

filegroup(
    name = "guarantee_expansion",
    testonly = True,
    srcs = ["guarantee_expansion.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "project_config",
    testonly = True,
    srcs = [".define/project/config.defcl"],
)
