filegroup(
    name = "compiler_memory",
    testonly = True,
    srcs = [
        ":deep_requirements",
        ":destruction_fragments",
        ":fragment_fanout_joins",
        ":guarantee_expansion",
        ":large_operation_volume",
        ":many_substantial_actions",
        ":operation_dependencies",
        ":project_config",
        ":reference_graph_project",
    ],
    visibility = [
        "//define/compiler:__pkg__",
        "//define/testdata:__pkg__",
    ],
)

filegroup(
    name = "deep_requirements",
    testonly = True,
    srcs = ["deep_requirements.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "destruction_fragments",
    testonly = True,
    srcs = ["destruction_fragments.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "fragment_fanout_joins",
    testonly = True,
    srcs = ["fragment_fanout_joins.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "guarantee_expansion",
    testonly = True,
    srcs = ["guarantee_expansion.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "large_operation_volume",
    testonly = True,
    srcs = ["large_operation_volume.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "many_substantial_actions",
    testonly = True,
    srcs = ["many_substantial_actions.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "operation_dependencies",
    testonly = True,
    srcs = ["operation_dependencies.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "project_config",
    testonly = True,
    srcs = [".define/project/config.defcl"],
)

filegroup(
    name = "reference_graph_project",
    testonly = True,
    srcs = glob(["reference_graph_project/**/*.dfn"]) + [
        "reference_graph_project/.define/project/config.defcl",
    ],
    visibility = ["//define/compiler:__pkg__"],
)

filegroup(
    name = "reference_graph_project_entry",
    testonly = True,
    srcs = ["reference_graph_project/test.dfn"],
    visibility = ["//define/compiler:__pkg__"],
)
