"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.grandchild
import local.my_domain_com.my_lib.triggered


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.triggered.TriggeredAction,
    )

    @override
    def run(self):
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.GrandchildPosition
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).run()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).destroy_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.TriggeredAction
        ).get_interface_position(
            "position<input>"
        ).destroy_particle()
