load("//tools/bzl:pyright.bzl", "pyright_test")

_TRACING_TESTDATA_EXCLUDES = [
    "**/expected_trace/**",
    "**/operation_trace.json",
]

filegroup(
    name = "codegen_testdata",
    testonly = True,
    srcs = glob(
        ["**"],
        exclude = _TRACING_TESTDATA_EXCLUDES,
    ),
    visibility = [
        "//define/compiler/codegen:__pkg__",
        "//define/testdata/codegen:__pkg__",
    ],
)

filegroup(
    name = "operation_graph_many_actions_integration",
    testonly = True,
    srcs = glob(
        ["**"],
        exclude = [
            "**/expected/**",
            "**/occupied_positions.txt",
        ] + _TRACING_TESTDATA_EXCLUDES,
    ),
    visibility = [
        "//define/compiler/validator/reference_graph/reference_graph_validator_tests:__pkg__",
        "//define/testdata:__pkg__",
    ],
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    srcs = glob(["**/*.py"]),
    deps = [
        "//define/runtime:literal",
        "//define/runtime:tracing",
    ],
)
