"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal
from define.runtime import tracing

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destruct
import local.my_domain_com.my_lib.required


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_position_source)
        execution.create_action_destroyer__position_trigger_pos()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()
        self.trigger_action_destroyer__position_parent__action_destruct = local.my_domain_com.my_lib.destruct.DestructGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.destruct.Destruct,
                local.my_domain_com.my_lib.required.Required,
            ),
            scheduler=self.scheduler,
        )
        self.execution_trigger_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_trigger_action_destroyer: tracing.DestructionConnection
        self.execution_trigger_action_destroyer__position_parent__action_destruct: local.my_domain_com.my_lib.destruct.DestructExecution
        self.join_for_trigger_action_destroyer__for_empty_rule_position_parent__global_position_required = literal.Join(2)
        self.join_for_trigger_action_destroyer__position_parent__action_destruct__when_empty_global_position_required__global_position_work = literal.Join(2)

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "source",
            1,
        )
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.required.Required
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "source::/required",
            1,
        )
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<parent>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "source",
            "/destroyer::parent",
            1,
        )
        self.execution_trigger_action_destroyer__position_parent__action_destruct = local.my_domain_com.my_lib.destruct.DestructExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<parent>"
            ).particle.get_action(
                local.my_domain_com.my_lib.destruct.Destruct
            ),
            self.scheduler,
            self.scheduler.execution_created(
                self.trace_execution,
                "destroyer",
            ),
            "destruct",
            self.guarantees.trigger_action_destroyer__position_parent__action_destruct,
        )
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_parent__global_position_required)
        self.trigger_action_destroyer__position_parent__action_destruct__when_empty_global_position_required__global_position_work()

    def create_action_destroyer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/destroyer::trigger_pos",
            1,
        )
        self.destruction_connection_trigger_action_destroyer = tracing.DestructionConnection(
            self.scheduler,
            1,
            self.trigger_action_destroyer__position_parent__action_destruct__when_empty_global_position_required__global_position_work,
        )
        self.guarantees.trigger_action_destroyer__position_parent__action_destruct.guarantee_global_position_required__global_position_work.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.execution_trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.trace_execution,
            "destroyer",
            self.guarantees.trigger_action_destroyer,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_parent__global_position_required: self.destruction_connection_trigger_action_destroyer,
            },
            ),
        )
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_parent__global_position_required)
        self.trigger_action_destroyer__for_empty_rule_position_parent()

    def trigger_action_destroyer__for_empty_rule_position_parent__global_position_required(self):
        if not self.join_for_trigger_action_destroyer__for_empty_rule_position_parent__global_position_required.arrive():
            return
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_parent__global_position_required()

    def trigger_action_destroyer__for_empty_rule_position_parent(self):
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_parent()

    def trigger_action_destroyer__position_parent__action_destruct__when_empty_global_position_required__global_position_work(self):
        if not self.join_for_trigger_action_destroyer__position_parent__action_destruct__when_empty_global_position_required__global_position_work.arrive():
            return
        self.execution_trigger_action_destroyer__position_parent__action_destruct.accept_when_empty_global_position_required__global_position_work()
