"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.process


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.process.Process,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        scheduler.submit(execution.on_action_parent_occupied)
        execution.accept_when_empty_action_process__position_config()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_process: local.my_domain_com.my_lib.process.ProcessExecution
        self.execution_action_process = local.my_domain_com.my_lib.process.ProcessExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.process.Process
            ),
            self.scheduler,
        )
        self.execution_action_process.join_for_empty_rule_position_input = literal.NO_JOIN
        self.execution_action_process.join_for_empty_rule_position_trigger = literal.NO_JOIN
        self.execution_action_process.join_for_destroy_position_input = literal.NO_JOIN
        self.execution_action_process.join_for_destroy_position_trigger = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_process__position_input)
        self.scheduler.submit(self.create_action_process__position_trigger)
        self.execution_action_process.on_action_parent_occupied()

    def accept_when_empty_action_process__position_config(self):
        self.execution_action_process.accept_when_empty_position_config()

    def create_action_process__position_input(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.process.Process
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        self.execution_action_process.accept_for_empty_rule_position_input()

    def create_action_process__position_trigger(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.process.Process
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.execution_action_process.accept_for_empty_rule_position_trigger()
