"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.process


class Test(literal.Action):
    is_constructor: ClassVar[bool] = True
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.process.Process,
    )

    @override
    def execute(self):
        self.on_particle.get_action(
            local.my_domain_com.my_lib.process.Process
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.process.Process
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
