"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.c
import local.my_domain_com.my_lib.d


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_a = literal.LocalPosition(
            "position<a>",
            constraints=(
                local.my_domain_com.my_lib.b.B,
            ),
            scheduler=self.scheduler,
        )

    def on_action_parent_occupied(self):
        self.create_position_a()

    def create_position_a(self):
        self.local_position_a.create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).particle.get_position(
            local.my_domain_com.my_lib.d.D
        ).create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).particle.get_position(
            local.my_domain_com.my_lib.d.D
        ).destroy_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).destroy_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).destroy_particle()
        self.local_position_a.destroy_particle()
