"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.direct_child
import local.my_domain_com.my_lib.filler
import local.my_domain_com.my_lib.guaranteed_child
import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
        local.my_domain_com.my_lib.filler.Filler,
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        literal.record_operation("test.create(/parent)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.direct_child.DirectChild
        ).create_particle()
        literal.record_operation("test.create(/parent::/direct_child)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(/filler::trigger_pos)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).run()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(/middle::trigger_pos)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).run(MiddleDestructionContracts())
        self.on_particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(/filler::trigger_pos)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(/middle::trigger_pos)")


class MiddleDestructionContracts(local.my_domain_com.my_lib.middle.MiddleDestructionContracts):

    @override
    def destroy_global_position_parent(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.guaranteed_child.GuaranteedChild
        ).destroy_particle()
        literal.record_operation("middle.destroy(/mover::destination::/guaranteed_child)")
        particle.get_position(
            local.my_domain_com.my_lib.direct_child.DirectChild
        ).destroy_particle()
        literal.record_operation("middle.destroy(/mover::destination::/direct_child)")
