"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.empty
import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.occupied


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def run(self):
        source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.occupied.Occupied,
                local.my_domain_com.my_lib.empty.Empty,
                local.my_domain_com.my_lib.destructor.Destructor,
            ),
        )
        source.create_particle()
        literal.record_operation("test.create(source)")
        source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("test.move(source, /middle::target)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        literal.record_operation("test.create(/middle::trigger)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).run()
