"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.worker


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destination.Destination,
        local.my_domain_com.my_lib.worker.Worker,
    )

    @override
    def run(self):
        source = literal.LocalPosition(
            "position<source>",
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.destination.Destination
        ).create_particle()
        literal.record_operation("test.create(/destination)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.destination.Destination
        ).destroy_particle()
        literal.record_operation("test.destroy(/destination)")
        source.create_particle()
        literal.record_operation("test.create(source)")
        source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ).get_interface_position(
                "position<source>"
            )
        )
        literal.record_operation("test.move(source, /worker::source)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).run()
