load("//tools/bzl:pyright.bzl", "pyright_test")

filegroup(
    name = "testdata_files",
    srcs = glob(["**/*"]),
    visibility = ["//define/compiler/codegen:__pkg__"],
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    srcs = glob(["**/*.py"]),
    deps = ["//define/runtime:literal"],
)
