"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.end_dest
import local.my_domain_com.my_lib.end_src_a
import local.my_domain_com.my_lib.end_src_b
import local.my_domain_com.my_lib.end_src_c
import local.my_domain_com.my_lib.mid_dest
import local.my_domain_com.my_lib.mid_src_a
import local.my_domain_com.my_lib.mid_src_b
import local.my_domain_com.my_lib.mid_src_c


class Act(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition("position<trigger>"),
                literal.InterfacePosition(
                    "position<chain_src_a>",
                    constraints=(
                        local.my_domain_com.my_lib.mid_src_a.MidSrcA,
                    ),
                ),
                literal.InterfacePosition(
                    "position<chain_src_b>",
                    constraints=(
                        local.my_domain_com.my_lib.mid_src_b.MidSrcB,
                    ),
                ),
                literal.InterfacePosition(
                    "position<chain_src_c>",
                    constraints=(
                        local.my_domain_com.my_lib.mid_src_c.MidSrcC,
                    ),
                ),
                literal.InterfacePosition("position<iface_dest>"),
                literal.InterfacePosition(
                    "position<chain_dest>",
                    constraints=(
                        local.my_domain_com.my_lib.mid_dest.MidDest,
                    ),
                ),
            ],
            trigger_position_name="position<trigger>",
        )

    @override
    def execute(self):
        local_dest = literal.LocalPosition("position<local_dest>")
        self.get_interface_position(
            "position<chain_src_a>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_src_a.MidSrcA
        ).particle.get_position(
            local.my_domain_com.my_lib.end_src_a.EndSrcA
        ).move_particle_to(local_dest)
        self.get_interface_position(
            "position<chain_src_b>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_src_b.MidSrcB
        ).particle.get_position(
            local.my_domain_com.my_lib.end_src_b.EndSrcB
        ).move_particle_to(
            self.get_interface_position(
                "position<iface_dest>"
            )
        )
        self.get_interface_position(
            "position<chain_src_c>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_src_c.MidSrcC
        ).particle.get_position(
            local.my_domain_com.my_lib.end_src_c.EndSrcC
        ).move_particle_to(
            self.get_interface_position(
                "position<chain_dest>"
            ).particle.get_position(
                local.my_domain_com.my_lib.mid_dest.MidDest
            ).particle.get_position(
                local.my_domain_com.my_lib.end_dest.EndDest
            )
        )
