"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.mover


class Destroyer(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.mover.Mover,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_run = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_action_mover: local.my_domain_com.my_lib.mover.MoverExecution
        self.destruction_position_action_mover__position_result: literal.Position
        self.join_for_move_position_run_to_action_mover__position_run: literal.Join
        self.join_for_empty_rule_position_run: literal.Join
        self.join_when_empty_action_mover__position_result: literal.Join
        self.execution_action_mover = local.my_domain_com.my_lib.mover.MoverExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.mover.Mover
            ),
            self.scheduler,
            self.trace_execution,
            "mover",
        )
        self.execution_action_mover.join_for_move_position_run_to_position_result = literal.NO_JOIN
        self.execution_action_mover.guarantees.position_run__move__position_result.inits.append(
            self.init_action_mover__position_run__move__position_result
        )
        self.execution_action_mover.guarantees.position_run__move__position_result.consumers.append(
            self.destroy_action_mover__position_result
        )

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.move_position_run_to_action_mover__position_run()

    def accept_when_empty_action_mover__position_result(self):
        if not self.join_when_empty_action_mover__position_result.arrive():
            return
        self.execution_action_mover.accept_for_empty_rule_position_run()

    def move_position_run_to_action_mover__position_run(self):
        if not self.join_for_move_position_run_to_action_mover__position_run.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.mover.Mover
            ).get_interface_position(
                "position<run>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "run",
            "/mover::run",
            1,
        )
        self.guarantees.position_run.publish(
            self.scheduler,
            self.execution_action_mover.accept_for_empty_rule_position_run,
        )

    def destroy_action_mover__position_result(self):
        literal.continue_destruction(self.continue_destroy_action_mover__position_result)

    def continue_destroy_action_mover__position_result(self):
        self.destruction_position_action_mover__position_result.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/mover::result",
            1,
        )

    def init_action_mover__position_run__move__position_result(self):
        self.destruction_position_action_mover__position_result = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<result>"
        )
