"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.construct_a
import local.my_domain_com.my_lib.construct_b


class TestAction(literal.Action):

    @override
    def run(self):
        box = literal.LocalPosition[Never](
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.construct_a.ConstructAAction,
                local.my_domain_com.my_lib.construct_b.ConstructBAction,
            ),
        )
        box.create_particle()
        box.particle.get_action(
            local.my_domain_com.my_lib.construct_a.ConstructAAction
        ).run()
        box.particle.get_action(
            local.my_domain_com.my_lib.construct_b.ConstructBAction
        ).run()
        box.destroy_particle()
