"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.construct_a
import local.my_domain_com.my_lib.construct_b


class Test(literal.Action):

    @override
    def run(self):
        box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.construct_a.ConstructA,
                local.my_domain_com.my_lib.construct_b.ConstructB,
            ),
        )
        box.create_particle()
        box.particle.get_action(
            local.my_domain_com.my_lib.construct_a.ConstructA
        ).run()
        box.particle.get_action(
            local.my_domain_com.my_lib.construct_b.ConstructB
        ).run()
        box.destroy_particle()
