"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.filler


class Test(literal.Action):

    @override
    def run(self):
        gw = literal.LocalPosition(
            "position<gw>",
            constraints=(
                local.my_domain_com.my_lib.filler.Filler,
            ),
        )
        gw.create_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<slot>"
        ).destroy_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<slot>"
        ).destroy_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<slot>"
        ).destroy_particle()
        gw.destroy_particle()
