"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.left


class ParentDestructor(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.left.Left,
    )


@final
class ParentDestructorGuarantees:
    def __init__(self, scheduler: literal.Scheduler):
        self.global_position_left = literal.Fanout(scheduler)


@final
class ParentDestructorExecution:
    def __init__(
        self,
        action: ParentDestructor,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = ParentDestructorGuarantees(self.scheduler)
        self.local_position_holder = literal.LocalPosition(
            "position<holder>",
            scheduler=self.scheduler,
        )
        self.join_for_move_global_position_left_to_position_holder: literal.Join
        self.join_for_empty_rule_global_position_left: literal.Join

    def accept_for_empty_rule_global_position_left(self):
        if not self.join_for_empty_rule_global_position_left.arrive():
            return
        self.move_global_position_left_to_position_holder()

    def move_global_position_left_to_position_holder(self):
        if not self.join_for_move_global_position_left_to_position_holder.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.left.Left
        ).move_particle_to(self.local_position_holder)
        self.scheduler.operation_completed(
            self.trace_execution,
            "move(/left, holder)",
        )
        self.local_position_holder.move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.left.Left
            )
        )
        self.scheduler.operation_completed(
            self.trace_execution,
            "move(holder, /left)",
        )
        self.guarantees.global_position_left.run()
