"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class Destructor(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<item>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestructorGuarantees:
    def __init__(self):
        self.position_item = literal.Guarantee()


@final
class DestructorExecution:
    def __init__(
        self,
        action: Destructor,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = DestructorGuarantees()
        self.local_position__holder = literal.LocalPosition(
            "position<_holder>",
            scheduler=self.scheduler,
        )
        self.join_for_move_position_item_to_position_holder: literal.Join
        self.join_for_empty_rule_position_item: literal.Join

    def accept_for_empty_rule_position_item(self):
        if not self.join_for_empty_rule_position_item.arrive():
            return
        self.move_position_item_to_position_holder()

    def move_position_item_to_position_holder(self):
        if not self.join_for_move_position_item_to_position_holder.arrive():
            return
        self.action.get_interface_position(
            "position<item>"
        ).move_particle_to(self.local_position__holder)
        self.local_position__holder.move_particle_to(
            self.action.get_interface_position(
                "position<item>"
            )
        )
        self.guarantees.position_item.publish(
            self.scheduler,
        )
