"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.marker


class MiddleDestructionContracts:
    def run_destructors_position_source__position_marker(self, _particle: literal.Particle):
        pass

    def destroy_position_source__position_marker(self, _particle: literal.Particle):
        pass

    def run_destructors_position_source(self, _particle: literal.Particle):
        pass

    def destroy_position_source(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = MiddleDestructionContracts()


class Middle(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger_pos>"),
                literal.LocalPosition(
                    "position<source>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                        local.my_domain_com.my_lib.marker.Marker,
                    ),
                ),
                literal.LocalPosition(
                    "position<holder>",
                    constraints=(
                        local.my_domain_com.my_lib.marker.Marker,
                    ),
                ),
            ],
        )

    @override
    def run(self, destruction_contracts: MiddleDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.get_interface_position(
            "position<source>"
        ).particle.get_action(
            local.my_domain_com.my_lib.child.Child
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.get_interface_position(
            "position<source>"
        ).particle.get_action(
            local.my_domain_com.my_lib.child.Child
        ).run()
        self.get_interface_position(
            "position<source>"
        ).move_particle_to(
            self.get_interface_position(
                "position<holder>"
            )
        )
        destruction_contracts.run_destructors_position_source__position_marker(
            self.get_interface_position(
                "position<holder>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker.Marker
            ).particle
        )
        destruction_contracts.destroy_position_source__position_marker(
            self.get_interface_position(
                "position<holder>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker.Marker
            ).particle
        )
        self.get_interface_position(
            "position<holder>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).destroy_particle()
        destruction_contracts.run_destructors_position_source(
            self.get_interface_position(
                "position<holder>"
            ).particle
        )
        destruction_contracts.destroy_position_source(
            self.get_interface_position(
                "position<holder>"
            ).particle
        )
        self.get_interface_position(
            "position<holder>"
        ).destroy_particle()
