"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.inner_result


class InnerAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.inner_result.InnerResultPosition,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<trigger_pos>"),
            ],
        )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.inner_result.InnerResultPosition
        ).create_particle()
        literal.record_operation("inner.create(/inner_result)")
