"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent


class TestAction(literal.Action):

    @override
    def run(self):
        local_ = literal.LocalPosition[Never](
            "position<local>",
            constraints=(
                local.my_domain_com.my_lib.parent.ParentPosition,
            ),
        )
        local_.create_particle()
        local_.particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).create_particle()
        local_.particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.middle.MiddleAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        local_.particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.middle.MiddleAction
        ).run()
        local_.particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.middle.MiddleAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        local_.particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).destroy_particle()
        local_.destroy_particle()
