"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.parent


class Inner(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/inner>"

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition("position<run>"),
                literal.InterfacePosition(
                    "position<input>",
                    constraints=(
                        local.my_domain_com.my_lib.parent.Parent,
                    ),
                ),
            ],
            trigger_position_name="position<run>",
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<input>"
        ).particle.get_position(
            "position<my.domain.com:my_lib:/parent>"
        ).particle.get_position(
            "position<my.domain.com:my_lib:/a>"
        ).create_particle()
        self.get_interface_position(
            "position<input>"
        ).particle.get_position(
            "position<my.domain.com:my_lib:/parent>"
        ).particle.get_position(
            "position<my.domain.com:my_lib:/b>"
        ).create_particle()
