load("@aspect_rules_py//py:defs.bzl", "py_library")

filegroup(
    name = "testdata_files",
    srcs = glob(["**/*"]) + [
        "//defcl/testdata/invalid:invalid_files",
        "//defcl/testdata/valid:valid_files",
    ],
    visibility = ["//defcl/python:__subpackages__"],
)

py_library(
    name = "testdata",
    srcs = ["__init__.py"],
    visibility = ["//defcl/testdata:__subpackages__"],
    deps = ["//defcl"],
)
