load("@aspect_rules_lint//format:defs.bzl", "format_test")
load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "testdata",
    srcs = ["__init__.py"],
    visibility = ["//defcl/testdata:__subpackages__"],
    deps = ["//defcl"],
)

filegroup(
    name = "testdata_files",
    srcs = glob(["**/*"]) + [
        "//defcl/testdata/invalid:invalid_files",
        "//defcl/testdata/valid:valid_files",
    ],
    visibility = ["//defcl/python:__subpackages__"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@aspect_rules_lint//format:ruff",
)
