load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("//tools/lint:format.bzl", "format_test")

proto_library(
    name = "boolean_proto",
    srcs = ["boolean.proto"],
)

go_proto_library(
    name = "boolean_go_proto",
    importpath = "defcl/schema/core",
    proto = ":boolean_proto",
)

go_library(
    name = "core",
    embed = [":boolean_go_proto"],
    importpath = "defcl/schema/core",
)

py_library(
    name = "core_py",
    srcs = ["__init__.py"],
    deps = ["//defcl/schema"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@aspect_rules_lint//format:ruff",
)
