"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.marker


class Runner(literal.Action):
    _typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/runner>"
    implied_qualities: ClassVar[tuple[literal.Constraint, ...]] = (
        local.my_domain_com.my_lib.marker.Marker,
    )

    def __init__(self):
        super().__init__(
            interface_positions=[
                literal.InterfacePosition("position<run>"),
            ],
            trigger_position_name="position<run>",
        )

    @override
    def execute(self):
        self.create_dimension_point()
