"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.inner_destroyer
import local.my_domain_com.my_lib.inner_destructor


class OuterDestructor(literal.Action):

    @override
    def run(self):
        inner_destroyer_particle = literal.LocalPosition(
            "position<inner_destroyer_particle>",
            constraints=(
                local.my_domain_com.my_lib.inner_destroyer.InnerDestroyer,
            ),
        )
        inner_source = literal.LocalPosition(
            "position<inner_source>",
            constraints=(
                local.my_domain_com.my_lib.inner_destructor.InnerDestructor,
            ),
        )
        inner_destroyer_particle.create_particle()
        literal.record_operation("outer_destructor.create(inner_destroyer_particle)")
        inner_source.create_particle()
        literal.record_operation("outer_destructor.create(inner_source)")
        inner_source.move_particle_to(
            inner_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.inner_destroyer.InnerDestroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("outer_destructor.move(inner_source, inner_destroyer_particle::/inner_destroyer::target)")
        inner_destroyer_particle.particle.get_action(
            local.my_domain_com.my_lib.inner_destroyer.InnerDestroyer
        ).run()
        inner_destroyer_particle.destroy_particle()
        literal.record_operation("outer_destructor.destroy(inner_destroyer_particle)")
