"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.carrier
import local.my_domain_com.my_lib.outer


class Wrapper(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.outer.Outer,
                        local.my_domain_com.my_lib.carrier.Carrier,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class WrapperGuarantees:
    def __init__(self):
        self.position_run = literal.Guarantee()


@final
class WrapperExecution:
    def __init__(
        self,
        action: Wrapper,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = WrapperGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_position_run__action_outer: local.my_domain_com.my_lib.outer.OuterExecution
        self.join_for_move_position_run__global_position_carrier_to_position_run__action_outer__position_run: literal.Join
        self.join_for_destroy_position_run: literal.Join
        self.join_for_empty_rule_position_run__global_position_carrier: literal.Join
        self.join_for_empty_rule_position_run: literal.Join

    def accept_for_empty_rule_position_run__global_position_carrier(self):
        if not self.join_for_empty_rule_position_run__global_position_carrier.arrive():
            return
        self.move_position_run__global_position_carrier_to_position_run__action_outer__position_run()

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.destroy_position_run()

    def init_position_run__action_outer(self):
        self.execution_position_run__action_outer = local.my_domain_com.my_lib.outer.OuterExecution(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ),
            self.scheduler,
            destruction_connections=self.destruction_connections,
        )
        self.execution_position_run__action_outer.join_for_empty_rule_position_run__global_position_payload = literal.NO_JOIN
        self.execution_position_run__action_outer.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_position_run__action_outer.join_for_move_position_run__global_position_payload_to_position_run__action_middle__position_run = literal.NO_JOIN
        self.execution_position_run__action_outer.join_for_destroy_position_run = literal.NO_JOIN
        self.execution_position_run__action_outer.guarantees.position_run.consumers.append(
            self.destroy_position_run
        )

    def move_position_run__global_position_carrier_to_position_run__action_outer__position_run(self):
        if not self.join_for_move_position_run__global_position_carrier_to_position_run__action_outer__position_run.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.carrier.Carrier
        ).move_particle_to(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.execution_position_run__action_outer.init_when_occupied_position_run()
        self.scheduler.submit(self.execution_position_run__action_outer.accept_for_empty_rule_position_run__global_position_payload)
        self.execution_position_run__action_outer.continue_when_occupied_position_run()

    def destroy_position_run(self):
        if not self.join_for_destroy_position_run.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_run)

    def continue_destroy_position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.guarantees.position_run.publish(
            self.scheduler,
        )
