"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.helper
import local.my_domain_com.my_lib.out


class Mover(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destination.Destination,
        local.my_domain_com.my_lib.out.Out,
        local.my_domain_com.my_lib.helper.Helper,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MoverGuarantees:
    def __init__(self):
        self.guarantee_global_position_out__move__global_position_destination: list[literal.Task] = []
        self.guarantee_action_helper__position_trigger_pos: list[literal.Task] = []
        self.trigger_action_helper = local.my_domain_com.my_lib.helper.HelperGuarantees()


@final
class MoverExecution:
    def __init__(
        self,
        action: Mover,
        scheduler: literal.Scheduler,
        guarantees: MoverGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        guarantees.trigger_action_helper.guarantee_global_position_slot__move__global_position_out.append(
            self.move_global_position_out_to_global_position_destination
        )
        self.execution_trigger_action_helper: local.my_domain_com.my_lib.helper.HelperExecution
        self.join_for_move_global_position_out_to_global_position_destination = literal.Join(2)
        self.join_for_trigger_action_helper__for_empty_rule_global_position_slot = literal.Join(2)

    def accept_when_empty_action_helper__position_trigger_pos(self):
        self.create_action_helper__position_trigger_pos()

    def accept_for_empty_rule_global_position_slot(self):
        self.trigger_action_helper__for_empty_rule_global_position_slot()

    def accept_when_empty_global_position_destination(self):
        self.move_global_position_out_to_global_position_destination()

    def create_action_helper__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.helper.Helper
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.execution_trigger_action_helper = local.my_domain_com.my_lib.helper.HelperExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.helper.Helper
            ),
            self.scheduler,
            self.guarantees.trigger_action_helper,
        )
        self.scheduler.submit_all(self.guarantees.guarantee_action_helper__position_trigger_pos)
        self.trigger_action_helper__for_empty_rule_global_position_slot()

    def move_global_position_out_to_global_position_destination(self):
        if not self.join_for_move_global_position_out_to_global_position_destination.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.out.Out
        ).move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.destination.Destination
            )
        )
        self.scheduler.continue_with(self.guarantees.guarantee_global_position_out__move__global_position_destination)

    def trigger_action_helper__for_empty_rule_global_position_slot(self):
        if not self.join_for_trigger_action_helper__for_empty_rule_global_position_slot.arrive():
            return
        self.execution_trigger_action_helper.accept_for_empty_rule_global_position_slot()
