"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.right_child


class Right(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.right_child.RightChild,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class RightGuarantees:
    def __init__(self):
        self.guarantee_global_action_right_child__position_trigger_pos: list[literal.Task] = []
        self.trigger_global_action_right_child = local.my_domain_com.my_lib.right_child.RightChildGuarantees()


@final
class RightExecution:
    def __init__(
        self,
        action: Right,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: RightGuarantees,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.destruction_connections = destruction_connections
        self.trigger_global_action_right_child__execution: local.my_domain_com.my_lib.right_child.RightChildExecution
        self.join_for_trigger_global_action_right_child__for_empty_rule_global_position_marker = literal.Join(2)
        self.join_for_trigger_global_action_right_child__when_occupied_global_position_marker = literal.Join(2)

    def accept_when_empty_global_action_right_child__position_trigger_pos(self):
        self.create_global_action_right_child__position_trigger_pos()

    def accept_for_empty_rule_global_position_marker(self):
        self.trigger_global_action_right_child__for_empty_rule_global_position_marker()

    def accept_when_occupied_global_position_marker(self):
        self.trigger_global_action_right_child__when_occupied_global_position_marker()

    def create_global_action_right_child__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.right_child.RightChild
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/right_child::trigger_pos",
            1,
        )
        self.init_trigger_global_action_right_child__execution()
        self.scheduler.submit_all(self.guarantees.guarantee_global_action_right_child__position_trigger_pos)
        self.scheduler.submit(self.trigger_global_action_right_child__for_empty_rule_global_position_marker)
        self.trigger_global_action_right_child__when_occupied_global_position_marker()

    def init_trigger_global_action_right_child__execution(self):
        action = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.right_child.RightChild
        )
        self.trigger_global_action_right_child__execution = local.my_domain_com.my_lib.right_child.RightChildExecution(
            action,
            self.scheduler,
            self.trace_execution,
            "right_child",
            self.guarantees.trigger_global_action_right_child,
            destruction_connections=self.destruction_connections,
        )

    def trigger_global_action_right_child__for_empty_rule_global_position_marker(self):
        if not self.join_for_trigger_global_action_right_child__for_empty_rule_global_position_marker.arrive():
            return
        self.trigger_global_action_right_child__execution.accept_for_empty_rule_global_position_marker()

    def trigger_global_action_right_child__when_occupied_global_position_marker(self):
        if not self.join_for_trigger_global_action_right_child__when_occupied_global_position_marker.arrive():
            return
        self.trigger_global_action_right_child__execution.accept_when_occupied_global_position_marker()
