"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child_destructor
import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.extra
import local.my_domain_com.my_lib.left
import local.my_domain_com.my_lib.parent_destructor
import local.my_domain_com.my_lib.right


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def run(self):
        source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.left.Left,
                local.my_domain_com.my_lib.right.Right,
                local.my_domain_com.my_lib.parent_destructor.ParentDestructor,
            ),
        )
        left_source = literal.LocalPosition(
            "position<left_source>",
            constraints=(
                local.my_domain_com.my_lib.extra.Extra,
            ),
        )
        right_source = literal.LocalPosition(
            "position<right_source>",
            constraints=(
                local.my_domain_com.my_lib.child_destructor.ChildDestructor,
            ),
        )
        source.create_particle()
        literal.record_operation("test.create(source)")
        left_source.create_particle()
        literal.record_operation("test.create(left_source)")
        left_source.particle.get_position(
            local.my_domain_com.my_lib.extra.Extra
        ).create_particle()
        literal.record_operation("test.create(left_source::/extra)")
        left_source.move_particle_to(
            source.particle.get_position(
                local.my_domain_com.my_lib.left.Left
            )
        )
        literal.record_operation("test.move(left_source, source::/left)")
        right_source.create_particle()
        literal.record_operation("test.create(right_source)")
        right_source.move_particle_to(
            source.particle.get_position(
                local.my_domain_com.my_lib.right.Right
            )
        )
        literal.record_operation("test.move(right_source, source::/right)")
        source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("test.move(source, /destroyer::target)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).run()
