"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal


class HeatAction(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<cold_water>"),
                literal.LocalPosition[Never]("position<hot_water>"),
            ],
        )

    @override
    def run(self):
        self.get_interface_position(
            "position<cold_water>"
        ).move_particle_to(
            self.get_interface_position(
                "position<hot_water>"
            )
        )
        literal.record_operation("heat.move(cold_water, hot_water)")
