"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.third


class ThirdDestructorAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.third.ThirdPosition,
    )

    @override
    def run(self):
        holder = literal.LocalPosition[Never](
            "position<holder>",
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.third.ThirdPosition
        ).move_particle_to(
            holder
        )
        literal.record_operation("third_destructor.move(/third, holder)")
        holder.move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.third.ThirdPosition
            )
        )
        literal.record_operation("third_destructor.move(holder, /third)")
        marker = literal.LocalPosition[Never](
            "position<marker>",
        )
        marker.create_particle()
        literal.record_operation("third_destructor.create(marker)")
        marker.destroy_particle()
        literal.record_operation("third_destructor.destroy(marker)")
