"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.input


class InnerDestructionContracts:
    def run_destructors_global_position_input(self, _particle: literal.Particle):
        pass

    def destroy_global_position_input(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = InnerDestructionContracts()


class Inner(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.input.Input,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger_pos>"),
                literal.LocalPosition("position<holder>"),
            ],
        )

    @override
    def run(self, destruction_contracts: InnerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).move_particle_to(
            self.get_interface_position(
                "position<holder>"
            )
        )
        destruction_contracts.run_destructors_global_position_input(
            self.get_interface_position(
                "position<holder>"
            ).particle
        )
        destruction_contracts.destroy_global_position_input(
            self.get_interface_position(
                "position<holder>"
            ).particle
        )
        self.get_interface_position(
            "position<holder>"
        ).destroy_particle()
