"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.child_2_0
import local.my_domain_com.my_lib.child_2_1
import local.my_domain_com.my_lib.done
import local.my_domain_com.my_lib.fill_3
import local.my_domain_com.my_lib.item
import local.my_domain_com.my_lib.kept
import local.my_domain_com.my_lib.stamp


class Fill2DestructionContracts:
    def run_destructors_position_run(self, _particle: literal.Particle):
        pass

    def destroy_position_run(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = Fill2DestructionContracts()


class Fill2Action(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.child_2_0.Child20Position,
        local.my_domain_com.my_lib.child_2_1.Child21Position,
        local.my_domain_com.my_lib.item.ItemPosition,
        local.my_domain_com.my_lib.kept.KeptPosition,
        local.my_domain_com.my_lib.stamp.StampAction,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<run>"),
            ],
        )

    @override
    def run(self, destruction_contracts: Fill2DestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        destruction_contracts.run_destructors_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        destruction_contracts.destroy_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        self.get_interface_position(
            "position<run>"
        ).destroy_particle()
        literal.record_operation("fill_2.destroy(run)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.item.ItemPosition
        ).move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.kept.KeptPosition
            )
        )
        literal.record_operation("fill_2.move(/item, /kept)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.stamp.StampAction
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        literal.record_operation("fill_2.create(/stamp::run)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.stamp.StampAction
        ).run()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_0.Child20Position
        ).create_particle()
        literal.record_operation("fill_2.create(/child_2_0)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_0.Child20Position
        ).particle.get_position(
            local.my_domain_com.my_lib.item.ItemPosition
        ).create_particle()
        literal.record_operation("fill_2.create(/child_2_0::/item)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_0.Child20Position
        ).particle.get_action(
            local.my_domain_com.my_lib.fill_3.Fill3Action
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        literal.record_operation("fill_2.create(/child_2_0::/fill_3::run)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_0.Child20Position
        ).particle.get_action(
            local.my_domain_com.my_lib.fill_3.Fill3Action
        ).run()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_0.Child20Position
        ).particle.get_position(
            local.my_domain_com.my_lib.kept.KeptPosition
        ).move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.child_2_0.Child20Position
            ).particle.get_position(
                local.my_domain_com.my_lib.done.DonePosition
            )
        )
        literal.record_operation("fill_2.move(/child_2_0::/kept, /child_2_0::/done)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_1.Child21Position
        ).create_particle()
        literal.record_operation("fill_2.create(/child_2_1)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_1.Child21Position
        ).particle.get_position(
            local.my_domain_com.my_lib.item.ItemPosition
        ).create_particle()
        literal.record_operation("fill_2.create(/child_2_1::/item)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_1.Child21Position
        ).particle.get_action(
            local.my_domain_com.my_lib.fill_3.Fill3Action
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        literal.record_operation("fill_2.create(/child_2_1::/fill_3::run)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_1.Child21Position
        ).particle.get_action(
            local.my_domain_com.my_lib.fill_3.Fill3Action
        ).run()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.child_2_1.Child21Position
        ).particle.get_position(
            local.my_domain_com.my_lib.kept.KeptPosition
        ).move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.child_2_1.Child21Position
            ).particle.get_position(
                local.my_domain_com.my_lib.done.DonePosition
            )
        )
        literal.record_operation("fill_2.move(/child_2_1::/kept, /child_2_1::/done)")
