"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal


class ParentDestructAction(literal.Action):

    @override
    def run(self):
        _noop = literal.LocalPosition[Never](
            "position<_noop>",
        )
        _noop.create_particle()
        literal.record_operation("parent_destruct.create(_noop)")
        _noop.destroy_particle()
        literal.record_operation("parent_destruct.destroy(_noop)")
