"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.marker
import local.my_domain_com.my_lib.second


class SecondDestructor(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.second.Second,
        local.my_domain_com.my_lib.marker.Marker,
    )

    @override
    def run(self):
        holder = literal.LocalPosition(
            "position<holder>",
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.second.Second
        ).move_particle_to(
            holder
        )
        literal.record_operation("second_destructor.move(/second, holder)")
        holder.move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.second.Second
            )
        )
        literal.record_operation("second_destructor.move(holder, /second)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        literal.record_operation("second_destructor.create(/marker)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).destroy_particle()
        literal.record_operation("second_destructor.destroy(/marker)")
