"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.first_child
import local.my_domain_com.my_lib.second_child
import local.my_domain_com.my_lib.worker


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.worker.WorkerAction,
    )

    @override
    def run(self):
        first_source = literal.LocalPosition[Never](
            "position<first_source>",
            constraints=(
                local.my_domain_com.my_lib.first_child.FirstChildPosition,
            ),
        )
        second_source = literal.LocalPosition[Never](
            "position<second_source>",
            constraints=(
                local.my_domain_com.my_lib.second_child.SecondChildPosition,
            ),
        )
        first_source.create_particle()
        first_source.particle.get_position(
            local.my_domain_com.my_lib.first_child.FirstChildPosition
        ).create_particle()
        second_source.create_particle()
        second_source.particle.get_position(
            local.my_domain_com.my_lib.second_child.SecondChildPosition
        ).create_particle()
        first_source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.worker.WorkerAction
            ).get_interface_position(
                "position<input>"
            )
        )
        second_source.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.worker.WorkerAction
            ).get_interface_position(
                "position<reserve>"
            )
        )
        self.on_particle.get_action(
            local.my_domain_com.my_lib.worker.WorkerAction
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.worker.WorkerAction
        ).run(WorkerDestructionContracts())
        self.on_particle.get_action(
            local.my_domain_com.my_lib.worker.WorkerAction
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()


class WorkerDestructionContracts(local.my_domain_com.my_lib.worker.WorkerDestructionContracts):

    @override
    def destroy_position_input(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.first_child.FirstChildPosition
        ).destroy_particle()

    @override
    def destroy_position_reserve(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.second_child.SecondChildPosition
        ).destroy_particle()
