"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.known_destructor
import local.my_domain_com.my_lib.target


class DestroyerDestructionContracts:
    def run_destructors_global_position_target(self, _particle: literal.Particle):
        pass

    def destroy_global_position_target(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = DestroyerDestructionContracts()


class DestroyerAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.target.TargetPosition,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<trigger_pos>"),
            ],
        )

    @override
    def run(self, destruction_contracts: DestroyerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.target.TargetPosition
        ).particle.get_action(
            local.my_domain_com.my_lib.known_destructor.KnownDestructorAction
        ).run()
        destruction_contracts.run_destructors_global_position_target(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.target.TargetPosition
            ).particle
        )
        destruction_contracts.destroy_global_position_target(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.target.TargetPosition
            ).particle
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.target.TargetPosition
        ).destroy_particle()
