"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.extra_destructor
import local.my_domain_com.my_lib.known_destructor
import local.my_domain_com.my_lib.outer


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.outer.Outer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        execution.execution_action_outer.execution_action_middle.execution_action_inner.execution_action_filler.join_for_empty_rule_position_run = scheduler.create_join(2)
        execution.execution_action_outer.execution_action_middle.execution_action_inner.join_when_empty_global_position_target = literal.NO_JOIN
        execution.execution_action_outer.execution_action_middle.join_when_empty_global_position_target = literal.NO_JOIN
        execution.execution_action_outer.join_when_empty_global_position_target = literal.NO_JOIN
        execution.join_when_empty_global_position_target = literal.NO_JOIN
        scheduler.submit(execution.on_action_parent_occupied)
        execution.accept_when_empty_global_position_target()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.extra_destructor.ExtraDestructor,
                local.my_domain_com.my_lib.known_destructor.KnownDestructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_outer: local.my_domain_com.my_lib.outer.OuterExecution
        self.join_when_empty_global_position_target: literal.Join
        self.execution_action_outer = local.my_domain_com.my_lib.outer.OuterExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ),
            self.scheduler,
            self.trace_execution,
            "outer",
        )
        self.execution_action_outer.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_action_outer.join_for_move_position_run_to_action_middle__position_run = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_source)
        self.execution_action_outer.on_action_parent_occupied()

    def accept_when_empty_global_position_target(self):
        if not self.join_when_empty_global_position_target.arrive():
            return
        self.execution_action_outer.accept_when_empty_global_position_target()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "source",
            1,
        )
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "source",
            "/outer::run",
            1,
        )
        self.execution_action_outer.accept_for_empty_rule_position_run()
