"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.inner


class Act(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    constraints=(
                        local.my_domain_com.my_lib.inner.Inner,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class ActGuarantees:
    def __init__(self):
        self.guarantee_position_trigger_pos__global_position_inner: list[literal.Task] = []


@final
class ActExecution:
    def __init__(
        self,
        action: Act,
        scheduler: literal.Scheduler,
        guarantees: ActGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_result = literal.LocalPosition(
            "position<result>",
            scheduler=self.scheduler,
        )

    def accept_action_parent(self):
        self.create_position_result()

    def accept_when_empty_position_trigger_pos__global_position_inner(self):
        self.create_position_trigger_pos__global_position_inner()

    def create_position_result(self):
        self.local_position_result.create_particle()
        self.local_position_result.destroy_particle()

    def create_position_trigger_pos__global_position_inner(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).particle.get_position(
            local.my_domain_com.my_lib.inner.Inner
        ).create_particle()
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).particle.get_position(
            local.my_domain_com.my_lib.inner.Inner
        ).destroy_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_trigger_pos__global_position_inner)
