"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            TestGuarantees(),
        )
        execution.create_position_gateway()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.other.Other,
            ),
            scheduler=self.scheduler,
        )
        guarantees.trigger_position_gateway__action_other.guarantee_position_box__global_position_item__move__position_box__global_position_destination.append(
            self.destroy_position_gateway__action_other__position_box__global_position_destination
        )
        self.execution_trigger_position_gateway__action_other: local.my_domain_com.my_lib.other.OtherExecution
        self.join_for_destroy_position_gateway = self.scheduler.create_join(2)
        self.join_for_trigger_position_gateway__action_other__when_empty_position_box__global_position_item = self.scheduler.create_join(2)

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.scheduler.submit(self.create_position_gateway__action_other__position_box)
        self.create_position_gateway__action_other__position_trigger_pos()

    def create_position_gateway__action_other__position_box(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<box>"
        ).create_particle()
        self.trigger_position_gateway__action_other__when_empty_position_box__global_position_item()

    def create_position_gateway__action_other__position_trigger_pos(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.execution_trigger_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ),
            self.scheduler,
            self.guarantees.trigger_position_gateway__action_other,
        )
        self.scheduler.submit(self.destroy_position_gateway__action_other__position_trigger_pos)
        self.scheduler.submit(self.trigger_position_gateway__action_other__when_empty_position_box__global_position_item)
        self.trigger_position_gateway__action_other__when_empty_position_box__global_position_destination()

    def destroy_position_gateway__action_other__position_box__global_position_destination(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.destination.Destination
        ).destroy_particle()
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<box>"
        ).destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway__action_other__position_trigger_pos(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        self.local_position_gateway.destroy_particle()

    def trigger_position_gateway__action_other__when_empty_position_box__global_position_item(self):
        if not self.join_for_trigger_position_gateway__action_other__when_empty_position_box__global_position_item.arrive():
            return
        self.execution_trigger_position_gateway__action_other.accept_when_empty_position_box__global_position_item()

    def trigger_position_gateway__action_other__when_empty_position_box__global_position_destination(self):
        self.execution_trigger_position_gateway__action_other.accept_when_empty_position_box__global_position_destination()
