"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.maker


class Test(literal.Action):

    @override
    def run(self):
        box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.maker.Maker,
            ),
        )
        box.create_particle()
        box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).run()
        box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<result>"
        ).particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).run()
        box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<result>"
        ).destroy_particle()
        box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()
        box.destroy_particle()
