"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal


class TestAction(literal.Action):

    @override
    def run(self):
        self_ = literal.LocalPosition[Never](
            "position<self_>",
        )
        self__ = literal.LocalPosition[Never](
            "position<self__>",
        )
        self___ = literal.LocalPosition[Never](
            "position<self>",
        )
        self_.create_particle()
        self__.create_particle()
        self___.create_particle()
        self_.destroy_particle()
        self__.destroy_particle()
        self___.destroy_particle()
