"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal


class Inner(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/inner>"

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition("position<trigger_pos>"),
            ],
            trigger_position_name="position<trigger_pos>",
        )

    @override
    def execute(self):
        scratch = literal.LocalPosition("position<scratch>")
        scratch.create_particle()
