"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.implied


class Triggered(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.implied.Implied,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class TriggeredGuarantees:
    def __init__(self):
        self.position_run__move__global_position_implied = literal.Guarantee()


@final
class TriggeredExecution:
    def __init__(
        self,
        action: Triggered,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = TriggeredGuarantees()
        self.join_for_move_position_run_to_global_position_implied: literal.Join
        self.join_for_empty_rule_position_run: literal.Join

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.move_position_run_to_global_position_implied()

    def move_position_run_to_global_position_implied(self):
        if not self.join_for_move_position_run_to_global_position_implied.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.implied.Implied
            )
        )
        self.guarantees.position_run__move__global_position_implied.publish(
            self.scheduler,
        )
