"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.deep
import local.my_domain_com.my_lib.item
import local.my_domain_com.my_lib.other


class Test(literal.Action):
    is_constructor: ClassVar[bool] = True

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition(
                    "position<gateway>",
                    constraints=(
                        local.my_domain_com.my_lib.other.Other,
                    ),
                ),
            ],
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<gateway>"
        ).create_particle()
        self.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        self.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).create_particle()
        self.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).particle.get_position(
            local.my_domain_com.my_lib.deep.Deep
        ).create_particle()
        self.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
