"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b


class Other(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<box>",
                    constraints=(
                        local.my_domain_com.my_lib.a.A,
                        local.my_domain_com.my_lib.b.B,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<keeper>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class OtherGuarantees:
    def __init__(self):
        self.guarantee_position_box__global_position_a__move__position_keeper: list[literal.Task] = []
        self.guarantee_position_box__global_position_b: list[literal.Task] = []


@final
class OtherExecution:
    def __init__(
        self,
        action: Other,
        scheduler: literal.Scheduler,
        guarantees: OtherGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees

    def accept_when_empty_position_box__global_position_b(self):
        self.create_position_box__global_position_b()

    def accept_for_empty_rule_position_box__global_position_a(self):
        self.move_position_box__global_position_a_to_position_keeper()

    def create_position_box__global_position_b(self):
        self.action.get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_box__global_position_b)

    def move_position_box__global_position_a_to_position_keeper(self):
        self.action.get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).move_particle_to(
            self.action.get_interface_position(
                "position<keeper>"
            )
        )
        self.scheduler.continue_with(self.guarantees.guarantee_position_box__global_position_a__move__position_keeper)
