"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.inner_destructor
import local.my_domain_com.my_lib.nested_worker
import local.my_domain_com.my_lib.worker


class Destructor(literal.Action):

    @override
    def run(self):
        worker = literal.LocalPosition(
            "position<worker>",
            constraints=(
                local.my_domain_com.my_lib.worker.Worker,
                local.my_domain_com.my_lib.nested_worker.NestedWorker,
            ),
        )
        source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
        )
        contributor = literal.LocalPosition(
            "position<contributor>",
            constraints=(
                local.my_domain_com.my_lib.inner_destructor.InnerDestructor,
            ),
        )
        worker.create_particle()
        literal.record_operation("destructor.create(worker)")
        source.create_particle()
        literal.record_operation("destructor.create(source)")
        source.move_particle_to(
            worker.particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("destructor.move(source, worker::/worker::target)")
        worker.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).run()
        source.create_particle()
        literal.record_operation("destructor.create(source)")
        source.move_particle_to(
            worker.particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("destructor.move(source, worker::/worker::target)")
        worker.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).run()
        contributor.create_particle()
        literal.record_operation("destructor.create(contributor)")
        contributor.move_particle_to(
            worker.particle.get_action(
                local.my_domain_com.my_lib.nested_worker.NestedWorker
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("destructor.move(contributor, worker::/nested_worker::target)")
        worker.particle.get_action(
            local.my_domain_com.my_lib.nested_worker.NestedWorker
        ).run(NestedWorkerDestructionContracts())
        contributor.create_particle()
        literal.record_operation("destructor.create(contributor)")
        contributor.move_particle_to(
            worker.particle.get_action(
                local.my_domain_com.my_lib.nested_worker.NestedWorker
            ).get_interface_position(
                "position<target>"
            )
        )
        literal.record_operation("destructor.move(contributor, worker::/nested_worker::target)")
        worker.particle.get_action(
            local.my_domain_com.my_lib.nested_worker.NestedWorker
        ).run(NestedWorkerDestructionContracts_2())
        worker.destroy_particle()
        literal.record_operation("destructor.destroy(worker)")


class NestedWorkerDestructionContracts(local.my_domain_com.my_lib.nested_worker.NestedWorkerDestructionContracts):

    @override
    def run_destructors_position_target(self, particle: literal.Particle):
        particle.get_action(
            local.my_domain_com.my_lib.inner_destructor.InnerDestructor
        ).run()


class NestedWorkerDestructionContracts_2(local.my_domain_com.my_lib.nested_worker.NestedWorkerDestructionContracts):

    @override
    def run_destructors_position_target(self, particle: literal.Particle):
        particle.get_action(
            local.my_domain_com.my_lib.inner_destructor.InnerDestructor
        ).run()
