"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.a


class Inner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<holder>",
                    constraints=(
                        local.my_domain_com.my_lib.a.A,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class InnerGuarantees:
    def __init__(self):
        self.position_holder__global_position_a = literal.Guarantee()


@final
class InnerExecution:
    def __init__(
        self,
        action: Inner,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = InnerGuarantees()

    def accept_when_empty_position_holder__global_position_a(self):
        self.create_position_holder__global_position_a()

    def create_position_holder__global_position_a(self):
        self.action.get_interface_position(
            "position<holder>"
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.guarantees.position_holder__global_position_a.publish(
            self.scheduler,
        )
