"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.parent_destructor


class Test(literal.GlobalPosition):
    typed_name: ClassVar[str] = "position<my.domain.com:my_lib:/test>"

    @override
    def after_assigned(self):
        box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.parent_destructor.ParentDestructor,
                local.my_domain_com.my_lib.child.Child,
            ),
        )
        box.create_particle()
        box.particle.get_position(
            "position<my.domain.com:my_lib:/child>"
        ).create_particle()
        box.destroy_particle()
