"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import standard.number.rational


class AssignDestructionContracts:
    def run_destructors_position_trigger(self, _particle: literal.Particle):
        pass

    def destroy_position_trigger(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = AssignDestructionContracts()


class Assign(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger>"),
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        standard.number.rational.NumberRational,
                    ),
                ),
                literal.LocalPosition(
                    "position<source>",
                    constraints=(
                        standard.number.rational.NumberRational,
                    ),
                ),
            ],
        )

    @override
    def run(self, destruction_contracts: AssignDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        self.get_interface_position(
            "position<target>"
        ).set_value_from(
            self.get_interface_position(
                "position<source>"
            )
        )
        literal.record_operation("assign.set_value(target, source)")
        destruction_contracts.run_destructors_position_trigger(
            self.get_interface_position(
                "position<trigger>"
            ).particle
        )
        destruction_contracts.destroy_position_trigger(
            self.get_interface_position(
                "position<trigger>"
            ).particle
        )
        self.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
        literal.record_operation("assign.destroy(trigger)")
