"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.work


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.work.WorkAction,
    )

    @override
    def run(self):
        self.on_particle.get_action(
            local.my_domain_com.my_lib.work.WorkAction
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        literal.record_operation("test.create(/work::run)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.work.WorkAction
        ).run()
