load("@aspect_rules_py//py:defs.bzl", "py_library", "py_test")

exports_files(["pyproject.toml"])

# --- Libraries ---

py_library(
    name = "init",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "ast",
    srcs = ["ast.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":init",
        "@pypi//lark",
    ],
)

py_library(
    name = "parser",
    srcs = ["parser.py"],
    data = ["grammar.lark"],
    visibility = ["//visibility:public"],
    deps = [
        ":init",
        "@pypi//lark",
    ],
)

py_library(
    name = "transformer",
    srcs = ["transformer.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":ast",
        "@pypi//lark",
    ],
)

py_library(
    name = "validator",
    srcs = ["validator.py"],
    data = ["//spec:reserved_words"],
    visibility = ["//visibility:public"],
    deps = [":ast"],
)

# --- Tests ---

py_test(
    name = "parser_test",
    srcs = ["parser_test.py"],
    pytest_main = True,
    deps = [
        ":parser",
        "@pypi//lark",
        "@pypi//pytest",
    ],
)

py_test(
    name = "transformer_test",
    srcs = ["transformer_test.py"],
    pytest_main = True,
    deps = [
        ":parser",
        ":transformer",
        "@pypi//pytest",
    ],
)

py_test(
    name = "validator_test",
    srcs = ["validator_test.py"],
    pytest_main = True,
    deps = [
        ":parser",
        ":transformer",
        ":validator",
        "@pypi//pytest",
    ],
)
