"""Generated by the Define compiler."""

from typing import ClassVar, Never

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.producer


class BoxPosition(literal.GlobalPosition[Never]):
    constraints: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.producer.ProducerAction,
        local.my_domain_com.my_lib.destination.DestinationPosition,
    )
