load("//tools/bzl:pyright.bzl", "pyright_test")

_TRACING_TESTDATA_EXCLUDES = [
    "**/expected_trace/**",
    "**/operation_trace.txt",
]

filegroup(
    name = "codegen_testdata",
    testonly = True,
    srcs = glob(
        ["**"],
        exclude = _TRACING_TESTDATA_EXCLUDES,
    ),
    visibility = ["//define/testdata/codegen:__pkg__"],
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    srcs = glob(["**/*.py"]),
    deps = [
        "//define/runtime:literal",
    ],
)
