load("//tools/bzl:pyright.bzl", "pyright_test")

filegroup(
    name = "codegen_testdata",
    testonly = True,
    srcs = glob(
        ["**"],
        exclude = [
            "**/expected_trace/**",
            "**/operation_trace.txt",
        ],
    ),
    visibility = ["//define/testdata/codegen:__pkg__"],
)

filegroup(
    name = "tracing_testdata",
    testonly = True,
    srcs = glob(
        ["**"],
        exclude = [
            "**/expected/**",
        ],
    ),
    visibility = ["//define/testdata/codegen:__pkg__"],
)

pyright_test(
    name = "pyright_test",
    srcs = glob(["**/*.py"]),
    deps = ["//define/runtime:literal"],
)
