load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/lint:format.bzl", "format_test")

py_library(
    name = "define",
    srcs = ["__init__.py"],
    visibility = ["//define:__subpackages__"],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@aspect_rules_lint//format:ruff",
)
