"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class Runner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<slot>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class RunnerGuarantees:
    def __init__(self):
        self.guarantee_position_slot: list[literal.Task] = []


@final
class RunnerExecution:
    def __init__(
        self,
        action: Runner,
        scheduler: literal.Scheduler,
        guarantees: RunnerGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees

    def accept_for_empty_rule_position_slot(self):
        self.destroy_position_slot()

    def destroy_position_slot(self):
        self.action.get_interface_position(
            "position<slot>"
        ).destroy_particle()
        self.action.get_interface_position(
            "position<slot>"
        ).create_particle()
        self.scheduler.continue_with(self.guarantees.guarantee_position_slot)
