"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destruct
import local.my_domain_com.my_lib.maker


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_position_source)
        execution.create_action_destroyer__position_trigger_pos()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()
        self.trigger_action_destroyer__position_parent__action_destruct = local.my_domain_com.my_lib.destruct.DestructGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.maker.Maker,
                local.my_domain_com.my_lib.destruct.Destruct,
            ),
            scheduler=self.scheduler,
        )
        self.execution_trigger_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_trigger_action_destroyer: literal.DestructionConnection
        self.trigger_action_destroyer_destruction_connections: literal.DestructionConnections
        self.execution_trigger_action_destroyer__position_parent__action_destruct: local.my_domain_com.my_lib.destruct.DestructExecution
        self.join_for_trigger_action_destroyer__when_empty_position_parent__action_maker__position_trigger_pos = literal.Join(2)
        self.join_for_trigger_action_destroyer__when_empty_position_parent__action_maker__position_result = literal.Join(2)
        self.join_for_trigger_action_destroyer__position_parent__action_destruct__for_empty_rule_action_maker__position_result = literal.Join(2)

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<parent>"
            )
        )
        self.execution_trigger_action_destroyer__position_parent__action_destruct = local.my_domain_com.my_lib.destruct.DestructExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<parent>"
            ).particle.get_action(
                local.my_domain_com.my_lib.destruct.Destruct
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer__position_parent__action_destruct,
        )
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_parent__action_maker__position_trigger_pos)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_parent__action_maker__position_result)
        self.trigger_action_destroyer__position_parent__action_destruct__for_empty_rule_action_maker__position_result()

    def create_action_destroyer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_connection_trigger_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_parent__action_maker__position_result,
            1,
            self.trigger_action_destroyer__position_parent__action_destruct__for_empty_rule_action_maker__position_result,
        )
        self.guarantees.trigger_action_destroyer__position_parent__action_destruct.guarantee_action_maker__position_result.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.trigger_action_destroyer_destruction_connections = literal.DestructionConnections(
            self.destruction_connection_trigger_action_destroyer,
        )
        self.execution_trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer,
            destruction_connections=self.trigger_action_destroyer_destruction_connections,
        )
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_parent__action_maker__position_trigger_pos)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_parent__action_maker__position_result)
        self.trigger_action_destroyer__for_empty_rule_position_parent()

    def trigger_action_destroyer__when_empty_position_parent__action_maker__position_trigger_pos(self):
        if not self.join_for_trigger_action_destroyer__when_empty_position_parent__action_maker__position_trigger_pos.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_empty_position_parent__action_maker__position_trigger_pos()

    def trigger_action_destroyer__when_empty_position_parent__action_maker__position_result(self):
        if not self.join_for_trigger_action_destroyer__when_empty_position_parent__action_maker__position_result.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_empty_position_parent__action_maker__position_result()

    def trigger_action_destroyer__for_empty_rule_position_parent(self):
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_parent()

    def trigger_action_destroyer__position_parent__action_destruct__for_empty_rule_action_maker__position_result(self):
        if not self.join_for_trigger_action_destroyer__position_parent__action_destruct__for_empty_rule_action_maker__position_result.arrive():
            return
        self.execution_trigger_action_destroyer__position_parent__action_destruct.accept_for_empty_rule_action_maker__position_result()
