"""Generated by the Define compiler."""

from typing import ClassVar

from define.runtime import literal

import local.my_domain_com.my_lib.grandchild
import local.my_domain_com.my_lib.sibling


class Child(literal.GlobalPosition):
    constraints: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.grandchild.Grandchild,
        local.my_domain_com.my_lib.sibling.Sibling,
    )
