load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("//tools/lint:format.bzl", "format_test")

proto_library(
    name = "integer_enum_proto",
    srcs = ["integer_enum.proto"],
)

py_proto_library(
    name = "integer_enum_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":integer_enum_proto"],
)

proto_library(
    name = "nested_integer_enum_proto",
    srcs = ["nested_integer_enum.proto"],
)

py_proto_library(
    name = "nested_integer_enum_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":nested_integer_enum_proto"],
)

proto_library(
    name = "nested_no_brackets_message_proto",
    srcs = ["nested_no_brackets_message.proto"],
)

py_proto_library(
    name = "nested_no_brackets_message_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":nested_no_brackets_message_proto"],
)

proto_library(
    name = "nested_no_brackets_scalar_proto",
    srcs = ["nested_no_brackets_scalar.proto"],
)

py_proto_library(
    name = "nested_no_brackets_scalar_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":nested_no_brackets_scalar_proto"],
)

proto_library(
    name = "no_brackets_message_proto",
    srcs = ["no_brackets_message.proto"],
)

py_proto_library(
    name = "no_brackets_message_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":no_brackets_message_proto"],
)

proto_library(
    name = "no_brackets_scalar_proto",
    srcs = ["no_brackets_scalar.proto"],
)

py_proto_library(
    name = "no_brackets_scalar_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":no_brackets_scalar_proto"],
)

proto_library(
    name = "repeated_integer_enum_proto",
    srcs = ["repeated_integer_enum.proto"],
)

py_proto_library(
    name = "repeated_integer_enum_proto_py",
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = [":repeated_integer_enum_proto"],
)

py_library(
    name = "schemas_py",
    srcs = ["__init__.py"],
    visibility = ["//defcl/python/validator:__pkg__"],
    deps = ["//defcl/testdata/invalid/semantics"],
)

format_test(
    name = "format_test",
    srcs = glob(
        ["*.py"],
        exclude = ["*_pb2.py"],
    ),
    python = "@multitool//tools/ruff",
)
