load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:build_file_checks.bzl", "check_build_file")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "guarantee_generation",
    srcs = ["guarantee_generation.py"],
    deps = [
        ":particle_info",
        ":particle_state_store",
        "//define/compiler:ast",
        "//define/compiler:chained_name",
        "//define/compiler/validator/reference_graph:action_contract",
        "//define/compiler/validator/reference_graph:position_occupancy",
        "@pypi//msgspec",
    ],
)

py_library(
    name = "interface_arrival_tracker",
    srcs = ["interface_arrival_tracker.py"],
    deps = [
        ":particle_info",
        "//define/compiler:ast",
        "@pypi//msgspec",
    ],
)

py_library(
    name = "particle_info",
    srcs = ["particle_info.py"],
    visibility = ["//define/compiler/validator/reference_graph:__subpackages__"],
    deps = [
        "//define/compiler:ast",
        "//define/compiler/validator/reference_graph:quality_assignment",
        "@pypi//msgspec",
    ],
)

py_library(
    name = "particle_state_store",
    srcs = ["particle_state_store.py"],
    deps = [
        ":particle_info",
        "//define/compiler:ast",
        "//define/compiler:chained_name",
        "//define/compiler/data_structures:trie",
        "//define/compiler/validator/reference_graph:action_contract",
        "//define/compiler/validator/reference_graph:position_occupancy",
        "//define/compiler/validator/reference_graph/destruction:child_state",
        "@pypi//msgspec",
    ],
)

py_library(
    name = "particle_tracker",
    srcs = ["particle_tracker.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":guarantee_generation",
        ":interface_arrival_tracker",
        ":particle_info",
        ":particle_state_store",
        ":requirement_resolution",
        "//define/compiler:ast",
        "//define/compiler:chained_name",
        "//define/compiler/validator/reference_graph:action_contract",
        "//define/compiler/validator/reference_graph:position_occupancy",
        "//define/compiler/validator/reference_graph:quality_assignment",
        "//define/compiler/validator/reference_graph/destruction:child_state",
    ],
)

py_library(
    name = "requirement_resolution",
    srcs = ["requirement_resolution.py"],
    deps = [
        ":particle_info",
        ":particle_state_store",
        "//define/compiler:ast",
        "//define/compiler:chained_name",
        "//define/compiler/validator/reference_graph:action_contract",
        "//define/compiler/validator/reference_graph:position_occupancy",
        "@pypi//msgspec",
    ],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

pyright_test(
    name = "pyright_test",
    deps = [
        ":guarantee_generation",
        ":interface_arrival_tracker",
        ":particle_info",
        ":particle_state_store",
        ":particle_tracker",
        ":requirement_resolution",
    ],
)

check_build_file()
