"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.origin
import local.my_domain_com.my_lib.target


class TestAction(literal.Action):

    @override
    def run(self):
        holder = literal.LocalPosition(
            "position<holder>",
        )
        box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.origin.OriginPosition,
                local.my_domain_com.my_lib.target.TargetPosition,
            ),
        )
        box.create_particle()
        box.particle.get_position(
            local.my_domain_com.my_lib.origin.OriginPosition
        ).create_particle()
        box.particle.get_position(
            local.my_domain_com.my_lib.origin.OriginPosition
        ).move_particle_to(
            box.particle.get_position(
                local.my_domain_com.my_lib.target.TargetPosition
            )
        )
        box.particle.get_position(
            local.my_domain_com.my_lib.target.TargetPosition
        ).move_particle_to(
            holder
        )
        box.destroy_particle()
        holder.destroy_particle()
