"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_library_collection.outer_position
import local.my_domain_com.my_library_collection.perform_operation


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_library_collection.outer_position.OuterPosition,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_library_collection.outer_position.OuterPosition
        ).create_particle()
        literal.record_operation("test.create(/outer_position)")
        self.on_particle.get_position(
            local.my_domain_com.my_library_collection.outer_position.OuterPosition
        ).particle.get_action(
            local.my_domain_com.my_library_collection.perform_operation.PerformOperation
        ).get_interface_position(
            "position<operation_trigger>"
        ).create_particle()
        literal.record_operation("test.create(/outer_position::/perform_operation::operation_trigger)")
        self.on_particle.get_position(
            local.my_domain_com.my_library_collection.outer_position.OuterPosition
        ).particle.get_action(
            local.my_domain_com.my_library_collection.perform_operation.PerformOperation
        ).run()
