"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal


class CleanupBAction(literal.Action):

    @override
    def run(self):
        scratch = literal.LocalPosition[Never](
            "position<scratch>",
        )
        scratch.create_particle()
        literal.record_operation("cleanup_b.create(scratch)")
        scratch.destroy_particle()
        literal.record_operation("cleanup_b.destroy(scratch)")
