"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.empty_item


class CallEmpty(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.empty_item.EmptyItem,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class CallEmptyGuarantees:
    def __init__(self):
        self.trigger_action_empty_item = local.my_domain_com.my_lib.empty_item.EmptyItemGuarantees()


@final
class CallEmptyExecution:
    def __init__(
        self,
        action: CallEmpty,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: CallEmptyGuarantees,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.destruction_connections = destruction_connections
        self.execution_trigger_action_empty_item: local.my_domain_com.my_lib.empty_item.EmptyItemExecution
        self.join_for_trigger_action_empty_item__for_empty_rule_global_position_item = self.scheduler.create_join(2)

    def accept_action_parent(self):
        self.create_action_empty_item__position_trigger_pos()

    def accept_for_empty_rule_global_position_item(self):
        self.trigger_action_empty_item__for_empty_rule_global_position_item()

    def create_action_empty_item__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.empty_item.EmptyItem
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/empty_item::trigger_pos",
            1,
        )
        self.execution_trigger_action_empty_item = local.my_domain_com.my_lib.empty_item.EmptyItemExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.empty_item.EmptyItem
            ),
            self.scheduler,
            self.trace_execution,
            "empty_item",
            self.guarantees.trigger_action_empty_item,
            destruction_connections=self.destruction_connections,
        )
        self.scheduler.submit(self.destroy_action_empty_item__position_trigger_pos)
        self.trigger_action_empty_item__for_empty_rule_global_position_item()

    def destroy_action_empty_item__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.empty_item.EmptyItem
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/empty_item::trigger_pos",
            1,
        )

    def trigger_action_empty_item__for_empty_rule_global_position_item(self):
        if not self.join_for_trigger_action_empty_item__for_empty_rule_global_position_item.arrive():
            return
        self.execution_trigger_action_empty_item.accept_for_empty_rule_global_position_item()
