"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent


class Test(literal.Action):
    is_constructor: ClassVar[bool] = True
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def execute(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
