"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<gateway>",
                    constraints=(
                        local.my_domain_com.my_lib.other.Other,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.create_position_gateway()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_gateway__global_action_other = local.my_domain_com.my_lib.other.OtherGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.trigger_position_gateway__global_action_other__execution: local.my_domain_com.my_lib.other.OtherExecution
        self.join_for_trigger_position_gateway__global_action_other__for_empty_rule_position_source = literal.Join(3)

    def create_position_gateway(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).create_particle()
        self.scheduler.submit(self.create_position_gateway__global_action_other__position_source)
        self.create_position_gateway__global_action_other__position_trigger_pos()

    def create_position_gateway__global_action_other__position_source(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<source>"
        ).create_particle()
        self.scheduler.submit(self.create_position_gateway__global_action_other__position_source__global_position_a)
        self.create_position_gateway__global_action_other__position_source__global_position_b()

    def create_position_gateway__global_action_other__position_source__global_position_a(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.trigger_position_gateway__global_action_other__for_empty_rule_position_source()

    def create_position_gateway__global_action_other__position_source__global_position_b(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.trigger_position_gateway__global_action_other__for_empty_rule_position_source()

    def create_position_gateway__global_action_other__position_trigger_pos(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.init_trigger_position_gateway__global_action_other__execution()
        self.trigger_position_gateway__global_action_other__for_empty_rule_position_source()

    def init_trigger_position_gateway__global_action_other__execution(self):
        action = self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.other.Other
        )
        self.trigger_position_gateway__global_action_other__execution = local.my_domain_com.my_lib.other.OtherExecution(
            action,
            self.scheduler,
            self.guarantees.trigger_position_gateway__global_action_other,
        )

    def trigger_position_gateway__global_action_other__for_empty_rule_position_source(self):
        if not self.join_for_trigger_position_gateway__global_action_other__for_empty_rule_position_source.arrive():
            return
        self.trigger_position_gateway__global_action_other__execution.accept_for_empty_rule_position_source()
