"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.callee
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.marker


class Test(literal.Action):

    @override
    def run(self):
        carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.callee.Callee,
            ),
        )
        source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.marker.Marker,
                local.my_domain_com.my_lib.destructor.Destructor,
            ),
        )
        carrier.create_particle()
        source.create_particle()
        source.particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        source.particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).destroy_particle()
        source.move_particle_to(
            carrier.particle.get_action(
                local.my_domain_com.my_lib.callee.Callee
            ).get_interface_position(
                "position<src>"
            )
        )
        carrier.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        carrier.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).run()
        carrier.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        carrier.destroy_particle()
