"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.augend
import local.my_domain_com.my_lib.total
import standard.number.decimal.ascii


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.augend.AugendPosition,
        local.my_domain_com.my_lib.total.TotalPosition,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.augend.AugendPosition
        ).create_particle()
        literal.record_operation("test.create(/augend)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.total.TotalPosition
        ).create_particle()
        literal.record_operation("test.create(/total)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.augend.AugendPosition
        ).particle.value = 1.5
        literal.record_operation("test.set_value(/augend, 1.5)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.total.TotalPosition
        ).particle.value = standard.number.decimal.ascii.infix_add(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.augend.AugendPosition
            ).particle.value,
            2,
        )
        literal.record_operation("test.execute(operation<standard:/number/rational/add>, /augend, 2, /total)")
