"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Test(literal.Action):

    @override
    def run(self):
        parent = literal.LocalPosition(
            "position<parent>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
        )
        parent.create_particle()
        literal.record_operation("test.create(parent)")
        parent.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        literal.record_operation("test.create(parent::/child)")
        parent.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).destroy_particle()
        literal.record_operation("test.destroy(parent::/child)")
        parent.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        literal.record_operation("test.create(parent::/child)")
        parent.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).destroy_particle()
        literal.record_operation("test.destroy(parent::/child)")
        parent.destroy_particle()
        literal.record_operation("test.destroy(parent)")
