"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destructor


class Test(literal.Action):

    @override
    def run(self):
        staging = literal.LocalPosition(
            "position<staging>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
        )
        box = literal.LocalPosition(
            "position<box>",
        )
        staging.create_particle()
        literal.record_operation("test.create(staging)")
        staging.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        literal.record_operation("test.create(staging::/child)")
        staging.move_particle_to(
            box
        )
        literal.record_operation("test.move(staging, box)")
        box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).run()
        box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).destroy_particle()
        literal.record_operation("test.destroy(box::/child)")
        box.destroy_particle()
        literal.record_operation("test.destroy(box)")
