"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destroyer


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_position_first)
        execution.create_position_second()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()
        self.trigger_action_destroyer_2 = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_first = literal.LocalPosition(
            "position<first>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_second = literal.LocalPosition(
            "position<second>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        guarantees.trigger_action_destroyer.guarantee_position_run.append(
            self.move_position_second_to_action_destroyer__position_run
        )
        self.execution_trigger_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_trigger_action_destroyer: literal.DestructionConnection
        self.execution_trigger_action_destroyer_2: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_trigger_action_destroyer_2: literal.DestructionConnection
        self.destruction_position_action_destroyer__position_run__global_position_child: literal.Position
        self.destruction_position_action_destroyer__position_run__global_position_child_2: literal.Position
        self.join_for_move_position_second_to_action_destroyer__position_run = literal.Join(2)
        self.join_for_trigger_action_destroyer__for_empty_rule_position_run = literal.Join(2)
        self.join_for_trigger_action_destroyer_2__for_empty_rule_position_run = literal.Join(2)

    def create_position_first(self):
        self.local_position_first.create_particle()
        self.local_position_first.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.local_position_first.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.destruction_connection_trigger_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_destroyer__position_run__global_position_child,
        )
        self.execution_trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_run: self.destruction_connection_trigger_action_destroyer,
            },
            ),
        )
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_run)
        self.trigger_action_destroyer__for_empty_rule_position_run()

    def destroy_action_destroyer__position_run__global_position_child(self):
        self.destruction_position_action_destroyer__position_run__global_position_child.destroy_particle()
        self.destruction_connection_trigger_action_destroyer.complete()

    def create_position_second(self):
        self.local_position_second.create_particle()
        self.local_position_second.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.move_position_second_to_action_destroyer__position_run()

    def move_position_second_to_action_destroyer__position_run(self):
        if not self.join_for_move_position_second_to_action_destroyer__position_run.arrive():
            return
        self.local_position_second.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.destruction_connection_trigger_action_destroyer_2 = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_destroyer__position_run__global_position_child_2,
        )
        self.execution_trigger_action_destroyer_2 = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer_2,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_run: self.destruction_connection_trigger_action_destroyer_2,
            },
            ),
        )
        self.scheduler.submit(self.trigger_action_destroyer_2__for_empty_rule_position_run)
        self.trigger_action_destroyer_2__for_empty_rule_position_run()

    def destroy_action_destroyer__position_run__global_position_child_2(self):
        self.destruction_position_action_destroyer__position_run__global_position_child_2.destroy_particle()
        self.destruction_connection_trigger_action_destroyer_2.complete()

    def trigger_action_destroyer__for_empty_rule_position_run(self):
        if not self.join_for_trigger_action_destroyer__for_empty_rule_position_run.arrive():
            return
        self.destruction_position_action_destroyer__position_run__global_position_child = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_run()

    def trigger_action_destroyer_2__for_empty_rule_position_run(self):
        if not self.join_for_trigger_action_destroyer_2__for_empty_rule_position_run.arrive():
            return
        self.destruction_position_action_destroyer__position_run__global_position_child_2 = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_trigger_action_destroyer_2.accept_for_empty_rule_position_run()
