load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@rules_python//python:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_binary(
    name = "generate_action_graph_source",
    srcs = ["generate_action_graph_source.py"],
    deps = [
        ":generator_cli",
        ":generator_io",
        "@pypi//click",
    ],
)

py_test(
    name = "generate_action_graph_source_test",
    size = "small",
    srcs = ["generate_action_graph_source_test.py"],
    deps = [
        ":generate_action_graph_source",
        "//define/compiler:ast",
        "//define/compiler:driver",
        "//define/compiler:parser",
        "@pypi//click",
        "@pypi//pytest",
    ],
)

py_binary(
    name = "generate_deep_pipeline_source",
    srcs = ["generate_deep_pipeline_source.py"],
    deps = [
        ":generator_cli",
        ":generator_io",
        "@pypi//click",
    ],
)

py_test(
    name = "generate_deep_pipeline_source_test",
    size = "small",
    srcs = ["generate_deep_pipeline_source_test.py"],
    deps = [
        ":generate_deep_pipeline_source",
        "//define/compiler:driver",
        "@pypi//click",
        "@pypi//pytest",
    ],
)

py_binary(
    name = "generate_destruction_fragments_source",
    srcs = ["generate_destruction_fragments_source.py"],
    deps = [
        ":generator_cli",
        ":generator_io",
        "@pypi//click",
    ],
)

py_test(
    name = "generate_destruction_fragments_source_test",
    size = "small",
    srcs = ["generate_destruction_fragments_source_test.py"],
    deps = [
        ":generate_destruction_fragments_source",
        "//define/compiler:driver",
        "@pypi//click",
        "@pypi//pytest",
    ],
)

py_binary(
    name = "generate_large_define_source",
    srcs = ["generate_large_define_source.py"],
    deps = [
        ":generator_cli",
        ":generator_io",
        "@pypi//click",
    ],
)

py_test(
    name = "generate_large_define_source_test",
    size = "small",
    srcs = ["generate_large_define_source_test.py"],
    deps = [
        ":generate_large_define_source",
        "//define/compiler:ast",
        "//define/compiler:driver",
        "//define/compiler:parser",
        "@pypi//click",
        "@pypi//pytest",
    ],
)

py_binary(
    name = "generate_operation_graph_source",
    srcs = ["generate_operation_graph_source.py"],
    deps = [
        ":generator_cli",
        ":generator_io",
        "@pypi//click",
    ],
)

py_test(
    name = "generate_operation_graph_source_test",
    size = "small",
    srcs = ["generate_operation_graph_source_test.py"],
    deps = [
        ":generate_operation_graph_source",
        "//define/compiler:ast",
        "//define/compiler:driver",
        "//define/compiler:parser",
        "@pypi//click",
        "@pypi//pytest",
    ],
)

py_binary(
    name = "generate_reference_graph_project",
    srcs = ["generate_reference_graph_project.py"],
    deps = [
        ":generator_cli",
        "@pypi//click",
    ],
)

py_test(
    name = "generate_reference_graph_project_test",
    size = "small",
    srcs = ["generate_reference_graph_project_test.py"],
    deps = [
        ":generate_reference_graph_project",
        "//define/compiler:driver",
        "@pypi//click",
        "@pypi//pytest",
    ],
)

py_library(
    name = "generator_cli",
    srcs = ["generator_cli.py"],
    deps = ["@pypi//click"],
)

py_library(
    name = "generator_io",
    srcs = ["generator_io.py"],
)

py_test(
    name = "generator_io_test",
    size = "small",
    srcs = ["generator_io_test.py"],
    deps = [
        ":generator_io",
        "@pypi//pytest",
    ],
)

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

pyright_test(
    name = "pyright_test",
    deps = [
        ":generate_action_graph_source",
        ":generate_action_graph_source_test",
        ":generate_deep_pipeline_source",
        ":generate_deep_pipeline_source_test",
        ":generate_destruction_fragments_source",
        ":generate_destruction_fragments_source_test",
        ":generate_large_define_source",
        ":generate_large_define_source_test",
        ":generate_operation_graph_source",
        ":generate_operation_graph_source_test",
        ":generate_reference_graph_project",
        ":generate_reference_graph_project_test",
        ":generator_cli",
        ":generator_io",
        ":generator_io_test",
    ],
)
