# gazelle:python_extension disabled
load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")
load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "schemas_proto",
    srcs = [
        "integers.proto",
        "repeated_messages.proto",
        "single_toplevel.proto",
        "strings.proto",
    ],
    visibility = ["//visibility:public"],
)

py_proto_library(
    name = "schemas_py_pb2",
    visibility = ["//defcl:__subpackages__"],
    deps = [":schemas_proto"],
)

py_library(
    name = "init",
    srcs = ["__init__.py"],
    visibility = ["//defcl:__subpackages__"],
    deps = ["//defcl/testdata/valid:init"],
)

go_proto_library(
    name = "schemas_go_proto",
    importpath = "defcl/testdata/valid/schemas",
    proto = ":schemas_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "schemas",
    embed = [":schemas_go_proto"],
    importpath = "defcl/testdata/valid/schemas",
    visibility = ["//visibility:public"],
)
