"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.maker
import local.my_domain_com.my_lib.required


class DestroyerDestructionContracts:
    def run_destructors_position_parent(self, _particle: literal.Particle):
        pass

    def destroy_position_parent(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = DestroyerDestructionContracts()


class DestroyerAction(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[Never]("position<trigger_pos>"),
                literal.LocalPosition[Never](
                    "position<parent>",
                    constraints=(
                        local.my_domain_com.my_lib.maker.MakerAction,
                        local.my_domain_com.my_lib.required.RequiredPosition,
                    ),
                ),
            ],
        )

    @override
    def run(self, destruction_contracts: DestroyerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        held_required = literal.LocalPosition[Never](
            "position<held_required>",
        )
        self.get_interface_position(
            "position<parent>"
        ).particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("destroyer.create(parent::/maker::trigger_pos)")
        self.get_interface_position(
            "position<parent>"
        ).particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).run()
        self.get_interface_position(
            "position<parent>"
        ).particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<result>"
        ).move_particle_to(
            self.get_interface_position(
                "position<parent>"
            ).particle.get_position(
                local.my_domain_com.my_lib.required.RequiredPosition
            )
        )
        literal.record_operation("destroyer.move(parent::/maker::result, parent::/required)")
        self.get_interface_position(
            "position<parent>"
        ).particle.get_position(
            local.my_domain_com.my_lib.required.RequiredPosition
        ).move_particle_to(
            held_required
        )
        literal.record_operation("destroyer.move(parent::/required, held_required)")
        held_required.move_particle_to(
            self.get_interface_position(
                "position<parent>"
            ).particle.get_position(
                local.my_domain_com.my_lib.required.RequiredPosition
            )
        )
        literal.record_operation("destroyer.move(held_required, parent::/required)")
        destruction_contracts.run_destructors_position_parent(
            self.get_interface_position(
                "position<parent>"
            ).particle
        )
        destruction_contracts.destroy_position_parent(
            self.get_interface_position(
                "position<parent>"
            ).particle
        )
        self.get_interface_position(
            "position<parent>"
        ).particle.get_position(
            local.my_domain_com.my_lib.required.RequiredPosition
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(parent::/required)")
        self.get_interface_position(
            "position<parent>"
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(parent)")
