load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "codegen",
    srcs = ["__init__.py"],
)

py_library(
    name = "generator",
    srcs = ["generator.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "//define/compiler/validator:validation_result",
    ],
)

py_test(
    name = "generator_test",
    size = "small",
    srcs = ["generator_test.py"],
    deps = [
        ":generator",
        "//define/compiler:conftest",
        "//define/compiler:diagnostics",
    ],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

# IMPORTANT: When adding a new py_library, py_binary, or py_test target to this
# package, you must also add it to the deps list below.
pyright_test(
    name = "pyright_test",
    deps = [
        ":codegen",
        ":generator",
        ":generator_test",
    ],
)
