load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "action_plan",
    srcs = ["action_plan.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        "//define/compiler:ast",
        "//define/compiler/validator/reference_graph:operation_graph",
        "//define/compiler/validator/reference_graph:operation_graph_action_resolver",
    ],
)

py_test(
    name = "action_plan_test",
    size = "small",
    srcs = ["action_plan_test.py"],
    deps = [
        ":action_plan",
        "//define/compiler:ast",
        "//define/compiler:test_helpers",
        "//define/compiler/validator/reference_graph:action_contract",
        "//define/compiler/validator/reference_graph:operation_graph",
    ],
)

py_library(
    name = "codegen",
    srcs = ["__init__.py"],
)

py_library(
    name = "generated_program_runner",
    srcs = ["generated_program_runner.py"],
    visibility = ["//tools:__pkg__"],
)

py_library(
    name = "generator",
    srcs = ["generator.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "//define/compiler/codegen/literal/python:generator",
        "//define/compiler/graphs:reference_graph",
        "//define/compiler/validator/reference_graph:operation_graph",
    ],
)

py_test(
    name = "generator_integration_test",
    size = "small",
    srcs = ["generator_integration_test.py"],
    data = ["//define/testdata/codegen"],
    deps = [
        ":generated_program_runner",
        "//define/compiler:driver",
        "//define/compiler/validator:test_helpers",
        "//define/runtime:literal",  # keep
        "@pypi//pytest",
    ],
)

py_test(
    name = "generator_test",
    size = "small",
    srcs = ["generator_test.py"],
    data = ["//define/testdata/codegen/generator"],
    deps = [
        ":generated_program_runner",
        ":generator",
        "//define/compiler:conftest",
        "//define/compiler:diagnostics",
        "//define/compiler/validator:test_helpers",
        "//define/compiler/validator:validation_result",
        "//define/compiler/validator/reference_graph:reference_graph_validator",
        "//define/runtime:literal",  # keep
        "@pypi//pytest",
    ],
)

filegroup(
    name = "generator_test_sources",
    testonly = True,
    srcs = ["generator_test.py"],
    visibility = ["//define/testdata:__pkg__"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

# IMPORTANT: When adding a new py_library, py_binary, or py_test target to this
# package, you must also add it to the deps list below.
pyright_test(
    name = "pyright_test",
    deps = [
        ":action_plan",
        ":action_plan_test",
        ":codegen",
        ":generated_program_runner",
        ":generator",
        ":generator_integration_test",
        ":generator_test",
    ],
)
