"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.c
import local.my_domain_com.my_lib.maker


class TestAction(literal.Action):

    @override
    def run(self):
        gw = literal.LocalPosition[Never](
            "position<gw>",
            constraints=(
                local.my_domain_com.my_lib.maker.MakerAction,
            ),
        )
        gw.create_particle()
        literal.record_operation("test.create(gw)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<held>"
        ).create_particle()
        literal.record_operation("test.create(gw::/maker::held)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(gw::/maker::trigger_pos)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<held>"
        ).particle.get_position(
            local.my_domain_com.my_lib.c.CPosition
        ).destroy_particle()
        literal.record_operation("test.destroy(gw::/maker::held::/c)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(gw::/maker::trigger_pos)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(gw::/maker::trigger_pos)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).run()
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<held>"
        ).particle.get_position(
            local.my_domain_com.my_lib.c.CPosition
        ).destroy_particle()
        literal.record_operation("test.destroy(gw::/maker::held::/c)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<held>"
        ).destroy_particle()
        literal.record_operation("test.destroy(gw::/maker::held)")
        gw.particle.get_action(
            local.my_domain_com.my_lib.maker.MakerAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(gw::/maker::trigger_pos)")
        gw.destroy_particle()
        literal.record_operation("test.destroy(gw)")
