"""Python literal code generator for the Define compiler."""

from __future__ import annotations

import typing
from pathlib import Path

from define.compiler import ast
from define.compiler.codegen.literal.python import (
    action_context,
    action_definition,
    naming,
    position_definition,
    template_context,
    template_env,
)
from define.compiler.graphs import reference_graph_executor

if typing.TYPE_CHECKING:
    import jinja2

    from define.compiler.validator import codegen_input as codegen_input_types

_TEMPLATES_DIR = Path(__file__).parent
_COMPILED_DIR = _TEMPLATES_DIR / "templates.compiled"
_ENV = template_env.create_environment(
    _TEMPLATES_DIR,
    _COMPILED_DIR,
    template_globals={
        "ChainAccessor": template_context.ChainAccessor,
        "StatementKind": template_context.StatementKind,
    },
)
_POSITION_TEMPLATE = _ENV.get_template("position_definition.j2")
_ACTION_TEMPLATE = _ENV.get_template("action_definition.j2")
_ENTRY_POINT_TEMPLATE = _ENV.get_template("entry_point.j2")
_PACKAGE_INIT = '"""Generated by the Define compiler."""\n'

type _DefinitionContext = (
    action_context.ActionDefinitionContext | template_context.PositionDefinitionContext
)


@typing.final
class _DefinitionGenerator:
    """Generate definitions after their referenced definitions complete."""

    def __init__(
        self,
        codegen_input: codegen_input_types.CodegenInput,
        entry_point: ast.ActionDefinition,
        converter: naming.NameConverter,
        output_dir: Path,
        *,
        trace_operations: bool,
    ):
        """Initialize the shared generation inputs."""
        self._codegen_input = codegen_input
        self._entry_point = entry_point
        self._converter = converter
        self._trace_operations = trace_operations
        self._output_dir = output_dir
        self._entry_definition: action_context.ActionDefinitionContext

    def generate(
        self,
        *,
        max_workers: int | None,
    ) -> tuple[action_context.ActionDefinitionContext, set[Path]]:
        """Generate every definition with bounded worker concurrency."""
        package_dirs = reference_graph_executor.process_definitions(
            self._codegen_input.definition_order,
            self._generate_definition,
            max_workers=max_workers,
        )
        return self._entry_definition, set(package_dirs)

    def _generate_definition(self, definition: ast.QualityDefinition) -> Path:
        if isinstance(definition, ast.ActionDefinition):
            context = self._generate_action(definition)
            template = _ACTION_TEMPLATE
        else:
            context = position_definition.PositionDefinitionGenerator(
                typing.cast("ast.PositionDefinition", definition),
                self._converter,
            ).generate()
            template = _POSITION_TEMPLATE
        return self._write_definition_file(template, context)

    def _generate_action(
        self,
        definition: ast.ActionDefinition,
    ) -> action_context.ActionDefinitionContext:
        context = action_definition.ActionDefinitionGenerator(
            self._codegen_input.actions[definition.typed_name.full_typed_name],
            self._converter,
            trace_operations=self._trace_operations,
        ).generate()
        if definition.typed_name == self._entry_point.typed_name:
            self._entry_definition = context
        return context

    def _write_definition_file(
        self,
        template: jinja2.Template,
        context: _DefinitionContext,
    ) -> Path:
        """Render and write a definition file."""
        content = template.render(definition=context)

        # TODO: Two definitions whose FQUN paths map to the same Python module
        # (e.g., a position and an action with the same `/path` defined in one
        # source file, or two positions sharing a path) can write the same file
        # concurrently. The generator needs to either group same-module
        # definitions into a single rendered file or reject the collision.
        relative_file_path = naming.file_path_for_module(context.module_name)
        file_path = self._output_dir / relative_file_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        _ = file_path.write_text(content)
        return relative_file_path.parent.parent


class PythonLiteralCodeGenerator:
    """Generates literal Python code for a validated Define entry point."""

    def generate(
        self,
        codegen_input: codegen_input_types.CodegenInput,
        entry_point: ast.ActionDefinition,
        output_dir: Path,
        *,
        trace_operations: bool = False,
        max_workers: int | None = None,
    ):
        """Generate Python files for the entry-point constructor and its references."""
        converter = naming.NameConverter()
        # Authority-name collisions are assigned by first use, so preserve the
        # existing definition-order choice before workers share the converter.
        for definition in codegen_input.definition_order.definitions:
            _ = converter.module_name(definition.typed_name.name_content)
        entry_definition, package_dirs = _DefinitionGenerator(
            codegen_input,
            entry_point,
            converter,
            output_dir,
            trace_operations=trace_operations,
        ).generate(max_workers=max_workers)

        self._write_init_files(package_dirs, output_dir)
        self._write_entry_point(entry_definition, output_dir)

    def _write_init_files(self, package_dirs: set[Path], output_dir: Path):
        """Write empty __init__.py files for intermediate packages."""
        needed_dirs: set[Path] = set()
        for package_dir in package_dirs:
            needed_dirs.add(package_dir)
            for parent in package_dir.parents:
                if parent == Path("."):
                    continue
                needed_dirs.add(parent)

        for dir_path in sorted(needed_dirs):
            init_file = output_dir / dir_path / "__init__.py"
            if not init_file.exists():
                _ = init_file.write_text(_PACKAGE_INIT)

    def _write_entry_point(
        self,
        context: action_context.ActionDefinitionContext,
        output_dir: Path,
    ):
        """Write the __main__.py entry point file."""
        content = _ENTRY_POINT_TEMPLATE.render(
            entry_reference=naming.ClassReference(
                module_name=context.module_name,
                class_name=context.class_name,
            ),
            trace_operations=context.trace_operations,
        )
        _ = (output_dir / "__main__.py").write_text(content)
