"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.left


class ParentDestructor(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.left.Left,
    )

    @override
    def run(self):
        holder = literal.LocalPosition(
            "position<holder>",
        )
        self.on_particle.get_position(
            local.my_domain_com.my_lib.left.Left
        ).move_particle_to(
            holder
        )
        holder.move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.left.Left
            )
        )
