"""Generated by the Define compiler."""

from typing import ClassVar

from define.runtime import literal

import local.my_domain_com.my_lib.extra_a
import local.my_domain_com.my_lib.extra_b
import local.my_domain_com.my_lib.work


class Required(literal.GlobalPosition):
    constraints: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.extra_a.ExtraA,
        local.my_domain_com.my_lib.extra_b.ExtraB,
        local.my_domain_com.my_lib.work.Work,
    )
