"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.grandchild
import local.my_domain_com.my_lib.greatgrandchild
import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent
import local.my_domain_com.my_lib.sibling


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        literal.record_operation("test.create(/parent)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        literal.record_operation("test.create(/parent::/child)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.Grandchild
        ).create_particle()
        literal.record_operation("test.create(/parent::/child::/grandchild)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.Grandchild
        ).particle.get_position(
            local.my_domain_com.my_lib.greatgrandchild.Greatgrandchild
        ).create_particle()
        literal.record_operation("test.create(/parent::/child::/grandchild::/greatgrandchild)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.sibling.Sibling
        ).create_particle()
        literal.record_operation("test.create(/parent::/sibling)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(/middle::trigger_pos)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).run(MiddleDestructionContracts())
        self.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(/middle::trigger_pos)")


class MiddleDestructionContracts(local.my_domain_com.my_lib.middle.MiddleDestructionContracts):

    @override
    def destroy_global_position_parent__position_child__position_grandchild(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.greatgrandchild.Greatgrandchild
        ).destroy_particle()
        literal.record_operation("middle.destroy(/parent::/child::/grandchild::/greatgrandchild)")

    @override
    def destroy_global_position_parent(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.sibling.Sibling
        ).destroy_particle()
        literal.record_operation("inner.destroy(/parent::/sibling)")
