"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.triggered


class Test(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/test>"
    is_constructor: ClassVar[bool] = True
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.triggered.Triggered,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition(
                    "position<source>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                ),
            ],
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<source>"
        ).create_particle()
        self.get_interface_position(
            "position<source>"
        ).particle.get_position(
            "position<my.domain.com:my_lib:/child>"
        ).create_particle()
        self.get_interface_position(
            "position<source>"
        ).move_particle_to(
            self.on_particle.get_action(
                "action<my.domain.com:my_lib:/triggered>"
            ).get_interface_position(
                "position<run>"
            )
        )
