"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.leaf
import local.my_domain_com.my_lib.mid
import local.my_domain_com.my_lib.runner


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.runner.Runner,
    )

    @override
    def run(self):
        self.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).get_interface_position(
            "position<wrap>"
        ).create_particle()
        literal.record_operation("test.create(/runner::wrap)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).get_interface_position(
            "position<wrap>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid.Mid
        ).create_particle()
        literal.record_operation("test.create(/runner::wrap::/mid)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).get_interface_position(
            "position<wrap>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid.Mid
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.Leaf
        ).create_particle()
        literal.record_operation("test.create(/runner::wrap::/mid::/leaf)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        literal.record_operation("test.create(/runner::run)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).run()
