"""Generated by the Define compiler."""

from typing import Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b


class TestAction(literal.Action):

    @override
    def run(self):
        source = literal.LocalPosition[Never](
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.a.APosition,
                local.my_domain_com.my_lib.b.BPosition,
            ),
        )
        destination = literal.LocalPosition[Never](
            "position<destination>",
        )
        source.create_particle()
        source.particle.get_position(
            local.my_domain_com.my_lib.a.APosition
        ).create_particle()
        source.particle.get_position(
            local.my_domain_com.my_lib.b.BPosition
        ).create_particle()
        source.move_particle_to(
            destination
        )
        destination.particle.get_position(
            local.my_domain_com.my_lib.a.APosition
        ).destroy_particle()
        destination.particle.get_position(
            local.my_domain_com.my_lib.b.BPosition
        ).destroy_particle()
        destination.destroy_particle()
