"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.maker


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
            TestGuarantees(),
        )
        execution.create_position_box()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_box__action_maker = local.my_domain_com.my_lib.maker.MakerGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: TestGuarantees,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.maker.Maker,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_held = literal.LocalPosition(
            "position<held>",
            scheduler=self.scheduler,
        )
        guarantees.trigger_position_box__action_maker.guarantee_position_result.append(
            self.move_position_box__action_maker__position_result_to_position_held
        )
        self.execution_trigger_position_box__action_maker: local.my_domain_com.my_lib.maker.MakerExecution
        self.execution_trigger_position_held__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.join_for_destroy_position_box = literal.Join(2)
        self.join_for_trigger_position_box__action_maker__action_parent = literal.Join(2)
        self.join_for_trigger_position_box__action_maker__when_empty_position_result = literal.Join(2)
        self.join_for_trigger_position_held__action_destructor__action_parent = literal.Join(2)

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.scheduler.submit(self.create_position_box__action_maker__position_run)
        self.scheduler.submit(self.trigger_position_box__action_maker__action_parent)
        self.trigger_position_box__action_maker__when_empty_position_result()

    def create_position_box__action_maker__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/maker::run",
            1,
        )
        self.init_execution_trigger_position_box__action_maker()
        self.scheduler.submit(self.destroy_position_box__action_maker__position_run)
        self.scheduler.submit(self.trigger_position_box__action_maker__action_parent)
        self.trigger_position_box__action_maker__when_empty_position_result()

    def move_position_box__action_maker__position_result_to_position_held(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<result>"
        ).move_particle_to(self.local_position_held)
        self.scheduler.move_completed(
            self.trace_execution,
            "box::/maker::result",
            "held",
            1,
        )
        self.init_execution_trigger_position_held__action_destructor()
        self.scheduler.submit(self.destroy_position_held)
        self.scheduler.submit(self.destroy_position_box)
        self.scheduler.submit(self.trigger_position_held__action_destructor__action_parent)
        self.trigger_position_held__action_destructor__action_parent()

    def destroy_position_held(self):
        self.local_position_held.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "held",
            1,
        )

    def destroy_position_box__action_maker__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/maker::run",
            1,
        )
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box",
            1,
        )

    def init_execution_trigger_position_box__action_maker(self):
        action = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        )
        self.execution_trigger_position_box__action_maker = local.my_domain_com.my_lib.maker.MakerExecution(
            action,
            self.scheduler,
            self.trace_execution,
            "maker",
            self.guarantees.trigger_position_box__action_maker,
        )

    def init_execution_trigger_position_held__action_destructor(self):
        self.execution_trigger_position_held__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
            self.trace_execution,
            "destructor",
        )

    def trigger_position_box__action_maker__action_parent(self):
        if not self.join_for_trigger_position_box__action_maker__action_parent.arrive():
            return
        self.execution_trigger_position_box__action_maker.accept_action_parent()

    def trigger_position_box__action_maker__when_empty_position_result(self):
        if not self.join_for_trigger_position_box__action_maker__when_empty_position_result.arrive():
            return
        self.execution_trigger_position_box__action_maker.accept_when_empty_position_result()

    def trigger_position_held__action_destructor__action_parent(self):
        if not self.join_for_trigger_position_held__action_destructor__action_parent.arrive():
            return
        self.execution_trigger_position_held__action_destructor.accept_action_parent()
