"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Test(literal.Action):
    is_constructor: ClassVar[bool] = True

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition(
                    "position<src>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                ),
                literal.InterfacePosition(
                    "position<dest>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                ),
            ],
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<src>"
        ).create_particle()
        self.get_interface_position(
            "position<src>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.get_interface_position(
            "position<src>"
        ).move_particle_to(
            self.get_interface_position(
                "position<dest>"
            )
        )
        self.get_interface_position(
            "position<dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).destroy_particle()
