"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.react_a
import local.my_domain_com.my_lib.react_b


class KickOff(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.InterfacePosition("position<trigger>"),
                literal.InterfacePosition(
                    "position<output>",
                    constraints=(
                        local.my_domain_com.my_lib.react_a.ReactA,
                        local.my_domain_com.my_lib.react_b.ReactB,
                    ),
                ),
            ],
            trigger_position_name="position<trigger>",
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<output>"
        ).create_particle()
        self.get_interface_position(
            "position<output>"
        ).particle.get_action(
            local.my_domain_com.my_lib.react_a.ReactA
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.get_interface_position(
            "position<output>"
        ).particle.get_action(
            local.my_domain_com.my_lib.react_b.ReactB
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
