"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.c


class Worker(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<item>",
                    constraints=(
                        local.my_domain_com.my_lib.a.A,
                        local.my_domain_com.my_lib.b.B,
                        local.my_domain_com.my_lib.c.C,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class WorkerGuarantees:
    def __init__(self):
        self.position_item = literal.Guarantee()
        self.position_trigger_pos = literal.Guarantee()


@final
class WorkerExecution:
    def __init__(
        self,
        action: Worker,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = WorkerGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_holder = literal.LocalPosition(
            "position<holder>",
            scheduler=self.scheduler,
        )
        self.join_for_move_position_item_to_position_holder: literal.Join
        self.join_for_destroy_position_trigger_pos: literal.Join
        self.join_for_empty_rule_position_item: literal.Join
        self.join_for_empty_rule_position_trigger_pos: literal.Join

    def accept_for_empty_rule_position_item(self):
        if not self.join_for_empty_rule_position_item.arrive():
            return
        self.move_position_item_to_position_holder()

    def accept_for_empty_rule_position_trigger_pos(self):
        if not self.join_for_empty_rule_position_trigger_pos.arrive():
            return
        self.destroy_position_trigger_pos()

    def move_position_item_to_position_holder(self):
        if not self.join_for_move_position_item_to_position_holder.arrive():
            return
        self.action.get_interface_position(
            "position<item>"
        ).move_particle_to(self.local_position_holder)
        self.local_position_holder.move_particle_to(
            self.action.get_interface_position(
                "position<item>"
            )
        )
        self.guarantees.position_item.publish(
            self.scheduler,
        )

    def destroy_position_trigger_pos(self):
        if not self.join_for_destroy_position_trigger_pos.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger_pos)

    def continue_destroy_position_trigger_pos(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.guarantees.position_trigger_pos.publish(
            self.scheduler,
        )
