"""Minimal type stubs for pygtrie."""

from collections.abc import Iterable, Iterator
from typing import Any, Generic, TypeVar

_K = TypeVar("_K")
_V = TypeVar("_V")

class _Step(Generic[_K, _V]):
    key: _K | None
    value: _V
    def __bool__(self) -> bool: ...

class Trie(Generic[_K, _V]):
    def _path_from_key(self, key: _K) -> Any: ...
    def _key_from_path(self, path: Any) -> _K: ...
    def __setitem__(self, key: _K, value: _V) -> None: ...
    def __contains__(self, key: _K) -> bool: ...
    def __getitem__(self, key: _K) -> _V: ...
    def longest_prefix(self, key: _K) -> _Step[_K, _V]: ...

class StringTrie(Trie[str, _V]):
    def __init__(self, separator: str = ...) -> None: ...
    def iterkeys(self, prefix: str = ...) -> Iterator[str]: ...

class PrefixSet(Generic[_K]):
    def __init__(
        self, iterable: Any = ..., factory: Any = ..., **kwargs: Any
    ) -> None: ...
    def add(self, value: _K) -> None: ...
    def __contains__(self, key: _K) -> bool: ...
    def __iter__(self) -> Iterator[_K]: ...
    def iter(self, prefix: _K = ...) -> Iterable[_K]: ...
