"""Minimal type stubs for pygtrie."""

from collections.abc import Iterable, Iterator
from typing import Any

class _Step[K, V]:
    key: K | None
    value: V
    def __bool__(self) -> bool: ...

class Trie[K, V]:
    def _path_from_key(self, key: K) -> Any: ...
    def _key_from_path(self, path: Any) -> K: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __contains__(self, key: K) -> bool: ...
    def __getitem__(self, key: K) -> V: ...
    def longest_prefix(self, key: K) -> _Step[K, V]: ...

class StringTrie[V](Trie[str, V]):
    def __init__(self, separator: str = ...) -> None: ...
    def iterkeys(self, prefix: str = ...) -> Iterator[str]: ...

class PrefixSet[K]:
    def __init__(
        self, iterable: Any = ..., factory: Any = ..., **kwargs: Any
    ) -> None: ...
    def add(self, value: K) -> None: ...
    def __contains__(self, key: K) -> bool: ...
    def __iter__(self) -> Iterator[K]: ...
    def iter(self, prefix: K = ...) -> Iterable[K]: ...
