"""Minimal type stubs for pygtrie."""

from typing import Generic, TypeVar

_V = TypeVar("_V")

class _Step(Generic[_V]):
    key: str | None
    value: _V
    def __bool__(self) -> bool: ...

class StringTrie(Generic[_V]):
    def __init__(self, separator: str = ...) -> None: ...
    def __setitem__(self, key: str, value: _V) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> _V: ...
    def longest_prefix(self, key: str) -> _Step[_V]: ...
