"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.worker


class Test(literal.EntryPoint):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<gateway>",
                    constraints=(
                        local.my_domain_com.my_lib.worker.Worker,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
            TestGuarantees(),
        )
        execution.create_position_gateway()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_gateway__action_worker = local.my_domain_com.my_lib.worker.WorkerGuarantees()
        self.trigger_position_gateway__action_worker_2 = local.my_domain_com.my_lib.worker.WorkerGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        guarantees.trigger_position_gateway__action_worker.guarantee_position_trigger_pos.append(
            self.create_position_gateway__action_worker__position_trigger_pos_2
        )
        guarantees.trigger_position_gateway__action_worker.guarantee_position_item.append(
            self.trigger_position_gateway__action_worker_2__for_empty_rule_position_item
        )
        self.execution_trigger_position_gateway__action_worker: local.my_domain_com.my_lib.worker.WorkerExecution
        self.execution_trigger_position_gateway__action_worker_2: local.my_domain_com.my_lib.worker.WorkerExecution
        self.join_for_trigger_position_gateway__action_worker__for_empty_rule_position_item = self.scheduler.create_join(2)
        self.join_for_trigger_position_gateway__action_worker__for_empty_rule_position_trigger_pos = self.scheduler.create_join(2)
        self.join_for_trigger_position_gateway__action_worker_2__for_empty_rule_position_item = self.scheduler.create_join(2)
        self.join_for_trigger_position_gateway__action_worker_2__for_empty_rule_position_trigger_pos = self.scheduler.create_join(2)

    def create_position_gateway(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway",
            1,
        )
        self.scheduler.submit(self.create_position_gateway__action_worker__position_item)
        self.create_position_gateway__action_worker__position_trigger_pos()

    def create_position_gateway__action_worker__position_item(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<item>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway::/worker::item",
            1,
        )
        self.trigger_position_gateway__action_worker__for_empty_rule_position_item()

    def create_position_gateway__action_worker__position_trigger_pos(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway::/worker::trigger_pos",
            1,
        )
        self.execution_trigger_position_gateway__action_worker = local.my_domain_com.my_lib.worker.WorkerExecution(
            self.action.get_interface_position(
                "position<gateway>"
            ).particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ),
            self.scheduler,
            self.trace_execution,
            "worker",
            self.guarantees.trigger_position_gateway__action_worker,
        )
        self.scheduler.submit(self.trigger_position_gateway__action_worker__for_empty_rule_position_trigger_pos)
        self.scheduler.submit(self.trigger_position_gateway__action_worker__for_empty_rule_position_item)
        self.trigger_position_gateway__action_worker__for_empty_rule_position_trigger_pos()

    def create_position_gateway__action_worker__position_trigger_pos_2(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway::/worker::trigger_pos",
            2,
        )
        self.execution_trigger_position_gateway__action_worker_2 = local.my_domain_com.my_lib.worker.WorkerExecution(
            self.action.get_interface_position(
                "position<gateway>"
            ).particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ),
            self.scheduler,
            self.trace_execution,
            "worker#2",
            self.guarantees.trigger_position_gateway__action_worker_2,
        )
        self.scheduler.submit(self.trigger_position_gateway__action_worker_2__for_empty_rule_position_trigger_pos)
        self.scheduler.submit(self.trigger_position_gateway__action_worker_2__for_empty_rule_position_item)
        self.trigger_position_gateway__action_worker_2__for_empty_rule_position_trigger_pos()

    def trigger_position_gateway__action_worker__for_empty_rule_position_item(self):
        if not self.join_for_trigger_position_gateway__action_worker__for_empty_rule_position_item.arrive():
            return
        self.execution_trigger_position_gateway__action_worker.accept_for_empty_rule_position_item()

    def trigger_position_gateway__action_worker__for_empty_rule_position_trigger_pos(self):
        if not self.join_for_trigger_position_gateway__action_worker__for_empty_rule_position_trigger_pos.arrive():
            return
        self.execution_trigger_position_gateway__action_worker.accept_for_empty_rule_position_trigger_pos()

    def trigger_position_gateway__action_worker_2__for_empty_rule_position_item(self):
        if not self.join_for_trigger_position_gateway__action_worker_2__for_empty_rule_position_item.arrive():
            return
        self.execution_trigger_position_gateway__action_worker_2.accept_for_empty_rule_position_item()

    def trigger_position_gateway__action_worker_2__for_empty_rule_position_trigger_pos(self):
        if not self.join_for_trigger_position_gateway__action_worker_2__for_empty_rule_position_trigger_pos.arrive():
            return
        self.execution_trigger_position_gateway__action_worker_2.accept_for_empty_rule_position_trigger_pos()
