"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.marker_a
import local.my_domain_com.my_lib.marker_b


class DestroyerDestructionContracts:
    def run_destructors_position_run__position_marker_a(self, _particle: literal.Particle):
        pass

    def destroy_position_run__position_marker_a(self, _particle: literal.Particle):
        pass

    def run_destructors_position_run__position_marker_b(self, _particle: literal.Particle):
        pass

    def destroy_position_run__position_marker_b(self, _particle: literal.Particle):
        pass

    def run_destructors_position_run(self, _particle: literal.Particle):
        pass

    def destroy_position_run(self, _particle: literal.Particle):
        pass


_DEFAULT_DESTRUCTION_CONTRACTS = DestroyerDestructionContracts()


class DestroyerAction(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.marker_a.MarkerAPosition,
                        local.my_domain_com.my_lib.marker_b.MarkerBPosition,
                    ),
                ),
            ],
        )

    @override
    def run(self, destruction_contracts: DestroyerDestructionContracts = _DEFAULT_DESTRUCTION_CONTRACTS):
        holder_a = literal.LocalPosition(
            "position<holder_a>",
        )
        holder_b = literal.LocalPosition(
            "position<holder_b>",
        )
        self.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_a.MarkerAPosition
        ).move_particle_to(
            holder_a
        )
        literal.record_operation("destroyer.move(run::/marker_a, holder_a)")
        holder_a.move_particle_to(
            self.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_a.MarkerAPosition
            )
        )
        literal.record_operation("destroyer.move(holder_a, run::/marker_a)")
        self.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_b.MarkerBPosition
        ).move_particle_to(
            holder_b
        )
        literal.record_operation("destroyer.move(run::/marker_b, holder_b)")
        holder_b.move_particle_to(
            self.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_b.MarkerBPosition
            )
        )
        literal.record_operation("destroyer.move(holder_b, run::/marker_b)")
        destruction_contracts.run_destructors_position_run__position_marker_a(
            self.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_a.MarkerAPosition
            ).particle
        )
        destruction_contracts.run_destructors_position_run__position_marker_b(
            self.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_b.MarkerBPosition
            ).particle
        )
        destruction_contracts.run_destructors_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        destruction_contracts.destroy_position_run__position_marker_a(
            self.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_a.MarkerAPosition
            ).particle
        )
        destruction_contracts.destroy_position_run__position_marker_b(
            self.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_b.MarkerBPosition
            ).particle
        )
        destruction_contracts.destroy_position_run(
            self.get_interface_position(
                "position<run>"
            ).particle
        )
        self.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_a.MarkerAPosition
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(run::/marker_a)")
        self.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_b.MarkerBPosition
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(run::/marker_b)")
        self.get_interface_position(
            "position<run>"
        ).destroy_particle()
        literal.record_operation("destroyer.destroy(run)")
