"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.construct_a
import local.my_domain_com.my_lib.construct_b
import local.my_domain_com.my_lib.destruct_a
import local.my_domain_com.my_lib.destruct_b


class Test(literal.EntryPoint):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<box>",
                    constraints=(
                        local.my_domain_com.my_lib.construct_a.ConstructA,
                        local.my_domain_com.my_lib.construct_b.ConstructB,
                        local.my_domain_com.my_lib.destruct_a.DestructA,
                        local.my_domain_com.my_lib.destruct_b.DestructB,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        execution.create_position_box()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.execution_trigger_position_box__action_construct_a: local.my_domain_com.my_lib.construct_a.ConstructAExecution
        self.execution_trigger_position_box__action_construct_b: local.my_domain_com.my_lib.construct_b.ConstructBExecution
        self.execution_trigger_position_box__action_destruct_b: local.my_domain_com.my_lib.destruct_b.DestructBExecution
        self.execution_trigger_position_box__action_destruct_a: local.my_domain_com.my_lib.destruct_a.DestructAExecution
        self.join_for_trigger_position_box__action_construct_a__action_parent = self.scheduler.create_join(2)
        self.join_for_trigger_position_box__action_construct_b__action_parent = self.scheduler.create_join(2)
        self.join_for_trigger_position_box__action_destruct_b__action_parent = self.scheduler.create_join(2)
        self.join_for_trigger_position_box__action_destruct_a__action_parent = self.scheduler.create_join(2)

    def create_position_box(self):
        self.action.get_interface_position(
            "position<box>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.execution_trigger_position_box__action_construct_a = local.my_domain_com.my_lib.construct_a.ConstructAExecution(
            self.scheduler,
            self.trace_execution,
            "construct_a",
        )
        self.execution_trigger_position_box__action_construct_b = local.my_domain_com.my_lib.construct_b.ConstructBExecution(
            self.scheduler,
            self.trace_execution,
            "construct_b",
        )
        self.execution_trigger_position_box__action_destruct_b = local.my_domain_com.my_lib.destruct_b.DestructBExecution(
            self.scheduler,
            self.trace_execution,
            "destruct_b",
        )
        self.execution_trigger_position_box__action_destruct_a = local.my_domain_com.my_lib.destruct_a.DestructAExecution(
            self.scheduler,
            self.trace_execution,
            "destruct_a",
        )
        self.scheduler.submit(self.destroy_position_box)
        self.scheduler.submit(self.trigger_position_box__action_construct_a__action_parent)
        self.scheduler.submit(self.trigger_position_box__action_construct_b__action_parent)
        self.scheduler.submit(self.trigger_position_box__action_destruct_b__action_parent)
        self.scheduler.submit(self.trigger_position_box__action_destruct_a__action_parent)
        self.scheduler.submit(self.trigger_position_box__action_construct_a__action_parent)
        self.scheduler.submit(self.trigger_position_box__action_construct_b__action_parent)
        self.scheduler.submit(self.trigger_position_box__action_destruct_b__action_parent)
        self.trigger_position_box__action_destruct_a__action_parent()

    def destroy_position_box(self):
        self.action.get_interface_position(
            "position<box>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box",
            1,
        )

    def trigger_position_box__action_construct_a__action_parent(self):
        if not self.join_for_trigger_position_box__action_construct_a__action_parent.arrive():
            return
        self.execution_trigger_position_box__action_construct_a.accept_action_parent()

    def trigger_position_box__action_construct_b__action_parent(self):
        if not self.join_for_trigger_position_box__action_construct_b__action_parent.arrive():
            return
        self.execution_trigger_position_box__action_construct_b.accept_action_parent()

    def trigger_position_box__action_destruct_b__action_parent(self):
        if not self.join_for_trigger_position_box__action_destruct_b__action_parent.arrive():
            return
        self.execution_trigger_position_box__action_destruct_b.accept_action_parent()

    def trigger_position_box__action_destruct_a__action_parent(self):
        if not self.join_for_trigger_position_box__action_destruct_a__action_parent.arrive():
            return
        self.execution_trigger_position_box__action_destruct_a.accept_action_parent()
