"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.middle


class Test(literal.Action):

    @override
    def run(self):
        holder = literal.LocalPosition(
            "position<holder>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
        )
        holder.create_particle()
        literal.record_operation("test.create(holder)")
        holder.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(holder::/middle::trigger_pos)")
        holder.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).run()
        holder.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(holder::/middle::trigger_pos)")
        holder.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(holder::/middle::trigger_pos)")
        holder.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).run()
        holder.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(holder::/middle::trigger_pos)")
        holder.destroy_particle()
        literal.record_operation("test.destroy(holder)")
