"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal


class DoThing(literal.Action):
    _typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/do_thing>"

    def __init__(self):
        super().__init__(
            interface_positions=[
                literal.InterfacePosition("position<trigger_pos>"),
            ],
            trigger_position_name="position<trigger_pos>",
        )

    @override
    def execute(self):
        local_pos = literal.LocalPosition("position<local_pos>")
        local_pos.create_dimension_point()


class Test(literal.GlobalPosition):
    _typed_name: ClassVar[str] = "position<my.domain.com:my_lib:/test>"
    constraints: ClassVar[list[literal.Constraint]] = [
        DoThing,
    ]

    @override
    def after_assigned(self):
        self.create_dimension_point()
        self.dimension_point.get_action(
            "action<my.domain.com:my_lib:/do_thing>"
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_dimension_point()


def main():
    literal.start(Test())


if __name__ == "__main__":
    main()
