"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.outer_destructor


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
            TestGuarantees(),
        )
        execution.create_position_outer()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_position_outer__action_outer_destructor = local.my_domain_com.my_lib.outer_destructor.OuterDestructorGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        guarantees: TestGuarantees,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = guarantees
        self.local_position_outer = literal.LocalPosition(
            "position<outer>",
            constraints=(
                local.my_domain_com.my_lib.outer_destructor.OuterDestructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_trigger_position_outer__action_outer_destructor: local.my_domain_com.my_lib.outer_destructor.OuterDestructorExecution
        self.join_for_trigger_position_outer__action_outer_destructor__action_parent = self.scheduler.create_join(2)

    def create_position_outer(self):
        self.local_position_outer.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "outer",
            1,
        )
        self.execution_trigger_position_outer__action_outer_destructor = local.my_domain_com.my_lib.outer_destructor.OuterDestructorExecution(
            self.scheduler,
            self.trace_execution,
            "outer_destructor",
            self.guarantees.trigger_position_outer__action_outer_destructor,
        )
        self.scheduler.submit(self.destroy_position_outer)
        self.scheduler.submit(self.trigger_position_outer__action_outer_destructor__action_parent)
        self.trigger_position_outer__action_outer_destructor__action_parent()

    def destroy_position_outer(self):
        self.local_position_outer.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "outer",
            1,
        )

    def trigger_position_outer__action_outer_destructor__action_parent(self):
        if not self.join_for_trigger_position_outer__action_outer_destructor__action_parent.arrive():
            return
        self.execution_trigger_position_outer__action_outer_destructor.accept_action_parent()
