"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.parent


class Test(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
        local.my_domain_com.my_lib.inner.Inner,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        literal.record_operation("test.create(/parent)")
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        literal.record_operation("test.create(/parent::/child)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        literal.record_operation("test.create(/inner::trigger_pos)")
        self.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).run()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        literal.record_operation("test.destroy(/inner::trigger_pos)")
