"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_result = literal.LocalPosition(
            "position<result>",
            scheduler=self.scheduler,
        )

    def on_action_parent_occupied(self):
        self.create_position_result()

    def create_position_result(self):
        self.local_position_result.create_particle()
        self.local_position_result.destroy_particle()
