[project]
name = "define-tools"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "click",
    "lark",
    "pygithub",
    "pyyaml",
    "requests",
]

[dependency-groups]
dev = [
    "pytest>=6",
]

[tool.basedpyright]
exclude = ["bazel-*"]

[tool.ruff]
extend = "../pyproject.toml"
