"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.triggered


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.triggered.Triggered,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.scheduler.submit(execution.create_global_action_triggered__position_input)
        execution.create_global_action_triggered__position_run()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_global_action_triggered = local.my_domain_com.my_lib.triggered.TriggeredGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.trigger_global_action_triggered__execution: local.my_domain_com.my_lib.triggered.TriggeredExecution
        self.join_for_trigger_global_action_triggered__for_empty_rule_position_input__global_position_child = literal.Join(2)

    def create_global_action_triggered__position_input(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.Triggered
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.Triggered
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.trigger_global_action_triggered__for_empty_rule_position_input__global_position_child()

    def create_global_action_triggered__position_run(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.Triggered
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.init_trigger_global_action_triggered__execution()
        self.trigger_global_action_triggered__for_empty_rule_position_input__global_position_child()

    def init_trigger_global_action_triggered__execution(self):
        action = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.Triggered
        )
        self.trigger_global_action_triggered__execution = local.my_domain_com.my_lib.triggered.TriggeredExecution(
            action,
            self.scheduler,
            self.guarantees.trigger_global_action_triggered,
        )

    def trigger_global_action_triggered__for_empty_rule_position_input__global_position_child(self):
        if not self.join_for_trigger_global_action_triggered__for_empty_rule_position_input__global_position_child.arrive():
            return
        self.trigger_global_action_triggered__execution.accept_for_empty_rule_position_input__global_position_child()
