"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.fifth
import local.my_domain_com.my_lib.fifth_destructor
import local.my_domain_com.my_lib.first
import local.my_domain_com.my_lib.first_destructor
import local.my_domain_com.my_lib.fourth_destructor
import local.my_domain_com.my_lib.second_destructor
import local.my_domain_com.my_lib.third
import local.my_domain_com.my_lib.third_destructor


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.create_position_carrier()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()
        self.trigger_action_destroyer__position_target__action_fifth_destructor = local.my_domain_com.my_lib.fifth_destructor.FifthDestructorGuarantees()
        self.trigger_action_destroyer__position_target__action_third_destructor = local.my_domain_com.my_lib.third_destructor.ThirdDestructorGuarantees()
        self.trigger_action_destroyer__position_target__action_first_destructor = local.my_domain_com.my_lib.first_destructor.FirstDestructorGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.first.First,
                local.my_domain_com.my_lib.first_destructor.FirstDestructor,
                local.my_domain_com.my_lib.second_destructor.SecondDestructor,
                local.my_domain_com.my_lib.third.Third,
                local.my_domain_com.my_lib.third_destructor.ThirdDestructor,
                local.my_domain_com.my_lib.fourth_destructor.FourthDestructor,
                local.my_domain_com.my_lib.fifth.Fifth,
                local.my_domain_com.my_lib.fifth_destructor.FifthDestructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_trigger_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_trigger_action_destroyer: literal.DestructionConnection
        self.execution_trigger_action_destroyer__position_target__action_fifth_destructor: local.my_domain_com.my_lib.fifth_destructor.FifthDestructorExecution
        self.execution_trigger_action_destroyer__position_target__action_third_destructor: local.my_domain_com.my_lib.third_destructor.ThirdDestructorExecution
        self.execution_trigger_action_destroyer__position_target__action_first_destructor: local.my_domain_com.my_lib.first_destructor.FirstDestructorExecution
        self.join_for_move_position_carrier_to_action_destroyer__position_target = self.scheduler.create_join(3)
        self.join_for_trigger_action_destroyer__when_empty_position_target__global_position_second = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__when_empty_position_target__global_position_fourth = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__when_empty_position_target__global_position_marker = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__when_occupied_position_target = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_fifth = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_marker = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_third = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_marker = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_first = self.scheduler.create_join(2)
        self.join_for_trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_marker = self.scheduler.create_join(2)

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.scheduler.submit(self.create_position_carrier__global_position_first)
        self.scheduler.submit(self.create_position_carrier__global_position_third)
        self.create_position_carrier__global_position_fifth()

    def create_position_carrier__global_position_first(self):
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.first.First
        ).create_particle()
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.first.First
        ).destroy_particle()
        self.move_position_carrier_to_action_destroyer__position_target()

    def create_position_carrier__global_position_third(self):
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.third.Third
        ).create_particle()
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.third.Third
        ).destroy_particle()
        self.move_position_carrier_to_action_destroyer__position_target()

    def create_position_carrier__global_position_fifth(self):
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.fifth.Fifth
        ).create_particle()
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.fifth.Fifth
        ).destroy_particle()
        self.move_position_carrier_to_action_destroyer__position_target()

    def move_position_carrier_to_action_destroyer__position_target(self):
        if not self.join_for_move_position_carrier_to_action_destroyer__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.execution_trigger_action_destroyer__position_target__action_fifth_destructor = local.my_domain_com.my_lib.fifth_destructor.FifthDestructorExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.fifth_destructor.FifthDestructor
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer__position_target__action_fifth_destructor,
        )
        self.execution_trigger_action_destroyer__position_target__action_third_destructor = local.my_domain_com.my_lib.third_destructor.ThirdDestructorExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.third_destructor.ThirdDestructor
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer__position_target__action_third_destructor,
        )
        self.execution_trigger_action_destroyer__position_target__action_first_destructor = local.my_domain_com.my_lib.first_destructor.FirstDestructorExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.first_destructor.FirstDestructor
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer__position_target__action_first_destructor,
        )
        self.destruction_connection_trigger_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            6,
            self.trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_fifth,
            self.trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_marker,
            self.trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_third,
            self.trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_marker,
            self.trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_first,
            self.trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_marker,
        )
        self.guarantees.trigger_action_destroyer__position_target__action_fifth_destructor.guarantee_global_position_fifth.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.guarantees.trigger_action_destroyer__position_target__action_fifth_destructor.guarantee_global_position_marker.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.guarantees.trigger_action_destroyer__position_target__action_third_destructor.guarantee_global_position_third.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.guarantees.trigger_action_destroyer__position_target__action_third_destructor.guarantee_global_position_marker.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.guarantees.trigger_action_destroyer__position_target__action_first_destructor.guarantee_global_position_first.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.guarantees.trigger_action_destroyer__position_target__action_first_destructor.guarantee_global_position_marker.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.execution_trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_trigger_action_destroyer,
            },
            ),
        )
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_target__global_position_second)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_target__global_position_fourth)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_target__global_position_marker)
        self.scheduler.submit(self.trigger_action_destroyer__when_occupied_position_target)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_target__global_position_second)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_target__global_position_fourth)
        self.scheduler.submit(self.trigger_action_destroyer__when_empty_position_target__global_position_marker)
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_target)
        self.scheduler.submit(self.trigger_action_destroyer__when_occupied_position_target)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_fifth)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_marker)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_third)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_marker)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_first)
        self.trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_marker()

    def trigger_action_destroyer__when_empty_position_target__global_position_second(self):
        if not self.join_for_trigger_action_destroyer__when_empty_position_target__global_position_second.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_empty_position_target__global_position_second()

    def trigger_action_destroyer__when_empty_position_target__global_position_fourth(self):
        if not self.join_for_trigger_action_destroyer__when_empty_position_target__global_position_fourth.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_empty_position_target__global_position_fourth()

    def trigger_action_destroyer__when_empty_position_target__global_position_marker(self):
        if not self.join_for_trigger_action_destroyer__when_empty_position_target__global_position_marker.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_empty_position_target__global_position_marker()

    def trigger_action_destroyer__for_empty_rule_position_target(self):
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_target()

    def trigger_action_destroyer__when_occupied_position_target(self):
        if not self.join_for_trigger_action_destroyer__when_occupied_position_target.arrive():
            return
        self.execution_trigger_action_destroyer.accept_when_occupied_position_target()

    def trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_fifth(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_fifth.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_fifth_destructor.accept_when_empty_global_position_fifth()

    def trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_marker(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_fifth_destructor__when_empty_global_position_marker.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_fifth_destructor.accept_when_empty_global_position_marker()

    def trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_third(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_third.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_third_destructor.accept_when_empty_global_position_third()

    def trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_marker(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_third_destructor__when_empty_global_position_marker.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_third_destructor.accept_when_empty_global_position_marker()

    def trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_first(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_first.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_first_destructor.accept_when_empty_global_position_first()

    def trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_marker(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_first_destructor__when_empty_global_position_marker.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_first_destructor.accept_when_empty_global_position_marker()
