"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.first
import local.my_domain_com.my_lib.origin
import local.my_domain_com.my_lib.second


class Test(literal.EntryPoint):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<box>",
                    constraints=(
                        local.my_domain_com.my_lib.origin.Origin,
                        local.my_domain_com.my_lib.destination.Destination,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.create_position_box()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.join_for_move_position_box__global_position_origin_to_position_box__global_position_destination = self.scheduler.create_join(2)

    def create_position_box(self):
        self.action.get_interface_position(
            "position<box>"
        ).create_particle()
        self.action.get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.origin.Origin
        ).create_particle()
        self.scheduler.submit(self.create_position_box__global_position_origin__global_position_first)
        self.create_position_box__global_position_origin__global_position_second()

    def create_position_box__global_position_origin__global_position_first(self):
        self.action.get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.origin.Origin
        ).particle.get_position(
            local.my_domain_com.my_lib.first.First
        ).create_particle()
        self.move_position_box__global_position_origin_to_position_box__global_position_destination()

    def create_position_box__global_position_origin__global_position_second(self):
        self.action.get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.origin.Origin
        ).particle.get_position(
            local.my_domain_com.my_lib.second.Second
        ).create_particle()
        self.move_position_box__global_position_origin_to_position_box__global_position_destination()

    def move_position_box__global_position_origin_to_position_box__global_position_destination(self):
        if not self.join_for_move_position_box__global_position_origin_to_position_box__global_position_destination.arrive():
            return
        self.action.get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.origin.Origin
        ).move_particle_to(
            self.action.get_interface_position(
                "position<box>"
            ).particle.get_position(
                local.my_domain_com.my_lib.destination.Destination
            )
        )
