"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.caller
import local.my_domain_com.my_lib.implied


class Outer(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/outer>"
    implied_qualities: ClassVar[tuple[type[literal.Constraint], ...]] = (
        local.my_domain_com.my_lib.implied.Implied,
        local.my_domain_com.my_lib.caller.Caller,
    )

    def __init__(self):
        super().__init__(
            interface_positions=[
                literal.InterfacePosition("position<run>"),
            ],
            trigger_position_name="position<run>",
        )

    @override
    def execute(self):
        self.get_interface_position(
            "position<run>"
        ).create_dimension_point()
        self.create_dimension_point()
