"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal


class DestructA(literal.Action):
    pass


@final
class DestructAExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position__noop_a = literal.LocalPosition(
            "position<_noop_a>",
            scheduler=self.scheduler,
        )

    def on_action_parent_occupied(self):
        self.create_position_noop_a()

    def create_position_noop_a(self):
        self.local_position__noop_a.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "_noop_a",
            1,
        )
        self.local_position__noop_a.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "_noop_a",
            1,
        )
