"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.left
import local.my_domain_com.my_lib.marker
import local.my_domain_com.my_lib.right


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
        local.my_domain_com.my_lib.left.Left,
        local.my_domain_com.my_lib.right.Right,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.join_when_empty_global_position_right = literal.NO_JOIN
        execution.join_for_move_global_position_left_to_global_position_right = scheduler.create_join(2)
        scheduler.submit(execution.accept_when_empty_global_position_left)
        execution.accept_when_empty_global_position_right()


@final
class TestGuarantees:
    def __init__(self):
        self.global_position_left = literal.Guarantee()
        self.global_position_right = literal.Guarantee()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = TestGuarantees()
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_action_destroyer: literal.DestructionConnection
        self.execution_action_destroyer__position_target__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_action_destroyer__position_target__global_position_marker: literal.Position
        self.join_for_move_global_position_left_to_global_position_right: literal.Join
        self.join_for_destroy_action_destroyer__position_target__global_position_marker = self.scheduler.create_join(2)
        self.join_when_empty_global_position_right: literal.Join
        self.destruction_connection_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_destroyer__position_target__global_position_marker,
        )
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_action_destroyer,
            },
            ),
        )
        self.execution_action_destroyer.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_target = literal.NO_JOIN

    def accept_when_empty_global_position_left(self):
        self.create_global_position_left()

    def accept_when_empty_global_position_right(self):
        if not self.join_when_empty_global_position_right.arrive():
            return
        self.move_global_position_left_to_global_position_right()

    def create_global_position_left(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.left.Left
        ).create_particle()
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.left.Left
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        self.move_global_position_left_to_global_position_right()

    def move_global_position_left_to_global_position_right(self):
        if not self.join_for_move_global_position_left_to_global_position_right.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.left.Left
        ).move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.right.Right
            )
        )
        self.guarantees.global_position_left.publish(
            self.scheduler,
            self.move_global_position_right_to_action_destroyer__position_target,
        )

    def move_global_position_right_to_action_destroyer__position_target(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.right.Right
        ).move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.execution_action_destroyer__position_target__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.destructor.Destructor
            ),
            self.scheduler,
        )
        self.execution_action_destroyer__position_target__action_destructor.join_for_empty_rule_global_position_marker = literal.NO_JOIN
        self.execution_action_destroyer__position_target__action_destructor.join_for_move_global_position_marker_to_position_holder = literal.NO_JOIN
        self.execution_action_destroyer__position_target__action_destructor.guarantees.global_position_marker.consumers.append(
            self.destroy_action_destroyer__position_target__global_position_marker
        )
        self.guarantees.global_position_right.publish(
            self.scheduler,
            self.execution_action_destroyer.accept_for_empty_rule_position_target,
            self.execution_action_destroyer__position_target__action_destructor.accept_for_empty_rule_global_position_marker,
        )

    def destroy_action_destroyer__position_target__global_position_marker(self):
        if not self.join_for_destroy_action_destroyer__position_target__global_position_marker.arrive():
            return
        self.destruction_position_action_destroyer__position_target__global_position_marker = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        )
        self.destruction_position_action_destroyer__position_target__global_position_marker.destroy_particle()
        self.destruction_connection_action_destroyer.complete()
