"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.box
import local.my_domain_com.my_lib.input


class Producer(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.box.Box,
        local.my_domain_com.my_lib.input.Input,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition("position<trigger_pos>"),
            ],
        )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).move_particle_to(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.box.Box
            )
        )
