"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.transitive


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            TestGuarantees(),
        )
        execution.create_position_source()


@final
class TestGuarantees:
    def __init__(self):
        self.trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerGuarantees()
        self.trigger_action_destroyer__position_target__action_destructor = local.my_domain_com.my_lib.destructor.DestructorGuarantees()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        guarantees: TestGuarantees,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = guarantees
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.destructor.Destructor,
            ),
            scheduler=self.scheduler,
        )
        guarantees.trigger_action_destroyer__position_target__action_destructor.guarantee_position_occupied_last.append(
            self.destroy_action_destroyer__position_target__action_destructor__position_occupied_last
        )
        guarantees.trigger_action_destroyer__position_target__action_destructor.guarantee_position_occupied_first__global_position_transitive.append(
            self.destroy_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive
        )
        guarantees.trigger_action_destroyer__position_target__action_destructor.guarantee_position_occupied_first.append(
            self.destroy_action_destroyer__position_target__action_destructor__position_occupied_first
        )
        self.execution_trigger_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_trigger_action_destroyer: literal.DestructionConnection
        self.execution_trigger_action_destroyer__position_target__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_last: literal.Position
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive: literal.Position
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_first: literal.Position
        self.join_for_move_position_source_to_action_destroyer__position_target = literal.Join(2)
        self.join_for_destroy_action_destroyer__position_target__action_destructor__position_occupied_last = literal.Join(2)
        self.join_for_destroy_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive = literal.Join(2)
        self.join_for_destroy_action_destroyer__position_target__action_destructor__position_occupied_first = literal.Join(2)
        self.join_for_trigger_action_destroyer__for_empty_rule_position_target = literal.Join(2)
        self.join_for_trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_first = literal.Join(2)
        self.join_for_trigger_action_destroyer__position_target__action_destructor__when_empty_position_empty = literal.Join(2)
        self.join_for_trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_last = literal.Join(2)

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.submit(self.create_position_source__action_destructor__position_occupied_first)
        self.create_position_source__action_destructor__position_occupied_last()

    def create_position_source__action_destructor__position_occupied_first(self):
        self.local_position_source.particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).get_interface_position(
            "position<occupied_first>"
        ).create_particle()
        self.local_position_source.particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).get_interface_position(
            "position<occupied_first>"
        ).particle.get_position(
            local.my_domain_com.my_lib.transitive.Transitive
        ).create_particle()
        self.move_position_source_to_action_destroyer__position_target()

    def create_position_source__action_destructor__position_occupied_last(self):
        self.local_position_source.particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).get_interface_position(
            "position<occupied_last>"
        ).create_particle()
        self.move_position_source_to_action_destroyer__position_target()

    def move_position_source_to_action_destroyer__position_target(self):
        if not self.join_for_move_position_source_to_action_destroyer__position_target.arrive():
            return
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.execution_trigger_action_destroyer__position_target__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.destructor.Destructor
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer__position_target__action_destructor,
        )
        self.destruction_connection_trigger_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            3,
            self.destroy_action_destroyer__position_target__action_destructor__position_occupied_last,
            self.destroy_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive,
            self.trigger_action_destroyer__position_target__action_destructor__when_empty_position_empty,
        )
        self.guarantees.trigger_action_destroyer__position_target__action_destructor.guarantee_position_empty.append(
            self.destruction_connection_trigger_action_destroyer.complete
        )
        self.execution_trigger_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.guarantees.trigger_action_destroyer,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_trigger_action_destroyer,
            },
            ),
        )
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_target)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_first)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_last)
        self.scheduler.submit(self.trigger_action_destroyer__for_empty_rule_position_target)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_first)
        self.scheduler.submit(self.trigger_action_destroyer__position_target__action_destructor__when_empty_position_empty)
        self.trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_last()

    def destroy_action_destroyer__position_target__action_destructor__position_occupied_last(self):
        if not self.join_for_destroy_action_destroyer__position_target__action_destructor__position_occupied_last.arrive():
            return
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_last = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).get_interface_position(
            "position<occupied_last>"
        )
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_last.destroy_particle()
        self.destruction_connection_trigger_action_destroyer.complete()

    def destroy_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive(self):
        if not self.join_for_destroy_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive.arrive():
            return
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).get_interface_position(
            "position<occupied_first>"
        ).particle.get_position(
            local.my_domain_com.my_lib.transitive.Transitive
        )
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_first__global_position_transitive.destroy_particle()
        self.destroy_action_destroyer__position_target__action_destructor__position_occupied_first()

    def destroy_action_destroyer__position_target__action_destructor__position_occupied_first(self):
        if not self.join_for_destroy_action_destroyer__position_target__action_destructor__position_occupied_first.arrive():
            return
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_first = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_action(
            local.my_domain_com.my_lib.destructor.Destructor
        ).get_interface_position(
            "position<occupied_first>"
        )
        self.destruction_position_action_destroyer__position_target__action_destructor__position_occupied_first.destroy_particle()
        self.destruction_connection_trigger_action_destroyer.complete()

    def trigger_action_destroyer__for_empty_rule_position_target(self):
        if not self.join_for_trigger_action_destroyer__for_empty_rule_position_target.arrive():
            return
        self.execution_trigger_action_destroyer.accept_for_empty_rule_position_target()

    def trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_first(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_first.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_destructor.accept_for_empty_rule_position_occupied_first()

    def trigger_action_destroyer__position_target__action_destructor__when_empty_position_empty(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_destructor__when_empty_position_empty.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_destructor.accept_when_empty_position_empty()

    def trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_last(self):
        if not self.join_for_trigger_action_destroyer__position_target__action_destructor__for_empty_rule_position_occupied_last.arrive():
            return
        self.execution_trigger_action_destroyer__position_target__action_destructor.accept_for_empty_rule_position_occupied_last()
