load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

exports_files(["grammar.lark"])

py_library(
    name = "exceptions",
    srcs = ["exceptions.py"],
    visibility = [
        "//defcl/python:__subpackages__",
        "//define/compiler:__pkg__",
    ],
    deps = ["//defcl/python/lark:lark_standalone"],
)

py_library(
    name = "parser",
    srcs = ["parser.py"],
    visibility = ["//define/compiler:__pkg__"],
    deps = [
        "//defcl/python/validator:semantics",
        "//defcl/python/validator:syntax",
        "@pypi//protobuf",
    ],
)

py_test(
    name = "parser_test",
    size = "small",
    srcs = ["parser_test.py"],
    data = ["//defcl/testdata:testdata_files"],
    deps = [
        ":exceptions",
        ":parser",
        "//defcl/testdata/valid/schemas:integers_proto_py",
        "//defcl/testdata/valid/schemas:nested_messages_proto_py",
        "//defcl/testdata/valid/schemas:repeated_messages_proto_py",
        "//defcl/testdata/valid/schemas:single_toplevel_proto_py",
        "//defcl/testdata/valid/schemas:strings_proto_py",
        "@pypi//pytest",
    ],
)

py_library(
    name = "python",
    srcs = ["__init__.py"],
    visibility = ["//defcl/python:__subpackages__"],
    deps = ["//defcl"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

# IMPORTANT: When adding a new py_library, py_binary, or py_test target to this
# package or its sub-packages, you must also add it to the deps list below.
pyright_test(
    name = "pyright_test",
    tags = ["include-subpackages"],
    deps = [
        ":exceptions",
        ":parser",
        ":parser_test",
        ":python",
        "//defcl/python/lark",
        "//defcl/python/validator",
        "//defcl/python/validator:semantics",
        "//defcl/python/validator:semantics_test",
        "//defcl/python/validator:syntax",
        "//defcl/python/validator:syntax_test",
    ],
)
