"""Generated by the Define compiler."""

from typing import ClassVar, Never, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.fifth
import local.my_domain_com.my_lib.fifth_destructor
import local.my_domain_com.my_lib.first
import local.my_domain_com.my_lib.first_destructor
import local.my_domain_com.my_lib.fourth_destructor
import local.my_domain_com.my_lib.second_destructor
import local.my_domain_com.my_lib.third
import local.my_domain_com.my_lib.third_destructor


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.DestroyerAction,
    )

    @override
    def run(self):
        carrier = literal.LocalPosition[Never](
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.first.FirstPosition,
                local.my_domain_com.my_lib.first_destructor.FirstDestructorAction,
                local.my_domain_com.my_lib.second_destructor.SecondDestructorAction,
                local.my_domain_com.my_lib.third.ThirdPosition,
                local.my_domain_com.my_lib.third_destructor.ThirdDestructorAction,
                local.my_domain_com.my_lib.fourth_destructor.FourthDestructorAction,
                local.my_domain_com.my_lib.fifth.FifthPosition,
                local.my_domain_com.my_lib.fifth_destructor.FifthDestructorAction,
            ),
        )
        carrier.create_particle()
        carrier.particle.get_position(
            local.my_domain_com.my_lib.first.FirstPosition
        ).create_particle()
        carrier.particle.get_position(
            local.my_domain_com.my_lib.first.FirstPosition
        ).destroy_particle()
        carrier.particle.get_position(
            local.my_domain_com.my_lib.third.ThirdPosition
        ).create_particle()
        carrier.particle.get_position(
            local.my_domain_com.my_lib.third.ThirdPosition
        ).destroy_particle()
        carrier.particle.get_position(
            local.my_domain_com.my_lib.fifth.FifthPosition
        ).create_particle()
        carrier.particle.get_position(
            local.my_domain_com.my_lib.fifth.FifthPosition
        ).destroy_particle()
        carrier.move_particle_to(
            self.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.DestroyerAction
            ).get_interface_position(
                "position<target>"
            )
        )
        self.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.DestroyerAction
        ).run(DestroyerDestructionContracts())


class DestroyerDestructionContracts(local.my_domain_com.my_lib.destroyer.DestroyerDestructionContracts):

    @override
    def run_destructors_position_target(self, particle: literal.Particle):
        particle.get_action(
            local.my_domain_com.my_lib.fifth_destructor.FifthDestructorAction
        ).run()
        particle.get_action(
            local.my_domain_com.my_lib.third_destructor.ThirdDestructorAction
        ).run()
        particle.get_action(
            local.my_domain_com.my_lib.first_destructor.FirstDestructorAction
        ).run()
