"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.grandchild
import local.my_domain_com.my_lib.greatgrandchild
import local.my_domain_com.my_lib.other
import local.my_domain_com.my_lib.parent


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.ParentPosition,
        local.my_domain_com.my_lib.other.OtherAction,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.GrandchildPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.parent.ParentPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.GrandchildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.greatgrandchild.GreatgrandchildPosition
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).run()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<out>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.GrandchildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.greatgrandchild.GreatgrandchildPosition
        ).destroy_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<out>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.GrandchildPosition
        ).destroy_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<out>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.ChildPosition
        ).destroy_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<out>"
        ).destroy_particle()
        self.on_particle.get_action(
            local.my_domain_com.my_lib.other.OtherAction
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
