"""Generated by the Define compiler."""

from typing import ClassVar

from define.runtime import literal

import local.my_domain_com.my_lib.number.rational


class Item(literal.GlobalPosition):
    constraints: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.number.rational.NumberRational,
    )
