load("@aspect_rules_py//py:defs.bzl", "py_library", "py_test")
load("//tools/lint:format.bzl", "format_test")
load("//tools/lint:pyright.bzl", "pyright_test")

py_library(
    name = "file_validator",
    srcs = ["file_validator.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":name_validators",
        ":scope_tracker",
        ":stats",
        ":validation_result",
        "//define/compiler:ast",
        "//define/compiler:constants",
        "//define/compiler:diagnostics",
        "//define/compiler:exceptions",
        "//define/compiler:parser",
        "//define/compiler:parser_error_classification",
        "//define/compiler:parser_exceptions",
        "//define/compiler:transformer",
        "//define/compiler/lark:lark_standalone",
    ],
)

py_test(
    name = "file_validator_test",
    size = "small",
    srcs = ["file_validator_test.py"],
    pytest_main = True,
    deps = [
        ":file_validator",
        "//define/compiler:diagnostics",
        "//define/compiler:exceptions",
        "//define/compiler:parser",
        "@pypi//pytest",
    ],
)

py_library(
    name = "name_validators",
    srcs = ["name_validators.py"],
    data = ["//define/reserved_words"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
    ],
)

py_test(
    name = "name_validators_test",
    size = "small",
    srcs = ["name_validators_test.py"],
    pytest_main = True,
    deps = [
        ":name_validators",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "@pypi//pytest",
    ],
)

py_library(
    name = "path_tracker",
    srcs = ["path_tracker.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = ["@pypi//pygtrie"],
)

py_test(
    name = "path_tracker_test",
    size = "small",
    srcs = ["path_tracker_test.py"],
    pytest_main = True,
    deps = [
        ":path_tracker",
        "@pypi//pygtrie",
        "@pypi//pytest",
    ],
)

py_library(
    name = "program_validator",
    srcs = ["program_validator.py"],
    visibility = [
        "//define/compiler:__pkg__",
        "//define/compiler:__subpackages__",
    ],
    deps = [
        ":file_validator",
        ":path_tracker",
        ":reference_graph",
        ":stats",
        ":validation_result",
        "//define/compiler:config",
        "//define/compiler:constants",
        "//define/compiler:diagnostics",
        "//define/compiler:exceptions",
        "//define/compiler:parser",
    ],
)

py_library(
    name = "scope_tracker",
    srcs = ["scope_tracker.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = ["//define/compiler:ast"],
)

py_test(
    name = "scope_tracker_test",
    size = "small",
    srcs = ["scope_tracker_test.py"],
    pytest_main = True,
    deps = [
        ":scope_tracker",
        "//define/compiler:ast",
        "@pypi//pytest",
    ],
)

py_library(
    name = "reference_graph",
    srcs = ["reference_graph.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

py_test(
    name = "reference_graph_test",
    size = "small",
    srcs = ["reference_graph_test.py"],
    deps = [":reference_graph"],
)

py_library(
    name = "stats",
    srcs = ["stats.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

py_test(
    name = "stats_test",
    size = "small",
    srcs = ["stats_test.py"],
    pytest_main = True,
    deps = [
        ":stats",
        "@pypi//pytest",
    ],
)

py_library(
    name = "validation_result",
    srcs = ["validation_result.py"],
    visibility = [
        "//define/compiler:__pkg__",
        "//define/compiler:__subpackages__",
    ],
    deps = [
        ":stats",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "//define/compiler:exceptions",
        "//define/compiler/lark:lark_standalone",
    ],
)

py_test(
    name = "validation_result_test",
    size = "small",
    srcs = ["validation_result_test.py"],
    pytest_main = True,
    deps = [
        ":stats",
        ":validation_result",
        "//define/compiler:parser",
        "//define/compiler:transformer",
        "@pypi//pytest",
    ],
)

py_library(
    name = "validator",
    srcs = ["__init__.py"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    deps = [
        ":file_validator",
        ":file_validator_test",
        ":name_validators",
        ":name_validators_test",
        ":path_tracker",
        ":path_tracker_test",
        ":program_validator",
        ":reference_graph",
        ":reference_graph_test",
        ":scope_tracker",
        ":scope_tracker_test",
        ":stats",
        ":stats_test",
        ":validation_result",
        ":validation_result_test",
        ":validator",
    ],
)
