"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.item
import local.my_domain_com.my_lib.payload


class Test(literal.Action):

    @override
    def run(self):
        box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.item.Item,
                local.my_domain_com.my_lib.destination.Destination,
            ),
        )
        holder = literal.LocalPosition(
            "position<holder>",
            constraints=(
                local.my_domain_com.my_lib.payload.Payload,
            ),
        )
        box.create_particle()
        box.particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).create_particle()
        box.particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).particle.get_position(
            local.my_domain_com.my_lib.payload.Payload
        ).create_particle()
        box.particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).move_particle_to(
            holder
        )
        holder.particle.get_position(
            local.my_domain_com.my_lib.payload.Payload
        ).destroy_particle()
        holder.move_particle_to(
            box.particle.get_position(
                local.my_domain_com.my_lib.destination.Destination
            )
        )
        box.particle.get_position(
            local.my_domain_com.my_lib.destination.Destination
        ).destroy_particle()
        box.destroy_particle()
