"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal


class ProvideAction(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition[float]("position<input>"),
                literal.LocalPosition[float]("position<result>"),
            ],
        )

    @override
    def run(self):
        self.get_interface_position(
            "position<input>"
        ).move_particle_to(
            self.get_interface_position(
                "position<result>"
            )
        )
        literal.record_operation("provide.move(input, result)")
