"""Generated by the Define compiler."""

from typing import override

from define.runtime import literal

import local.my_domain_com.my_lib.deep
import local.my_domain_com.my_lib.item
import local.my_domain_com.my_lib.other


class Test(literal.Action):

    @override
    def run(self):
        gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.other.Other,
            ),
        )
        gateway.create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).particle.get_position(
            local.my_domain_com.my_lib.deep.Deep
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).run(OtherDestructionContracts())
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<input>"
        ).destroy_particle()
        gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        gateway.destroy_particle()


class OtherDestructionContracts(local.my_domain_com.my_lib.other.OtherDestructionContracts):

    @override
    def destroy_position_input__position_item(self, particle: literal.Particle):
        particle.get_position(
            local.my_domain_com.my_lib.deep.Deep
        ).destroy_particle()
