"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal

import local.my_domain_com.my_lib.combined
import local.my_domain_com.my_lib.flags
import local.my_domain_com.my_lib.mask
import standard.binary.ascii


class TestAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.flags.FlagsPosition,
        local.my_domain_com.my_lib.mask.MaskPosition,
        local.my_domain_com.my_lib.combined.CombinedPosition,
    )

    @override
    def run(self):
        self.on_particle.get_position(
            local.my_domain_com.my_lib.flags.FlagsPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.mask.MaskPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.combined.CombinedPosition
        ).create_particle()
        self.on_particle.get_position(
            local.my_domain_com.my_lib.flags.FlagsPosition
        ).particle.value = 0b1100
        self.on_particle.get_position(
            local.my_domain_com.my_lib.mask.MaskPosition
        ).particle.value = 0b1010
        self.on_particle.get_position(
            local.my_domain_com.my_lib.combined.CombinedPosition
        ).particle.value = standard.binary.ascii.or_(
            self.on_particle.get_position(
                local.my_domain_com.my_lib.flags.FlagsPosition
            ).particle.value,
            self.on_particle.get_position(
                local.my_domain_com.my_lib.mask.MaskPosition
            ).particle.value,
        )
