"""Generated by the Define compiler."""

from typing import ClassVar, override

from define.runtime import literal


class DoThing(literal.Action):
    typed_name: ClassVar[str] = "action<my.domain.com:my_lib:/do_thing>"

    def __init__(self, on_dimension_point: literal.DimensionPoint):
        super().__init__(
            on_dimension_point,
            interface_positions=[
                literal.InterfacePosition("position<pp>"),
            ],
            trigger_position_name="position<pp>",
        )

    @override
    def execute(self):
        noop = literal.LocalPosition("position<noop>")
        noop.create_dimension_point()
