"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.out
import local.my_domain_com.my_lib.slot


class Helper(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.slot.Slot,
        local.my_domain_com.my_lib.out.Out,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class HelperGuarantees:
    def __init__(self):
        self.global_position_slot__move__global_position_out = literal.Guarantee()


@final
class HelperExecution:
    def __init__(
        self,
        action: Helper,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = HelperGuarantees()
        self.join_for_move_global_position_slot_to_global_position_out: literal.Join
        self.join_for_empty_rule_global_position_slot: literal.Join

    def accept_for_empty_rule_global_position_slot(self):
        if not self.join_for_empty_rule_global_position_slot.arrive():
            return
        self.move_global_position_slot_to_global_position_out()

    def move_global_position_slot_to_global_position_out(self):
        if not self.join_for_move_global_position_slot_to_global_position_out.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.slot.Slot
        ).move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.out.Out
            )
        )
        self.guarantees.global_position_slot__move__global_position_out.publish(
            self.scheduler,
        )
