name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  # Needed for the buf action to leave a comment explaining what's wrong.
  pull-requests: write

jobs:
  coverage:
    if: >-
      github.event.pull_request.user.login != 'renovate[bot]' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-coverage
          repository-cache: true

      - name: Coverage
        run: >-
          bazelisk coverage --noshow_progress //... --combined_report=lcov
          --instrumentation_filter='^//(define|defcl|tools)[/:]'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          disable_search: true
          fail_ci_if_error: true
          files: bazel-out/_coverage/_coverage_report.dat
          token: ${{ secrets.CODECOV_TOKEN }}

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-${{ matrix.os }}
          repository-cache: true

      - name: Test
        run: bazelisk test --noshow_progress //...

      - name: Additional Build
        run: bazelisk build --noshow_progress //...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Format
        run: bazelisk run --noshow_progress //tools:format.check

      - name: Build buf plugin
        run: bazelisk build --noshow_progress //defcl/buf

      - uses: bufbuild/buf-action@v1
        with:
          breaking: false
          push: false
          format: false
