load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:build_file_checks.bzl", "check_build_file")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "literal",
    srcs = ["literal.py"],
    visibility = [
        "//define:__subpackages__",
        "//tools:__pkg__",
    ],
)

py_test(
    name = "literal_test",
    size = "small",
    srcs = ["literal_test.py"],
    deps = [
        ":literal",
        "@pypi//pytest",
    ],
)

py_library(
    name = "runtime",
    srcs = ["__init__.py"],
    visibility = ["//define:__subpackages__"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    deps = [
        ":literal",
        ":literal_test",
        ":runtime",
    ],
)

check_build_file()
