load("@aspect_rules_lint//format:defs.bzl", "format_test")
load("@aspect_rules_py//py:defs.bzl", "py_library", "py_test")

py_library(
    name = "semantics",
    srcs = ["semantics.py"],
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        ":validator",
        "//defcl/python:exceptions",
        "@pypi//lark",
        "@pypi//protobuf",
    ],
)

py_test(
    name = "semantics_test",
    size = "small",
    srcs = ["semantics_test.py"],
    data = ["//defcl/testdata:testdata_files"],
    pytest_main = True,
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        ":semantics",
        ":syntax",
        "//defcl/python:exceptions",
        "//defcl/testdata/invalid/semantics/schemas:integer_enum_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:nested_integer_enum_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:nested_no_brackets_message_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:nested_no_brackets_scalar_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:no_brackets_message_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:no_brackets_scalar_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:repeated_integer_enum_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:schemas_py",
        "@pypi//pytest",
    ],
)

py_library(
    name = "syntax",
    srcs = ["syntax.py"],
    data = ["//defcl/python:grammar.lark"],
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        ":validator",
        "//defcl/python:exceptions",
        "@pypi//lark",
    ],
)

py_test(
    name = "syntax_test",
    size = "small",
    srcs = ["syntax_test.py"],
    data = ["//defcl/testdata:testdata_files"],
    pytest_main = True,
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        ":syntax",
        "//defcl/python:exceptions",
        "@pypi//lark",
        "@pypi//pytest",
    ],
)

py_library(
    name = "validator",
    srcs = ["__init__.py"],
    visibility = ["//defcl/python:__pkg__"],
    deps = ["//defcl/python"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@aspect_rules_lint//format:ruff",
)
