load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")

py_library(
    name = "semantics",
    srcs = ["semantics.py"],
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        "//defcl/python:exceptions",
        "//defcl/python/lark:lark_standalone",
        "@pypi//protobuf",
    ],
)

py_test(
    name = "semantics_test",
    size = "small",
    srcs = ["semantics_test.py"],
    data = ["//defcl/testdata:testdata_files"],
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        ":semantics",
        ":syntax",
        "//defcl/python:exceptions",
        "//defcl/testdata/invalid/semantics/schemas:integer_enum_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:nested_integer_enum_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:nested_no_brackets_message_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:nested_no_brackets_scalar_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:no_brackets_message_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:no_brackets_scalar_proto_py",
        "//defcl/testdata/invalid/semantics/schemas:repeated_integer_enum_proto_py",
        "@pypi//pytest",
    ],
)

py_library(
    name = "syntax",
    srcs = ["syntax.py"],
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        "//defcl/python:exceptions",
        "//defcl/python/lark:lark_standalone",
    ],
)

py_test(
    name = "syntax_test",
    size = "small",
    srcs = ["syntax_test.py"],
    data = ["//defcl/testdata:testdata_files"],
    visibility = ["//defcl/python:__pkg__"],
    deps = [
        ":syntax",
        "//defcl/python:exceptions",
        "//defcl/python/lark:lark_standalone",
        "@pypi//pytest",
    ],
)

py_library(
    name = "validator",
    srcs = ["__init__.py"],
    visibility = ["//defcl/python:__pkg__"],
    deps = ["//defcl/python"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)
