"""Generated by the Define compiler."""

from typing import ClassVar

from define.runtime import literal

import local.my_domain_com.child_lib.do_thing
import local.my_domain_com.parent_lib.do_thing


class Test(literal.GlobalPosition):
    _typed_name: ClassVar[str] = "position<my.domain.com:parent_lib:/test>"
    constraints: ClassVar[tuple[literal.Constraint, ...]] = (
        local.my_domain_com.parent_lib.do_thing.DoThing,
        local.my_domain_com.child_lib.do_thing.DoThing,
    )
